Add 172 segment detection for phone rules
gogf/gf pull request #1001
Opened 2020-11-18 02:11 UTC by arieslee

Adding loose phone number verification rules.
Add 172 segment detection for phone rules.

2020-11-19 13:00 UTC, gqcn requested changes

2020-11-19 13:00 UTC, gqcn commented on util/gvalid/gvalid_check.go
> +		"loose-mobile":         {},
规则名称请修改为`phone-loose`，保证统一校验类型前缀。

2020-11-19 13:01 UTC, gqcn commented
@arieslee 感谢贡献，很不错的特性。代码Review了，麻烦有几个小细节看看。

2020-11-21 06:15 UTC, arieslee commented on database/gdb/gdb_core.go
> +	Value interface{} `json:"value"`
这里的value允许接受int和float类型

2020-11-21 06:32 UTC, arieslee commented on database/gdb/gdb_core.go
> +	Value interface{} `json:"value"`
当初的想法是这里的value允许接受int和float类型

2020-11-26 06:23 UTC, arieslee commented on database/gdb/gdb_core.go
> +				fields = append(fields, column+"="+column+"+?")
Value这里是想接受浮点型和整形，所以才没用int

2020-11-26 13:48 UTC, gqcn requested changes

2020-11-26 13:48 UTC, gqcn commented on util/gvalid/i18n/en/validation.toml
> +"gf.gvalid.rule.regex"                = ":attribute value is invalid"
`The :attribute value is invalid`

2020-11-26 13:48 UTC, gqcn commented on go.mod
>  require (
`go.mod`变化有点大，提交之前你先`go mod tidy`一下

2020-11-26 13:48 UTC, gqcn commented on database/gdb/gdb_core.go
> +				fields = append(fields, column+"="+column+"+?")
可以判断一下前面是否带`-`，如果是的话就不需要用`+`连接了，看起来更严谨一些。

2020-11-26 13:48 UTC, gqcn commented on database/gdb/gdb_core.go
> +type UpdateCounter struct {
能不能把这个结构体名称缩短一点方便使用，例如叫`Updater`？

2020-11-27 11:48 UTC, arieslee commented on util/gvalid/i18n/en/validation.toml
> +"gf.gvalid.rule.regex"                = ":attribute value is invalid"
修改了

2020-11-27 11:50 UTC, arieslee commented on database/gdb/gdb_core.go
> +				fields = append(fields, column+"="+column+"+?")
嗯，那样确实贵更严谨一些，我已经修改了

2020-11-27 11:53 UTC, arieslee commented on go.mod
>  require (
先 go mod tidy一下，怕不稳，又复制了现在master上的go.mod的内容替换了。。。

2020-11-27 11:54 UTC, arieslee commented on util/gvalid/i18n/en/validation.toml
> +"gf.gvalid.rule.regex"                = ":attribute value is invalid"
已修改，English水平不行。。。见笑了，哈哈

2020-11-27 16:00 UTC, gqcn requested changes

2020-11-27 16:01 UTC, gqcn commented
@arieslee 另外，你的代码和`master`分支有冲突，你`pull`解决一下冲突再提交。

2020-11-28 02:03 UTC, arieslee commented on database/gdb/gdb_core.go
> +			if c.isCounter(valVarName) {
重新同步一下upstream，冲突应该解决了，另外，判断类型那里也修改了，感谢指点，golang确实刚用没多久，经验不足！不知道断言还可这么玩，你说的第二点，我还是不太明白，为什么要把Value转成int,如果我传的是float呢，转成int就不对了吧？我觉得还是判断Value前面有没有减号来的比较直接一点

2020-11-28 02:03 UTC, arieslee commented on database/gdb/gdb_core.go
> +			if c.isCounter(valVarName) {
重新同步了一下upstream，冲突解决了，另外，判断类型那里也修改了，感谢指点，golang确实刚用没多久，经验不足！不知道断言还可这么玩，你说的第二点，我还是不太明白，为什么要把Value转成int,如果我传的是float呢，转成int就不对了吧？我觉得还是判断Value前面有没有减号来的比较直接一点

2020-11-28 04:09 UTC, closed without merging