improve function empty
gogf/gf pull request #1058
Opened 2020-12-12 13:58 UTC by viken2

2020-12-14 04:47 UTC, gqcn requested changes

2020-12-14 04:47 UTC, gqcn commented on internal/empty/empty.go
> +		case reflect.Bool:
@viken2 These checks are already handled in previous type assertions, why did you add the same checks using reflection here?
![image](https://user-images.githubusercontent.com/26347176/102041419-6a5ce500-3e0a-11eb-8727-0445255a4394.png)

2020-12-24 13:53 UTC, viken2 commented on internal/empty/empty.go
> +		case reflect.Bool:
目前的功能是无法支持自定义类型的判断，比如 type TestInt int，类似这种，var a TestInt = 0 就无法识别

2020-12-24 14:10 UTC, gqcn commented on internal/empty/empty.go
> +		case reflect.Bool:
OK，I get it.

2020-12-24 17:38 UTC, merged