增加 ghttp client 中间件功能
gogf/gf pull request #1119
Opened 2021-01-12 10:24 UTC by eyasliu

fix #1118  

中间件调用使用洋葱模型

调用 `MiddlewareNext` 会继续调用下一个中间件，`MiddlewareAbort` 将会停止中间件调用，也不会发出请求

2021-01-13 12:22 UTC, gqcn requested changes

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_middleware.go
> +var gfHTTPClientMiddlewareAbort = gerror.New("http request abort")
不预定义这个`error`，在报错的时候再生成，通过`gerror.New`产生的`error`带有当前调用堆栈信息，可以用于更好排查错误。

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_middleware.go
> +func (m *clientMiddleware) Next(c *Client, req *http.Request) (resp *ClientResponse, err error) {
参数`c *Client`不用传递，直接绑定到`clientMiddleware`属性上。

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_middleware.go
> +	return c.callRequest(req)
直接在`Next`方法里面循环`handlers`就可以了，逻辑更简单，性能更好，这里没必要递归。

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_middleware.go
> +	m.Abort()
这个`req.Context().Value(gfHTTPClientMiddlewareKey)`的结果可能是`nil`，严谨一点，应该判断一下参数值再做断言转换，然后再调用`Abort`方法。

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_middleware.go
> +		m.err = gfHTTPClientMiddlewareAbort
不用这个`gfHTTPClientMiddlewareAbort`错误，在报错的时候再生成，通过`gerror.New`产生的`error`带有当前调用堆栈信息，可以用于更好排查错误。

2021-01-13 12:22 UTC, gqcn commented on net/ghttp/ghttp_client_request.go
> +// callRequest send http request, return *ClientResponse and error
注释都是以第三人称，要有英文句号；关键的使用相关的注意事项可以提上来写到方法注释上。

2021-01-15 06:17 UTC, eyasliu commented on net/ghttp/ghttp_client_middleware.go
> +	return c.callRequest(req)
这里不能在 Next 循环自动调用，实际上 MiddlewareNext 的每次调用都是开发者手动调用的，并不是循环自动调用。

在使用的时候，需要调用 MiddlewareNext 以获取更里层的处理结果，不然它就拿不到 `(*ClientResponse, error)`，也就没东西 return，这就限制了开发者写中间件的时候，它一定会调用 MiddlewareNext，如果它不调用 MiddlewareNext ，就会终止调用更里层的中间件

2021-01-15 06:54 UTC, eyasliu commented
每个中间件都需要显式的去调用 `MiddlewareNext(r)` 才会调用下一层中间，也才能获得下层中间件的处理结果。如果不调用 `MiddlewareNext(r)`，则不会继续调用，也拿不到下一层的处理结果。

这点和 ghttp 服务器端有些区别，服务端中 `*ghttp.Request` 充当了请求上下文的角色，这一个对象可以达到获取和设置请求与响应，支持隐式调用 `Middleware.Next()` 没有问题，但是http 客户端没有这个上下文对象，只能通过调用 Next 获取响应

另外，这个 CI 任务为啥失败了我还没看出来

2021-01-16 13:47 UTC, gqcn commented
@eyasliu 
1. 调用Next的时候中间件的链路就往下执行了，挨个调用中间件方法，只有遇到错误时才停止。所以中间件调用那个地方，需要采用循环的形式，并在循环的逻辑中判断是否有错误。
2. 你的abort变量没有什么用了，已经有err判断退出的机制了，就不需要这个变量控制了。

2021-01-17 11:10 UTC, eyasliu commented
请求合并的分支选错了，重新提交了一个 #1130

2021-01-17 11:10 UTC, closed without merging