fix: gdb miss timezone on timestamptz type
gogf/gf pull request #1257
Opened 2021-05-21 05:40 UTC by qinyuguang

#1256 

解决第一个问题，timestamptz类型结果，转为本地时区

2021-05-24 05:28 UTC, gqcn requested changes

2021-05-24 05:28 UTC, gqcn commented on database/gdb/gdb_core_structure.go
> +			return gtime.NewFromTime(t).Local()
@qinyuguang 这里从数据库读取到的数据在`driver`底层被转换为了`time.Time`类型，那么就会按照`driver`的数据类型保存，不能强行执行`Local`转换，因为`Local`转换已经交给`driver`来维护了。如果你不想要`driver`来管理时间转换以及时区维护，请查看`pgsql`的配置中有无参数可以配置。在`mysql`中是有一个`parseTime`的参数可以控制的。

2021-05-24 06:08 UTC, qinyuguang commented on database/gdb/gdb_core_structure.go
> +			return gtime.NewFromTime(t).Local()
@gqcn  pg的driver里正确的转成了带时区的*time.Time，也就是gf的这行代码上的t，但是后续的转换过程中，丢了时区。

FindAll之后拿到的数据，已经是go程序默认时区的时间了

2021-05-24 06:09 UTC, qinyuguang commented on database/gdb/gdb_core_structure.go
> +			return gtime.NewFromTime(t).Local()
可以看下这个代码，pg用ParseTimestamp方法解析的timestamptz类型数据

![image](https://user-images.githubusercontent.com/6872629/119304213-827a3f80-bc99-11eb-97be-97f038725a97.png)

![image](https://user-images.githubusercontent.com/6872629/119304236-8d34d480-bc99-11eb-9e28-d9e036d1eff6.png)

2021-05-30 08:37 UTC, qinyuguang commented
@gqcn 改了下提交，单独加了一个timestamptz的case，这样如何？

2021-06-01 07:48 UTC, qinyuguang commented
导致这个问题的原因，是gconv把gvar转为gtime.Time时，丢失了时区

```go
package main

import (
	"github.com/gogf/gf/container/gvar"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gtime"
	"github.com/gogf/gf/util/gconv"
)

func main() {
	timestamp1 := gtime.NewFromStr("2021-05-21 05:04:51.206547+00")
	g.Log().Debug("timestamp1:", timestamp1)
	g.Log().Debug("timestamp1:", timestamp1.Local())

	timestamp2 := gconv.GTime(gvar.New(timestamp1))
	g.Log().Debug("timestamp2:", timestamp2)
	g.Log().Debug("timestamp2:", timestamp2.Local())
}
```

输出：
```
2021-06-01 15:45:46.799 [DEBU] timestamp1: 2021-05-21 05:04:51
2021-06-01 15:45:46.799 [DEBU] timestamp1: 2021-05-21 13:04:51
2021-06-01 15:45:46.799 [DEBU] timestamp2: 2021-05-21 05:04:51
2021-06-01 15:45:46.799 [DEBU] timestamp2: 2021-05-21 05:04:51
```

2021-06-01 11:49 UTC, gqcn commented
@qinyuguang 你好，我已经修复`gvar`的时间时区丢失问题，并且`timestampz`类型转换之前已经添加了支持，在`master`分支上请试试。没问题的话这个issue可以关闭了。

2021-06-02 03:25 UTC, qinyuguang commented
没问题了，时区可以保留👍

2021-06-02 03:25 UTC, closed without merging