add log level prefix color
gogf/gf pull request #1312
Opened 2021-06-27 16:07 UTC by wangle201210

2021-06-28 05:10 UTC, gqcn requested changes

2021-06-28 05:10 UTC, gqcn commented on os/glog/glog_logger_chaining.go
> +func (l *Logger) Color(color logColor) *Logger {
1. 方法注释。
2. 类型使用`int`。

2021-06-28 05:10 UTC, gqcn commented on os/glog/glog_logger_config.go
> +	FileColor            bool           `json:"fileColor"`            // Logging level prefix with color or not (false in default).
建议使用类似`FileColorEnabled`见名知意、知类型的属性名称。

2021-06-28 05:10 UTC, gqcn commented on os/glog/glog_logger_config.go
> +	color                logColor       `json:"-"`
一个简单的`color`不太好理解，建议使用`currentColor`或者`customColor`名称方便维护。

2021-06-28 05:10 UTC, gqcn commented on os/glog/glog_logger_config.go
> +func (l *Logger) SetColor(color logColor) {
这个方法要删掉，不能全局设置固定颜色。

2021-06-28 05:10 UTC, gqcn commented on os/glog/glog_logger_handler.go
> +func (i *HandlerInput) Buffer(withColor ...bool) *bytes.Buffer {
固定颜色控制规则，不需要额外参数控制，见上面的`review`说明。

2021-06-28 05:12 UTC, gqcn requested changes

2021-06-28 05:12 UTC, gqcn commented on os/glog/glog_logger_handler.go
> +	return fmt.Sprintf("\x1b[0;%dm%s\x1b[0m", color, s)
这样硬编码似乎不支持`windows`平台，建议使用第三方颜色包：https://github.com/fatih/color

2021-06-29 06:41 UTC, wangle201210 commented on os/glog/glog_logger_handler.go
> +func (i *HandlerInput) Buffer(withColor ...bool) *bytes.Buffer {
这里是为了同时兼容文件和控制台输出，所以此处需要有控制选项

2021-06-29 06:41 UTC, wangle201210 commented on os/glog/glog_logger.go
> +	mustWithColor     = true
这里是为了同时兼容文件和控制台输出，所以此处需要有控制选项

2021-07-15 01:16 UTC, merged