garray代码规范化
gogf/gf pull request #1361
Opened 2021-07-28 14:19 UTC by jroam

2021-08-01 01:04 UTC, gqcn requested changes

2021-08-01 01:04 UTC, gqcn commented on container/garray/garray_normal_any.go
> +// NewArray See New.
请给定完整的描述。

2021-08-01 01:04 UTC, gqcn commented on container/garray/garray_normal_any.go
> +// Append See PushRight.
请给定完整的描述。

2021-08-01 01:04 UTC, gqcn commented on container/garray/garray_normal_int.go
> +			return a.array[i] > a.array[j]
`a.array[i] >= a.array[j]`

2021-08-01 01:04 UTC, gqcn commented on container/garray/garray_normal_str.go
> +// Append See PushRight.
请给定完整的描述。

2021-08-01 01:54 UTC, jroam commented on container/garray/garray_normal_any.go
> +// NewArray See New.
在goland新的规范中，要把函数名写在注释之前，下图是没有写上函数名的提示：   
![image](https://user-images.githubusercontent.com/5014017/127756641-bb873142-02e9-4c04-bec4-b870fbf52d41.png)

2021-08-01 01:56 UTC, jroam commented on container/garray/garray_normal_any.go
> +// Append See PushRight.
同第一处说明

2021-08-01 01:57 UTC, jroam commented on container/garray/garray_normal_int.go
> +			return a.array[i] > a.array[j]
是的,应该是>=

2021-08-01 01:57 UTC, jroam commented on container/garray/garray_normal_str.go
> +// Append See PushRight.
同第一处描述

2021-08-02 12:03 UTC, gqcn requested changes

2021-08-02 12:03 UTC, gqcn commented on container/garray/garray_normal_any.go
> +// NewArray See New.
我的意思是`NewArray See New.`这句注释不通顺，需要给定完整的方法说明，或者友好地提示开发者去哪里查看使用说明。

2021-08-03 15:20 UTC, jroam commented
在gf中，很多的注释都是这样写的，所以应该保持一样的风格：   
![image](https://user-images.githubusercontent.com/5014017/128041466-a10b0dc2-6801-4770-8915-deaf608c97a8.png)

2021-08-04 05:17 UTC, gqcn requested changes

2021-08-04 05:17 UTC, gqcn commented on container/garray/garray_normal_any.go
> +// NewArray See New.
@jroam 比如注释改为`NewArray is alias of New, please see New.` 都比`NewArray See New`要好，我是这个意思。

2021-08-05 05:09 UTC, merged