Feature regex example
gogf/gf pull request #1450
Opened 2021-11-02 12:08 UTC by DGuang21

2021-11-03 14:04 UTC, gqcn requested changes

2021-11-03 14:04 UTC, gqcn commented on text/gregex/gregex_z_example_test.go
> +	patternStr := `[1-9]\d*`
`\d+`即可。

2021-11-03 14:04 UTC, gqcn commented on text/gregex/gregex_z_example_test.go
> +	g.Dump(gregex.IsMatch(patternStr, []byte("hello 94 easy gf!")))
作为示例代码，字符串的含义能不能更通俗易懂一些呢？

2021-11-04 13:22 UTC, DGuang21 commented on text/gregex/gregex_z_example_test.go
> +	g.Dump(err)
此处举的例子为，我需要替换 []byte 中的某一个内容，但正则文本匹配出来会有别的结果，所以需要在闭包中处理判断，只替换真正需要被替换的内容。ReplaceStringFunc亦同理。一点拙见，还望指点 @gqcn

2021-11-06 03:35 UTC, merged