232234
gogf/gf pull request #1452
Opened 2021-11-03 02:25 UTC by 564104865

cache example

2021-11-03 07:09 UTC, 564104865 reviewed
comment on exported function NewRedis should be of the form "NewRedis

2021-11-04 12:27 UTC, gqcn requested changes

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	//Create a cache object,
注释`//`符号后加上一个空格，保持注释风格统一。以下同。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_adapter_redis.go
> +
真不容易啊哥，你实现了一个`Cache`的`RedisAdapter`。这个比较难，我没想到你会做这个，这已经算是一个feature了。要不你先使用内存缓存那个对象来作为`SetAdapter`那个方法的`Example`吧，`Redis`这个`Adapter`后面再搞，比较花时间。这个`RedisAdapter`其实最好实现到gredis包中进行维护，你可以后面抽个时间单独提这个`feature`的`pr`，分开搞，这次只搞`Example`。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	time.Sleep(time.Second)
最好多`Sleep`一点时间，比如多`200ms`，防止系统负载比较高时底层定时器的时间不准。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	// Output:
加一个空行将代码与输出注释分隔开来。以下同。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	// may Output:
`may -> May`

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	//Data returns a copy of all key-value pairs in the cache as map type. Note that this function may lead lots of memory usage, you can implement this function if necessary.
你这注释放这不太合适吧。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	data, _ := c.GetExpire(ctx, "k")
变量名称最好能与内容对应，这里建议改为`expire`。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	//GetOrSetFunc retrieves and returns the value of `key`, or sets `key` with result of function `f` and returns its result if `key` does not exist in the cache.
注释太长请适当换行。

2021-11-04 12:27 UTC, gqcn commented on os/gcache/gcache_z_example_cache_test.go
> +	//but it does nothing if `value` is a function and the function result is nil.
无意义的注释。

2021-11-04 12:36 UTC, gqcn commented
@564104865 少了`gcache`包方法的`Example`。

2021-11-05 15:24 UTC, merged