gstrset Example Finish
gogf/gf pull request #1453
Opened 2021-11-03 02:44 UTC by Evil-king

gstrset Example Finish

2021-11-03 05:00 UTC, gqcn requested changes

2021-11-03 05:00 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +	s := gset.NewStrSetFrom([]string{"a"}, true)
这个示例不太好，可以使用上面`ExampleStrSet_UnmarshalJSON`相同的示例。

2021-11-03 14:53 UTC, Evil-king commented on container/gset/gset_z_example_str_test.go
> +//The parameter <safe> is used to specify whether using set in concurrent-safety,
已经修改完成了

2021-11-04 15:52 UTC, gqcn requested changes

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +func ExampleStrSet_NewStrSet() {
`StrSet`没有`NewStrSet`方法，这个方法是包方法，因此这里应当改为`ExampleNewStrSet`。

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +func ExampleStrSet_NewStrSetFrom() {
`StrSet`没有`NewStrSetFrom`方法，这个方法是包方法，因此这里应当改为`ExampleNewStrSetFrom`。

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +	// May Output:
增加空行以便将代码与输出内容区分。

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +	// May Output
增加空行以便将代码与输出内容区分。

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +	time.Sleep(time.Duration(2) * time.Second)
感觉这样示例的意义不大，如果并发的示例不好编写就改为之前简单的操作示例吧。

2021-11-04 15:52 UTC, gqcn commented on container/gset/gset_z_example_str_test.go
> +	s1.Add([]string{"a", "b", "c", "d"}...)
使用数字作为`Sum`的参数才有意义。

2021-11-04 16:21 UTC, merged