Update garray_z_example_str_test.go
gogf/gf pull request #1454
Opened 2021-11-03 09:16 UTC by visualsun

新增加StrArray的Example

2021-11-03 13:44 UTC, gqcn requested changes

2021-11-03 13:44 UTC, gqcn commented on container/garray/garray_z_example_str_test.go
> +func ExampleStrArray_SortFunc() {
我看了除了SortFunc那个示例不是特别好，其他都写得很棒，我给你改个例子你看看：
```go
s := garray.NewStrArrayFrom(g.SliceStr{"b", "c", "a"})
fmt.Println(s)
s.SortFunc(func(v1, v2 string) bool {
	return gstr.Compare(v1, v2) > 0
})
fmt.Println(s)
s.SortFunc(func(v1, v2 string) bool {
	return gstr.Compare(v1, v2) < 0
})
fmt.Println(s)

// Output:
// ["b","c","a"]
// ["c","b","a"]
// ["a","b","c"]
```

2021-11-03 14:31 UTC, visualsun commented on container/garray/garray_z_example_str_test.go
> +func ExampleStrArray_SortFunc() {
非常好，我把这个例子调整进去

2021-11-04 11:40 UTC, gqcn requested changes

2021-11-04 11:40 UTC, gqcn commented on container/garray/garray_z_example_str_test.go
> +	s.SetArray(g.SliceStr{"We", "are", "3", "GF", "5", "fans", "!", "10"})
`Sum`方法只有对数字的元素项有效，这里最好不要有英文的元素项为例。

2021-11-04 11:40 UTC, gqcn commented on container/garray/garray_z_example_str_test.go
> +		fmt.Println(array[len(array)-1])
这里可以使用`for`循环打印一下`array`的元素项可能更好一些。

2021-11-04 12:09 UTC, visualsun commented on container/garray/garray_z_example_str_test.go
> +	s.SetArray(g.SliceStr{"We", "are", "3", "GF", "5", "fans", "!", "10"})
ok!

2021-11-04 12:09 UTC, visualsun commented on container/garray/garray_z_example_str_test.go
> +		fmt.Println(array[len(array)-1])
OK!

2021-11-04 12:29 UTC, merged