Create garray_z_example_sorted_str_test.go
gogf/gf pull request #1459
Opened 2021-11-04 14:28 UTC by visualsun

新增sorted str的example

2021-11-04 15:46 UTC, gqcn requested changes

2021-11-04 15:46 UTC, gqcn commented on container/garray/garray_z_example_sorted_str_test.go
> +func ExampleSortedStrArray_NewSortedStrArray() {
`SortedStrArray`类型没有`NewSortedStrArray`方法，这里应当为`ExampleNewSortedStrArray`

2021-11-04 15:46 UTC, gqcn commented on container/garray/garray_z_example_sorted_str_test.go
> +func ExampleSortedStrArray_NewSortedStrArraySize() {
`SortedStrArray`类型没有`NewSortedStrArraySize`方法，这里应当为`ExampleNewSortedStrArraySize`

2021-11-04 15:46 UTC, gqcn commented on container/garray/garray_z_example_sorted_str_test.go
> +	fmt.Println(s.Unique())
可以在调用`Unique`方法之前讲原有的数组内容打印出来，以便做对比。

2021-11-04 15:46 UTC, gqcn commented on container/garray/garray_z_example_sorted_str_test.go
> +}
等等，这个例子我没看出来和`SortedStrArray`有什么关系呢？

2021-11-04 15:46 UTC, gqcn commented on container/garray/garray_z_example_sorted_str_test.go
> +	fmt.Println(s.FilterEmpty())
可以在调用`FilterEmpty`方法之前将原有数组数据打印出来，以便做对比。

2021-11-05 02:30 UTC, visualsun commented on container/garray/garray_z_example_sorted_str_test.go
> +	fmt.Println(s.FilterEmpty())
ok!

2021-11-05 02:32 UTC, visualsun commented on container/garray/garray_z_example_sorted_str_test.go
> +func ExampleSortedStrArray_NewSortedStrArray() {
ok

2021-11-05 02:32 UTC, visualsun commented on container/garray/garray_z_example_sorted_str_test.go
> +func ExampleSortedStrArray_NewSortedStrArraySize() {
ok

2021-11-05 02:33 UTC, visualsun commented on container/garray/garray_z_example_sorted_str_test.go
> +	fmt.Println(s.Unique())
ok

2021-11-05 06:43 UTC, visualsun commented on container/garray/garray_z_example_sorted_str_test.go
> +}
ok

2021-11-05 15:27 UTC, merged