添加gstr包的实例
gogf/gf pull request #1462
Opened 2021-11-04 17:21 UTC by giamyl

2021-11-04 17:22 UTC, giamyl commented
添加gstr包的88个实例

2021-11-05 03:37 UTC, giamyl commented
Package gstr's All Example

2021-11-05 03:37 UTC, giamyl reviewed
Package gstr's All Example

2021-11-05 03:38 UTC, giamyl reviewed
Package gstr's All Example

2021-11-06 04:27 UTC, gqcn requested changes

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// 目前不支持嵌套切片。
改为英文或者去掉中文提示

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// 16
示例中带有中文更能提现`*Rune`方法的功能。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例中带有中文更能提现`*Rune`方法的功能。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例中带有中文更能提现`*Rune`方法的功能。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例中带有中文更能提现`*Rune`方法的功能。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	str = `.\+?[^]()`
字符串中需要包含其他非替换字符串，尽量使得示例各个贴近业务一些。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// golang_is Very Nice.to-use
该示例并没有体现出`ReplaceI`忽略大小写替换的功能。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例可以替换为，示例代码定义的变量少、言简意赅，其他示例可以参考这个：
```go
func ExampleReplaceIByArray() {
	fmt.Println(gstr.ReplaceIByArray(
		`golang is very nice`,
		[]string{
			"Golang",
			"GoFrame",
			"Nice",
			"GOOD",
		},
	))

	// Output:
	// GoFrame is very GOOD
}
```

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	str = `Goframe-Nice`
直接给`123456`转换为`654321`即可。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	delimiter = `ame_N`
分隔符号可以使用`_`可能更合适一些。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// _is Very Nice.to-use
示例不太好。打印出的内容不明白什么意义。不如直接用`abcdef`作为示例吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例不太好。打印出的内容不明白什么意义。不如直接用`abcdef`作为示例。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
为`*Rune`方法增加中文内容吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// goframe_is Very Nice.
用`abcdef`作为示例内容吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// goframe "is" Very Nice to use
示例中没有`Slash` `\\`怎么`Strip`呢？

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// me Nic
示例不太好。打印出的内容不明白什么意义。不如直接用`abcdef`作为示例吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// me N
示例不太好。打印出的内容不明白什么意义。不如直接用`abcdef`作为示例吧。
少了中文。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	s = `GoFRAME_IS VERY NICE.TO-USE`
`GoFRAME IS VERY NICE TO USE`

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	s = `goframe_is Very Nice.to-use`
`GoFRAME IS VERY NICE TO USE`

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// goframe_is Very Nice.
使用` abcdef.`作为例子吧，`mask`使用` .`

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// fram
不如直接用`abcdef`作为示例吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// Nice to use
不如直接用`abcdef`作为示例吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// frame is Very Nice.to-use
感觉这个Example差点示例的味道，更像是单元测试。要不就直接用`abcdef`，然后`cut`使用`abc`吧。

2021-11-06 04:27 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// goframe_is Very Nic
要不示例字符串就直接用`abcdef.`，然后`cut`使用`def`吧。

2021-11-06 04:30 UTC, gqcn commented
@giamyl 这里有几个通用的问题：
1. 不是所有的示例都需要单独定义变量来承接字符串内容，这样会使得示例的行数变多，内容过多增加心智负担，示例应当是简单言简意赅的。建议可以直接将参数直接传递给字符串方法，不用额外定义变量。
2. 部分Example差点示例的味道，更像是单元测试。建议部分方法如果不方便列举合适的例子可以直接使用`123456`或者`abcdef`这样的参数作为示例可能更好一些。
3. 所有的`*Rune`方法都是支持`UTF8`字符串操作的方法，因此示例中字符串应当有中文。

2021-11-13 14:18 UTC, gqcn requested changes

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	fmt.Println(rsStr)
结果看不出来方法特殊的地方，你可以使用以下方法：
```go
fmt.Printf(`%#v`, rsStr)
```

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	fmt.Println(rsStr)
结果看不出来方法特殊的地方，你可以使用以下方法：
```go
fmt.Printf(`%#v`, rsStr)
```

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// 103
可在上面的注释说明一下为什么这里打印`103`：因为是字母`g`的`ASC2`码。

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// e giNomescraf._i
这个示例不是很清晰，要不改成`abcde`或者`123456`吧。

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// [GoFrame Nice]
结果看不出来方法特殊的地方，你可以使用以下方法：
```go
fmt.Printf(`%#v`, rsStr)
```

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// [goframe is Very Nice to use]
结果看不出来方法特殊的地方，你可以使用以下方法：
```go
fmt.Printf(`%#v`, rsStr)
```

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
示例还是不是特别好。其实这个函数的常用于字符串过长时只展示部分内容，后面的内容通过`suffix`替代。可以参考以下示例：
```go
var (
	str    = `123456789`
	length = 3
	suffix = `...`
	rsStr  = gstr.StrLimit(str, length, suffix)
)
fmt.Println(rsStr)

// Output:
// 123...
```

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
@giamyl 这里没改到。

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +	// Output:
这里最好增加一个文件路径的示例，通过`StrTill`方法获取到文件后缀名，这种用途很广泛。

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
这里的示例不是很好，最好改为文件路径的示例，通过`StrTillEx`方法获取到文件后缀名，这种用途很广泛。

2021-11-13 14:18 UTC, gqcn commented on text/gstr/gstr_z_all_example_test.go
> +}
这个是`*Rune`方法，因此这里缺少了中文示例。

2021-11-18 14:11 UTC, merged