test: add gflie example
gogf/gf pull request #1463
Opened 2021-11-05 06:39 UTC by hailaz

2021-11-09 16:44 UTC, gqcn requested changes

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	intlog.SetEnabled(false)
在示例代码中，请去掉`intlog`的使用。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	tempFile := gfile.Join(tempDir, fileName)
请使用`var`包裹这几行代码，以保持良好的排版。
以下同。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	gfile.PutContents(tempFile, "test contents")
作为示例代码能否把文件名和内容取得更友好一些？比如文件名使用`goframe_example.txt`，示例内容用`goframe example content`?
请务必修改一下所有示例代码的示例内容，不要使用单测的方式来写示例代码。原则是站在使用者的角度，如何清晰易懂友好地学习示例代码，快速地掌握对应方法的使用。
以下同。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	fmt.Println(string(content))
可以先多打印一行把`[]byte`类型的内容打印出来，这样才能示例改方法的作用。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	gfile.Create(tempFile)
去掉`Mkdir`和`Create`方法的使用，你后面使用的方法会自动创建目录以及文件。
以下同。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutContents(tempFile, "test contents\ntest contents")
请将示例内容换成不同的内容，哥你这明显是在写单测啊。注意这个是示例代码，不是单测。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutContents(tempFile, "test contents\ntest contents")
请将示例内容换成不同的内容，哥你这明显是在写单测啊。注意这个是示例代码，不是单测。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_copy_test.go
> +	}
示例代码没必要执行`Remove`。

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_copy_test.go
> +	tempFile := gfile.Join(tempDir, fileName)
`srcFileName/srcDirPath/srcFilePath`

2021-11-09 16:44 UTC, gqcn commented on os/gfile/gfile_z_example_copy_test.go
> +	}
这段代码的示例作用没看懂。。。示例能改得通俗易懂一些吗？

2021-11-09 16:44 UTC, gqcn commented
@hailaz 我看了一下，整体都偏单元测试，请将代码修改为示例代码。

2021-11-11 06:11 UTC, hailaz commented on os/gfile/gfile_z_example_cache_test.go
> +	intlog.SetEnabled(false)
![image](https://user-images.githubusercontent.com/29968474/141247054-9162c9ea-eeda-4fb9-a9fe-e8898231d01b.png)
不关掉有输出

2021-11-12 07:27 UTC, hailaz commented on os/gfile/gfile_z_example_cache_test.go
> +	intlog.SetEnabled(false)
@gqcn

2021-11-13 14:29 UTC, gqcn requested changes

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDir(tempDir, "gflie_example.txt,sub_dir", true)
`pattern`参数用得不太对，建议示例以下使用`*.txt`或者`*`的场景。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDirFile(tempDir, "gflie_example.txt,sub_dir", true)
`pattern`参数用得不太对，建议示例以下使用`*.txt`的场景。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDirFunc(tempDir, "gflie_example.txt,sub_dir", true, func(path string) string {
`pattern`参数用得不太对，建议示例以下使用`*.txt`或者`*`的场景。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDirFileFunc(tempDir, "gflie_example.txt,gflie_example_ignores.txt,sub_dir", true, func(path string) string {
`pattern`参数用得不太对，建议示例以下使用`*.txt`或者`*`的场景。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_size_test.go
> +	if size == 0 { // Why does every directory have a size 4096 bytes (4K)?
这个`4KB`大小是Linux系统下目录节点的固定大小。你这个示例不够标志性，一般没人会去`Size`目录的大小，建议`Size`以下具体文件的大小，比如你写入了`10`个字节，那么`Size`出来就是`10`个字节。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_size_test.go
> +	if sizeStr == "0.00B" { // Why does every directory have a size 4096 bytes (4K)?
这个`4KB`大小是Linux系统下目录节点的固定大小。你这个示例不够标志性，一般没人会去`SizeFormat`目录的大小，建议`SizeFormat`以下具体文件的大小，比如你写入了`10`个字节，那么`SizeFormat`出来就是`10B`。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_size_test.go
> +	if sizeStr == "0.00B" { // Why does every directory have a size 4096 bytes (4K)?
同上。

2021-11-13 14:29 UTC, gqcn commented on os/gfile/gfile_z_example_size_test.go
> +	sizeStr1 := gfile.FormatSize(999999999999999999)
😅 能不能给几个正常点的大小，比如`B/KB/GB`都行的。

2021-11-13 14:30 UTC, gqcn commented
@hailaz 亮仔，你的PR我评论了哈，比之前好多了，如果CI失败的话，你把`Output`改为`May Output`吧。

2021-11-17 11:33 UTC, gqcn requested changes

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	// read contents
It reads the file content with cache duration of on minute,
which means it reads from cache after then without any IO operations within on minute.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_cache_test.go
> +	time.Sleep(time.Second * 1)
There's some delay for cache clearing after file content change.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	// read contents
It reads and returns the file content as string.
It returns empty string if it fails reading, for example,  with permission or IO error.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	fmt.Println(gfile.GetBytes(tempFile))
It reads and returns the file content as []byte.
It returns nil if it fails reading, for example, with permission or IO error.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutContents(tempFile, "goframe example content")
It creates and puts content string into specifies file path.
It automatically creates directory recursively if it does not exist.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutBytes(tempFile, []byte("goframe example content"))
It creates and puts content using []byte into specifies file path.
It automatically creates directory recursively if it does not exist.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutContentsAppend(tempFile, " append content")
It just appends specified content to the file content of file path.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_replace_test.go
> +	gfile.ReplaceFile("content", "replace word", tempFile)
It replaces content directly by file path.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_replace_test.go
> +	gfile.ReplaceFileFunc(func(path, content string) string {
It replaces content directly by file path and callback function.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_replace_test.go
> +	gfile.ReplaceDir("content", "replace word", tempDir, "gflie_example.txt", true)
It replaces content of all files under specified directory recursively.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_replace_test.go
> +	gfile.ReplaceDirFunc(func(path, content string) string {
It replaces content of all files under specified directory with custom callback function recursively.

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDirFile(tempDir, "*", true)
`list, _ := gfile.ScanDirFile(tempDir, "*.txt", true)`

2021-11-17 11:33 UTC, gqcn commented on os/gfile/gfile_z_example_scan_test.go
> +	list, _ := gfile.ScanDirFileFunc(tempDir, "*", true, func(path string) string {
`*.txt`

2021-11-18 14:51 UTC, gqcn requested changes

2021-11-18 14:51 UTC, gqcn commented on os/gfile/gfile_z_example_contents_test.go
> +	gfile.PutContentsAppend(tempFile, " append content")
@hailaz

2021-11-18 14:51 UTC, gqcn commented on os/gfile/gfile_z_example_replace_test.go
> +	gfile.ReplaceFile("content", "replace word", tempFile)
@hailaz

2021-11-21 14:28 UTC, gqcn approved these changes

2021-11-21 14:29 UTC, gqcn commented
@hailaz Approved, let me merge this later.

2021-11-21 14:47 UTC, merged