add gvar example
gogf/gf pull request #1486
Opened 2021-11-17 09:08 UTC by Hamster601

add gvar example

2021-11-17 11:12 UTC, gqcn requested changes

2021-11-17 11:12 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +func ExampleVar_New() {
应当是`ExampleNew`，具体请查看Example编写介绍：https://goframe.org/pages/viewpage.action?pageId=3673026

2021-11-17 11:12 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +func ExampleVar_Create() {
`ExampleCreate `

2021-11-17 11:12 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +var product2 = Product{
作为Example代码，不应当把使用到的结构体放在Example方法之外，具体请查看方法的代码提示。

2021-11-17 11:12 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	g.Dump(a1)
请使用简单的基本类型作为示例即可，示例尽可能简单，表达核心功能即可。
以下同。

2021-11-17 11:12 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	var a1 = gvar.New(product1.Price, false)
`gvar.New`在示例代码中请不用加第二个参数使用，尽可能简单。并且你的这些示例也没有演示第二个参数的用途，去掉即可。

2021-11-18 14:49 UTC, gqcn requested changes

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +
每个方法去掉无意义的第一个空换行。
以下同。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	// Output:
这个方法搞得有点复杂，不知所意，可以改成上面`New`方法那样简单即可。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	g.Dump(p2)
简单示例即可，不要使用结构体。
在实例中演示清楚Clone之后是一个新的泛型对象即可（修改新的泛型对象不会影响旧的）。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	var tag1 = gvar.New(100.00, false)
不要使用`New`方法第二个参数，因为对你这个示例没有意义。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = tag1.Set(200.00).(float64)
`g.Dump(v.Set(200))`

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	g.Dump(a1.Val().(float64) * 100)
关键的地方：
删掉这行代码，因为在泛型对象使用时我们并不推荐再重复使用断言转换。
泛型对象本身就支持各种类型转换，你使用的时候并不知道别人设置进去的是什么类型。你这样使用会对初学者造成困惑。
以下同。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	var a1 = gvar.New(gtime)
`gvar.New("2021-11-11 00:00:00")`

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	var product1 = Product{
请将结构体定义到函数里面。理由上面已说过。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	var json, _ = a1.MarshalJSON()
请使用`json.Marshal`

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.UnmarshalJSON(json)
请使用`json.Unmarshal`

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	json := []byte(`{
请将结构体定义到函数里面。理由上面已说过。

2021-11-18 14:49 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.UnmarshalValue(product2)
请使用`gconv.Scan`转换。

2021-11-22 15:20 UTC, gqcn requested changes

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.UnmarshalJSON(json)
@Hamster601 这里请参考我的评论。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.UnmarshalValue(tmp)
使用`gconv.Scan`，示例：
```go
type Student struct {
	Id     *g.Var
	Name   *g.Var
	Scores *g.Var
}
var (
	s Student
	m = g.Map{
		"Id":     1,
		"Name":   "john",
		"Scores": []int{100, 99, 98},
	}
)
if err := gconv.Scan(m, &s); err != nil {
	panic(err)
}
g.DumpWithType(s)
```

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +
去掉无意义的换行。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +
去掉无意义的换行。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	//}
注释后1个空格。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.Struct(&t)
错误不能忽略，例如加上`if err := xxx; err != nil {panic(err)}`。
以下同。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(a2["price"])
1. 多个变量申明请使用`var(xx)`包含。
2. 同时打印`id`键值。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(a2["price"] + "元")
1. 多个变量申明请使用`var(xx)`包含。
2. 同时打印`id`键值。
3. 考虑国际化，示例中请使用英文。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(a2["price"].Float64() * 100)
1. 多个变量申明请使用`var(xx)`包含。
2. 同时打印`id`键值。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(a2["product"])
多个变量申明请使用`var(xx)`包含。
以下同。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(a2[0], reflect.TypeOf(a2[0]))
请使用`fmt.Printf("%#v", a2)`可打印类型。

2021-11-22 15:20 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(m4, reflect.TypeOf(m4))
请使用`fmt.Printf("%#v", xxx)`可打印类型。

2021-11-23 04:02 UTC, Hamster601 commented on container/gvar/gvar_z_example_test.go
> +	_ = a1.UnmarshalJSON(json)
强哥，这里我有个疑问，这里不是gvar的example吗，如果用json的话，会不会体现不出这个例子的作用？这里我不是很明白您的意思，是要加一个json用做对比吗？ @gqcn

2021-11-24 15:00 UTC, gqcn requested changes

2021-11-24 15:00 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	params1 := map[string]interface{}{
@Hamster601

2021-11-24 15:00 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +	fmt.Println(b1["id"])
@Hamster601

2021-11-25 13:13 UTC, gqcn requested changes

2021-11-25 13:13 UTC, gqcn commented on container/gvar/gvar_z_example_test.go
> +package gvar_test
前面要加个空行...不然你会看到godoc上前面的一堆注释都是包说明。。

2021-11-26 12:38 UTC, merged