Added Order() method support for gdb.
gogf/gf pull request #1529
Opened 2021-12-22 13:06 UTC by zxr615

#1434 

本来是想在 [doQuoteString(s, charLeft, charRight string)](https://github.com/gogf/gf/blob/master/database/gdb/gdb_func.go#L304) 中做判断，但方法中的参数是 `string` 类型，而且 `doQuoteString()`  被引用的地方很多，如果改参数 `s` 成 `interface{}` 的话方法名也不太符合原意了，所以就直接在 `Order()` 方法里面修改了，多了个 `for` 循环，似乎不太优雅，大佬可以给给意见。

2021-12-22 14:22 UTC, gqcn requested changes

2021-12-22 14:22 UTC, gqcn commented on database/gdb/gdb_model_order_group.go
> -// Order("id", "desc")
这个注释不要删。

2021-12-22 14:53 UTC, zxr615 commented on database/gdb/gdb_model_order_group.go
> -// Order("id", "desc")
好的，测试没通过debug 的时候发现个问题，[这里的](https://github.com/gogf/gf/blob/master/database/gdb/gdb_model_order_group.go#L22) `if` 判断似乎是无效的，因为下面的 `model.orderBy` 又被重新赋值了，所以如果链式多次使用 `Order()` 也是无效的，我看文档确实没有提到多次链式使用 `Order()` 是设计如此吗？

![image](https://user-images.githubusercontent.com/30486360/147110563-56b013cf-ffc6-421f-82fc-4dc58fa77113.png)

2021-12-22 15:35 UTC, gqcn commented
@zxr615 你的CI失败了

2022-01-05 03:02 UTC, FlyingBlazer commented on database/gdb/gdb_model_order_group.go
> -// Order("id", "desc")
我也觉得25行应该改成 `+=`，但我PR #1520 的CI一直跑不完不知道为什么

2022-01-05 03:11 UTC, zxr615 commented on database/gdb/gdb_model_order_group.go
> -// Order("id", "desc")
> 我也觉得25行应该改成 `+=`，但我PR #1520 的CI一直跑不完不知道为什么

改成 `+=` 之后有些测试用例的结果和预期的是不一样的了，比如测试用例是：`Order("status desc").Order("id asc")`， 实际排序是只有`id asc`， 而改成 `+=` 之后就变成了`status desc id asc`， 所以 `asset()` 结果的时候就不对了，你可以本地跑一遍测试用例就知道什么问题了

2022-01-05 03:40 UTC, FlyingBlazer commented on database/gdb/gdb_model_order_group.go
> -// Order("id", "desc")
多谢，之前没看到github ci里的fail，还以为莫名其妙失败了

2022-01-06 14:04 UTC, gqcn commented
@zxr615 请继续修改撒，如果超过一个月没有活动会关闭哦

2022-01-07 15:27 UTC, zxr615 commented
> @zxr615 请继续修改撒，如果超过一个月没有活动会关闭哦

因为 `Order()` 支持 `Order("id", "desc")` 这样的多参数查询，所以有可能 `Order("id", "desc", gdb.Raw("field(id, 3,1,2)"))` 这样使用，如果要区分处理会比较复杂，所以使用一个循环检查如果有` gdb.Raw()` 的话则直接使用 `gdb.Raw()` 条件，舍去其他参数；从我个人角度来说，应该没什么问题，理由：因为用了 `gdb.Raw() `原始条件后应该是不会再拼接其他的参数，如果需要的话可以多次调用 `Order()` 来增加.

1.17 CI 失败了，不知道啥原因，[麻烦大佬帮忙看看](https://github.com/gogf/gf/runs/4739786389?check_suite_focus=true#step:8:3892)

2022-01-10 06:46 UTC, zxr615 commented
> > @zxr615 请继续修改撒，如果超过一个月没有活动会关闭哦
> 
> 因为 `Order()` 支持 `Order("id", "desc")` 这样的多参数查询，所以有可能 `Order("id", "desc", gdb.Raw("field(id, 3,1,2)"))` 这样使用，如果要区分处理会比较复杂，所以使用一个循环检查如果有` gdb.Raw()` 的话则直接使用 `gdb.Raw()` 条件，舍去其他参数；从我个人角度来说，应该没什么问题，理由：因为用了 `gdb.Raw() `原始条件后应该是不会再拼接其他的参数，如果需要的话可以多次调用 `Order()` 来增加.
> 
> 1.17 CI 失败了，不知道啥原因，[麻烦大佬帮忙看看](https://github.com/gogf/gf/runs/4739786389?check_suite_focus=true#step:8:3892)

@gqcn 这个CI提示端口的错误是什么原因呢？

2022-03-09 12:55 UTC, merged