ghttp: add cookie security configurations
gogf/gf pull request #1549
Opened 2022-01-05 07:11 UTC by FlyingBlazer

Add configurations for cookie security properties:

1. HttpOnly
2. Secure
3. SameSite

Pending Unit Test

Some questions:

1. Should I keep backward compatibility on `Cookie.SetCookie`'s `httpOnly` parameter?
2. How to handle multiple optional parameters to keep code clean and clear?

2022-01-06 12:27 UTC, gqcn requested changes

2022-01-06 12:27 UTC, gqcn commented on net/ghttp/ghttp_server_cookie.go
> +func (c *Cookie) SetCookie(key, value, domain, path string, maxAge time.Duration, extra ...map[string]interface{}) {
@FlyingBlazer 感谢参与贡献！我这里建议使用`struct`结构化定义`Cookie`的额外参数，而不是通过非结构化的`map`。因此建议您可以定义一个`CookieOption`的结构体，将需要额外定义的参数使用结构化管理起来。

2022-01-12 11:56 UTC, gqcn requested changes

2022-01-12 11:56 UTC, gqcn commented on net/ghttp/ghttp_server_cookie.go
> +	sameSite http.SameSite // cookie SameSite property
请公开属性。

2022-03-02 01:57 UTC, FlyingBlazer commented on net/ghttp/ghttp_server_cookie.go
> +	sameSite http.SameSite // cookie SameSite property
抱歉一直没抽出来时间，已经改了

2022-03-04 09:42 UTC, merged