Dev clickhouse driver - do not merge
gogf/gf pull request #1573
Opened 2022-01-16 08:54 UTC by DGuang21

2022-01-16 13:03 UTC, houseme commented on database/gdb/gdb_driver_clickhouse.go
> +	"strings"
代码格式化一下，按组import

2022-01-16 13:05 UTC, houseme commented on database/gdb/gdb_driver_clickhouse.go
> +	glog.Infof(context.Background(), "Open: %s %s", source, clickhouse.DefaultDatabase)
参考mysql驱动 ctx应该是 d.GetCtx()
具体参考链接：https://github.com/gogf/gf/blob/d4b502f14e0da2e0d8ceda140756cb95234a7967/database/gdb/gdb_driver_mysql.go#L59

2022-01-16 13:24 UTC, houseme reviewed
fmt

2022-01-16 13:24 UTC, houseme commented on database/gdb/gdb_z_clickhouse_test.go
> +	"github.com/gogf/gf/v2/util/grand"
请按组import 包

2022-01-21 09:18 UTC, gqcn requested changes

2022-01-21 09:18 UTC, gqcn commented on go.mod
> +	github.com/ClickHouse/clickhouse-go v1.5.1
不要直接引入`clickhouse`依赖。

2022-01-21 09:18 UTC, gqcn commented on .github/workflows/go.yml
> +      clickhouse-server:
为保持主库的轻量，`workflow`以及单测不放到主库，可以放到 `https://github.com/gogf/gdb-drivers`

2022-01-21 09:18 UTC, gqcn commented on database/gdb/gdb.go
> +	DoDeleteSQL(ctx context.Context, link Link, table string, condition interface{}, args ...interface{}) (result sql.Result, err error)              // See Core.DoDeleteSQL.
不建议增加`DoUpdateSQL/DoDeleteSQL`方法增加接口复杂度，可以通过原有的`DoUpdate/DoDelete`接口以及正则匹配替换来处理。再高级点，可以考虑引入第三方的SQL解析器再做替换（比如`pingcap`就有一个`SQL`语法解析包，可以参考下）。

2022-01-21 09:18 UTC, gqcn commented on database/gdb/gdb_driver_clickhouse.go
> +func (d *DriverClickhouse) DoCommit(ctx context.Context, in DoCommitInput) (out DoCommitOutput, err error) {
这个方法内部，只需要处理`clickhouse`特有的逻辑，如果可以复用基类的逻辑，可以使用`c.Core.DoCommit`，参考一下主库已有的`driver`实现呢？

2022-01-21 09:18 UTC, gqcn commented on database/gdb/gdb_driver_clickhouse.go
> +func (d *DriverClickhouse) DoInsert(ctx context.Context, link Link, table string, list List, option DoInsertOption) (result sql.Result, err error) {
同`DoCommit`说明。

2022-01-21 09:18 UTC, gqcn commented on database/gdb/gdb_z_clickhouse_test.go
> +import (
将单测挪到`https://github.com/gogf/gdb-drivers`

2022-01-22 09:30 UTC, closed without merging