add command `gf update`
gogf/gf pull request #1624
Opened 2022-02-23 02:12 UTC by wangle201210

#1614
- [x] mac
- [ ] win
- [ ] linux
example：
gf update
gf update -way clone
gf update -tag v2.0.0-rc2  (now release only have  v2.0.0-rc2)

2022-02-26 12:44 UTC, gqcn requested changes

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	Way    string `name:"way" short:"w" brief:"download way, You can choose wget、clone or code, default is wget binary file"`
用`Branch`吧，当给定`Tag`时使用二进制安装，使用`Branch`时用源码安装。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	workPath = path.Join(home, ".gf")
下载的临时存储目录请使用临时目录`gfile.Temp`，此外，在主流程中请`defer`删除不再使用的临时目录/内容。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	for _, data := range runCmd {
请使用`gproc.ShellRun`

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	filename := getGitFileName()
在执行之前先判断`wget`命令是否存在，使用`gproc.SearchBinary("wget")`

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	runCmd := []cmdInfo{
在执行之前先判断`git`命令是否存在，使用`gproc.SearchBinary("git")`

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	fileName := fmt.Sprintf("%s.tar.gz", c.release.TagName)
下载`zip`压缩文件，通过`gcompress`包解压即可，不依赖外部命令，因为这些命令可能不存在。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	release gitRelease
我看过你后面的实现，这里不建议通过属性来传递方法参数，而是将方法参数组装后通过参数传递到方法。
请去掉这两个属性定义。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	TagName         string `json:"tag_name"`
如果不需要使用`json`则不要定义`json`标签

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	TargetCommitish string `json:"target_commitish"`
`commitish`?

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	if err = json.Unmarshal(bodyContent, &releases); err != nil {
请使用`gjson.Unmarshal`以保证出错时的堆栈信息便于快速排错。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	if err = json.Unmarshal(bodyContent, &releases); err != nil {
请使用`gjson.Unmarshal`以保证出错时的堆栈信息便于快速排错。

2022-02-26 12:44 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_update.go
> +	resp, err := http.Get(releaseUrl)
请使用`g.Client().GetVar`

2022-03-10 11:19 UTC, gqcn commented
@wangle201210

2022-03-11 09:02 UTC, wangle201210 commented
> @wangle201210

emmm，前段时间忙了点其他的去了，我尽快加上～

2022-03-14 07:20 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	TargetCommitish string `json:"target_commitish"`
`target_commitish` 是 [git api](https://api.github.com/repos/gogf/gf/releases)接口返回的参数名字

2022-03-14 07:44 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	workPath = path.Join(home, ".gf")
`gfile.Temp(***)`返回的是`/tmp/***`目录，该目录可能存在文件权限问题，个人觉得应该优先考虑“当前用户的目录” 即` os.UserHomeDir`

2022-03-14 07:44 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	for _, data := range runCmd {
`gproc.ShellRun` 目前不支持指定运行目录功能，所以目前只能使用原生的cmd功能

2022-03-14 09:33 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	TagName         string `json:"tag_name"`
试过，即使用`g.Client().GetVar().Scan(**)` 不加`json`标签，也不能正常的绑定到对象上面去

2022-03-15 10:55 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	fileName := fmt.Sprintf("%s.tar.gz", c.release.TagName)
done

2022-03-15 10:55 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	runCmd := []cmdInfo{
done

2022-03-15 10:55 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	filename := getGitFileName()
done

2022-03-15 10:55 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	codeUrl    = "https://github.com/gogf/gf/archive/refs/tags/%s"
done

2022-03-15 10:56 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	Way    string `name:"way" short:"w" brief:"download way, You can choose wget、clone or code, default is wget binary file"`
tag 包含了branch的（一个branch必然属于某个tag，但是反之就不对了），所以下载的时候用tag更稳定
使用源码安装或者二进制安装，通过-w（-way）来控制，这样更清晰点

2022-03-15 10:56 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	if err = json.Unmarshal(bodyContent, &releases); err != nil {
done

2022-03-15 10:56 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	if err = json.Unmarshal(bodyContent, &releases); err != nil {
done

2022-03-15 10:57 UTC, wangle201210 commented on cmd/gf/internal/cmd/cmd_update.go
> +	resp, err := http.Get(releaseUrl)
done

2022-06-16 13:47 UTC, gqcn commented
@wangle201210 已经通过命令行安装方式简化CLI安装，这里对`update`命令不再有需求。因此关闭该PR。

2022-06-16 13:47 UTC, closed without merging