feat: support custom listener
gogf/gf pull request #1683
Opened 2022-03-18 13:25 UTC by Macrow

Add SetListener method for supporting custom listeners.

```go
ln, err := net.Listen("tcp", ":9999")
if err != nil {
  log.Fatal(err)
}
listeners := map[string]net.Listener{":9999": ln}

....

s := g.Server()

// when server is starting, it will find the custom listener in map which math the address by key
// 系统初始化时，会在预设的listeners里面查找匹配地址的listener，进行设定
s.SetAddr(":9999")
s.SetListener(listeners)

...

s.Run()
```

### multiple listeners
```go
ln1, err := net.Listen("tcp", ":9999")
if err != nil {
  log.Fatal(err)
}
ln2, err := net.Listen("tcp", ":8888")
if err != nil {
  log.Fatal(err)
}

listeners := map[string]net.Listener{":9999": ln1, ":8888": ln2}

....

s := g.Server()
s.SetAddr(":9999")
s.SetAddr(":8888")
s.SetListener(listeners)

...

s.Run()
```

另外有相关的issue
https://github.com/gogf/gf/issues/1043

2022-03-19 14:40 UTC, gqcn requested changes

2022-03-19 14:40 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +	// Listeners specifies custom listeners, size should match address provided
注释末尾应当加上英文结束符号`.`。

2022-03-19 14:40 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +func (s *Server) SetListener(ln map[string]net.Listener) {
- 该方法应当有详尽的英文注释。
- 方法定义为`SetListener(address string, ln net.Listener)`应当会好一些。

2022-03-19 14:48 UTC, gqcn requested changes

2022-03-19 14:48 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +	Listeners map[string]net.Listener `json:"listeners"`
多个`Address`采用多`Server`实现，所以这里不需要支持多个`Address`，这里直接定义为`net.Listener`类型即可。

2022-03-19 14:50 UTC, gqcn commented
@Macrow 感谢参与贡献！实现的想法不错，除了代码中CR注释，这里再提点要求：任何功能的新增都应当有单元测试，以保障逻辑正确及代码质量。这一点非常重要。

2022-03-19 18:28 UTC, Macrow commented on net/ghttp/ghttp_server_config.go
> +func (s *Server) SetListener(ln map[string]net.Listener) {
我查看了在```ghttp_server_graceful.go```的```startServer```方法，实际上是创建多个```gracefulServer```实例，所以还是需要使用多个```Listener```。

2022-03-19 18:40 UTC, Macrow commented
@gqcn 已经按照你的修改意见进行了调整，添加了单元测试。

另外对初始化listeners时做了一点点调整。使用端口作为listeners的key，以用来匹配替换rawListener。

```go
ln, err := net.Listen("tcp", ":8199")
if err != nil {
  log.Fatal(err)
}
listeners := map[int]net.Listener{8199: ln}

....

s := g.Server()

// 系统初始化时，会在预设的listeners里面查找匹配地址的listener，进行设定。
// 匹配到端口时，系统会检查该listener的实际端口是否和指定的端口一致，不一致也会忽略该listener。
s.SetAddr(":8199")
s.SetListeners(listeners)

...

s.Run()
```

```go
ln1, err := net.Listen("tcp", ":9999")
if err != nil {
  log.Fatal(err)
}
ln2, err := net.Listen("tcp", ":8888")
if err != nil {
  log.Fatal(err)
}

listeners := map[string]net.Listener{9999: ln1, 8888: ln2}

....

s := g.Server()
s.SetAddr(":9999,:8888")
s.SetListeners(listeners)

...

s.Run()
```

2022-03-21 13:42 UTC, gqcn requested changes

2022-03-21 13:42 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +			intlog.Printf(context.TODO(), `ignore the listener with port %d`, k)
如果产生`error`，不要忽略，返回，由上层调用方决定如何处理。

2022-03-21 13:42 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +func (s *Server) SetListeners(listeners map[int]net.Listener) {
大部分的`Server`都是单`Server`，因此很有必要再增加一个方法`SetListener(ln net.Listener)`，在内部根据`ln.Addr().String()`自动设置`Address`属性。

2022-03-22 14:00 UTC, Macrow commented
新增了```SetListener```方法，该方法会覆盖之前设置的地址端口。

另外，我在本地通过了所有测试，但github上的ci测试没有通过，点击进入错误详情看不到具体哪里出错，能否看看具体哪里测试没过？

<img width="491" alt="F8E059F6-9726-40F9-BC06-A4B4E7705C2C" src="https://user-images.githubusercontent.com/240792/159498696-2cdfc53f-95d3-435f-a5a0-b0da602a97d2.png">

2022-03-29 09:51 UTC, Macrow commented
@gqcn 强哥有空帮忙看看ci错误在哪儿？

2022-03-29 12:45 UTC, gqcn requested changes

2022-03-29 12:45 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +		return gerror.NewCodef(gcode.CodeInvalidParameter, "listener is nil")
错误提示信息应当具有明确的含义，例如：`listener cannot be nil`

2022-03-29 12:45 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_custom_listeners_test.go
> +func Test_SetCustomListener(t *testing.T) {
- 单例的端口请参考现有示例，使用随机端口，以免端口回收较慢引起监听失败。
- 端口监听是异步的，你可能需要等待一定时间再开始请求，具体也请参考现有示例。

2022-03-29 12:46 UTC, gqcn commented
@Macrow 
![image](https://user-images.githubusercontent.com/26347176/160614298-3e4bdecb-3d55-48f1-a865-e39ee3e9b9cf.png)

2022-03-31 14:01 UTC, gqcn requested changes

2022-03-31 14:01 UTC, gqcn commented on net/ghttp/ghttp_server_graceful.go
> +				}
```go
if listenerPort := (v.Addr().(*net.TCPAddr)).Port; listenerPort == addrPort {
    gs.rawListener = v
    break
}
```

2022-04-07 12:05 UTC, merged