upgrade ClickHouse dependencies to V2
gogf/gf pull request #1772
Opened 2022-04-19 06:22 UTC by DGuang21

feature: 
clickhouse dependencies to v2
use sqlparser replace STD SQL to Clickhouse SQL grammar

2022-05-14 04:24 UTC, DGuang21 commented on contrib/drivers/clickhouse/go.mod
> +	github.com/google/uuid v1.3.0
项目中已经不再引用了，等 clickhouse 发布新 tag 后再一起删掉这里

2022-05-17 12:54 UTC, gqcn requested changes

2022-05-17 12:54 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse.go
> +func (d *Driver) ConvertDataForRecordValue(ctx context.Context, value interface{}) interface{} {
如果不需要实现该接口，请删除。

2022-05-17 12:54 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse.go
> +// ConvertDataForRecord converting for any data that will be inserted into table/collection as a record.
如果不需要实现该接口，请删除。

2022-05-17 12:54 UTC, gqcn commented on database/gdb/gdb_core_ctx.go
> +func (c *Core) GetNeedParsedSqlFromCtx(ctx context.Context) bool {
我看了下你这两个方法都是在`clickhouse`的`driver`实现中调用，那么就不要写到公共组件中。

2022-05-18 12:11 UTC, gqcn requested changes

2022-05-18 15:32 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> +}
> 请拉取下主库最新的`master`分支，将`ConvertDataForRecord`和`ConvertDataForRecordValue`删除，试试。 如果不行的话，去掉`ConvertDataForRecordValue`，参考主库的`ConvertDataForRecord`去掉重复判断逻辑再提交。

已将 `DataToMapDeep` / `ConvertDataForRecordValue` / `ConvertDataForRecord` 中的逻辑合并精简

2022-05-19 13:22 UTC, gqcn requested changes

2022-05-19 13:22 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse_test.go
>  }
`TableField`的每个属性都要断言哈

2022-05-23 13:21 UTC, gqcn approved these changes

2022-05-23 13:21 UTC, merged