Feature/polaris feat: Add Polaris support
gogf/gf pull request #1797
Opened 2022-05-03 15:14 UTC by houseme

Add Polaris service

https://github.com/gogf/gf/issues/1504

https://github.com/gogf/gf/issues/1826

https://github.com/polarismesh/polaris/issues/163

2022-05-12 13:43 UTC, gqcn requested changes

2022-05-12 13:43 UTC, gqcn commented on contrib/registry/polaris/registry.go
> +			if instanceEvent, ok := event.(*model.InstanceEvent); ok {
代码块嵌套层级太深，请调整下代码组织结构。
例如：
```go
if instanceEvent, ok := event.(*model.InstanceEvent); !ok {
    return nil, nil
}
// 正常逻辑
```

2022-05-12 13:43 UTC, gqcn commented on contrib/registry/polaris/registry.go
> +	if k, ok := metadata["kind"]; ok {
`kind/version`等硬编码的字符串内容请定义为常量。

2022-05-12 13:43 UTC, gqcn commented on example/.gitignore
> +### JetBrains template
请去掉该文件。

2022-05-12 13:43 UTC, gqcn commented on net/gsvc/gsvc_service.go
>  	separator = "/"
`separator -> defaultSeparator`

2022-05-12 13:43 UTC, gqcn commented on net/gsvc/gsvc_service.go
> +	six   = 6
为什么要加这些数字的常量。。。？！

2022-05-12 13:43 UTC, gqcn commented on net/gsvc/gsvc_search.go
> +	}
你在读操作中修改对象属性？
建议，将`getSeparator`封装为方法，或者：
```go
var separator = s.Separator
if separator == "" {
    separator = defaultSeparator
}
```
以下同。

2022-05-12 13:43 UTC, gqcn commented on net/gsvc/gsvc.go
> +	Endpoints  []string // Service Endpoints, pattern: IP:port, eg: 192.168.1.2:8000.
`Search`方法的目的就是为了搜索服务并得到其`Endpoints`。。所以这里并不需要`Endpoints`。

2022-05-12 13:43 UTC, gqcn commented on net/gsvc/gsvc.go
> +	Endpoints  []string // Service Endpoints, pattern: IP:port, eg: 192.168.1.2:8000.
注意`Endpoints`是服务(`Service`)的地址，不是`polaris`或者`etcd`的地址。`polaris`或者`etcd`的地址在服务注册对象初始化的由开发者指定的。
所以这里并不需要`Endpoints`。

2022-05-12 13:43 UTC, gqcn commented on util/gvalid/gvalid_custom_rule.go
> +// RegisterRule registers custom validation rules and function for package.
`rule`

2022-05-12 14:04 UTC, houseme commented on net/gsvc/gsvc.go
> +	Endpoints  []string // Service Endpoints, pattern: IP:port, eg: 192.168.1.2:8000.
done

2022-05-12 14:06 UTC, houseme commented on net/gsvc/gsvc.go
> +	Endpoints  []string // Service Endpoints, pattern: IP:port, eg: 192.168.1.2:8000.
done

2022-05-12 14:22 UTC, houseme commented on net/gsvc/gsvc_search.go
> +	}
done

2022-05-12 14:26 UTC, houseme commented on util/gvalid/gvalid_custom_rule.go
> +// RegisterRuleByMap registers custom validation rules using maps for package.
done

2022-05-12 15:08 UTC, houseme commented on contrib/registry/polaris/doc.go
> +package polaris
done

2022-05-12 15:08 UTC, houseme commented on contrib/registry/polaris/.gitignore
> +### Example user template template
done

2022-05-12 15:26 UTC, houseme commented on net/gsvc/gsvc_service.go
> +// Key formats the service information and return the Service as registering key.
done

2022-05-12 16:18 UTC, houseme commented on contrib/registry/polaris/registry.go
> +	_ gsvc.Registrar = &Registry{}
done

2022-05-12 16:30 UTC, houseme commented on contrib/registry/polaris/registry.go
> +			if instanceEvent, ok := event.(*model.InstanceEvent); ok {
done

2022-05-12 16:31 UTC, houseme commented on util/gvalid/gvalid_validator_check_struct.go
> +		fieldToAliasNameMap = make(map[string]string)           // Field names to alias name maps.
done

2022-05-12 16:32 UTC, houseme commented on contrib/registry/polaris/registry.go
> +func WithNamespace(namespace string) Option {
配置暂时不改

2022-05-13 09:45 UTC, gqcn requested changes

2022-05-13 09:45 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +	_ gsvc.Registrar = &Registry{}
这里应该是`_ gsvc.Registry = &Registry{}`，该断言保障`Registry`对象能同时实现注册和发现两个特性，参考下`etcd`实现。

2022-05-13 09:45 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +// Copyright GoFrame Author(https://goframe.org). All Rights Reserved.
能否在目录下加个`README.MD`，介绍如何使用该`polaris`包。`etcd`那个包我来加。

2022-05-13 09:45 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +const _instanceIDSeparator = "-"
能否不要使用`_`开头的名称定义。

2022-05-13 10:42 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	}
done

2022-05-13 10:43 UTC, houseme commented on net/gsvc/gsvc_service.go
> +}
done

2022-05-13 10:45 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	delimiter        = ","
done

2022-05-13 10:47 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	_ gsvc.Registrar = &Registry{}
done

2022-05-13 10:48 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +const _instanceIDSeparator = "-"
done

2022-05-13 11:37 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	return s.Separator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, s.Separator)
done

2022-05-13 11:38 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	return s.Separator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, s.Separator)
done

2022-05-13 11:38 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +// Copyright GoFrame Author(https://goframe.org). All Rights Reserved.
done

2022-05-16 12:19 UTC, gqcn requested changes

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +func NewRegistry(provider polaris.ProviderAPI, consumer polaris.ConsumerAPI, opts ...Option) (r *Registry) {
`NewRegistry -> New`

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +func NewRegistryWithConfig(conf config.Configuration, opts ...Option) (r *Registry) {
`NewRegistryWithConfig -> NewWithConfig`

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +	endpoint = gstr.ReplaceByArray(endpoint, []string{"tcp://", "", "udp://", "", "http://", "", "https://", "", "ws://", "", "wss://", ""})
不用做替换，使用默认的`endpoint`约定，即`host:port`格式。
这个格式倒是可以在`gsvc`那边服务注册的时候加个校验，而不是在所有使用的地方再去校验。

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +	httpArr := gstr.Split(endpoint, endpointDelimiter)
- 为什么用`httpArr`，这是`HTTP`地址吗？
- `gstr.Split -> gstr.SplitAndTrim`

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris.go
> +	portArr := gstr.Split(httpArr[1], "?")
地址中不可能会包含这种字符。

2022-05-16 12:19 UTC, gqcn commented on net/gsvc/gsvc_service.go
> +	defaultSeparator := DefaultSeparator
`defaultSeparator -> separator` 前者作为临时分隔符变量容易引起误解。比如当`defaultSeparator = s.Separator`赋值过后，该变量的意义就不在是默认分隔符号。

2022-05-16 12:19 UTC, gqcn commented on net/gsvc/gsvc_service.go
> +	defaultSeparator := DefaultSeparator
`defaultSeparator -> separator `

2022-05-16 12:19 UTC, gqcn commented on net/gsvc/gsvc_service.go
> +	return defaultSeparator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, defaultSeparator)
这段代码重复率标高，请参考如下：
```go
var separator = defaultSeparator
if s.Separator != "" {
	separator = s.Separator
}
return separator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, separator)
```

2022-05-16 12:19 UTC, gqcn commented on contrib/registry/polaris/polaris_registry.go
> +// Copyright GoFrame Author(https://goframe.org). All Rights Reserved.
文件名改为`polaris_registrar`吧，更贴近文件的作用 - 实现`gsvc.Registrar`接口，顺便帮忙把`etcd`那边也改一下。

2022-05-16 12:22 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	endpoint = gstr.ReplaceByArray(endpoint, []string{"tcp://", "", "udp://", "", "http://", "", "https://", "", "ws://", "", "wss://", ""})
这个 那我去修改一下_test.go文件

2022-05-16 12:23 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	portArr := gstr.Split(httpArr[1], "?")
OK

2022-05-16 12:23 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	defaultSeparator := DefaultSeparator
ok

2022-05-16 12:23 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	defaultSeparator := DefaultSeparator
ok

2022-05-16 12:32 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	return defaultSeparator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, defaultSeparator)
这个地方是和默认的不相同，在最前面不添加分隔符。

2022-05-16 12:34 UTC, houseme commented on contrib/registry/polaris/polaris_registry.go
> +// Copyright GoFrame Author(https://goframe.org). All Rights Reserved.
ok

2022-05-16 12:39 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +func NewRegistryWithConfig(conf config.Configuration, opts ...Option) (r *Registry) {
done

2022-05-16 12:39 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +func NewRegistry(provider polaris.ProviderAPI, consumer polaris.ConsumerAPI, opts ...Option) (r *Registry) {
done

2022-05-16 12:40 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	endpoint = gstr.ReplaceByArray(endpoint, []string{"tcp://", "", "udp://", "", "http://", "", "https://", "", "ws://", "", "wss://", ""})
done

2022-05-16 12:40 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	httpArr := gstr.Split(endpoint, endpointDelimiter)
done

2022-05-16 12:44 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +	portArr := gstr.Split(httpArr[1], "?")
done

2022-05-16 12:47 UTC, houseme commented on net/gsvc/gsvc_service.go
> +	return defaultSeparator + gstr.Join([]string{s.Prefix, s.Deployment, s.Namespace, s.Name, s.Version}, defaultSeparator)
done

2022-05-16 13:20 UTC, gqcn requested changes

2022-05-16 14:12 UTC, houseme commented on contrib/registry/polaris/polaris.go
> +		return
done

2022-05-17 03:43 UTC, chuntaojun commented on contrib/registry/polaris/polaris_registrar.go
> +			go func() {
是不是需要进行控制下这个协程？反注册的话走context.Cancel进行取消

2022-05-17 12:47 UTC, gqcn approved these changes

2022-05-18 13:21 UTC, houseme commented on contrib/registry/polaris/polaris_registrar.go
> +			go func() {
done

2022-05-18 14:24 UTC, merged