Fix/1748 issues #1748
gogf/gf pull request #1817
Opened 2022-05-10 15:36 UTC by houseme

https://github.com/gogf/gf/issues/1748

2022-05-11 06:08 UTC, gqcn requested changes

2022-05-11 06:08 UTC, gqcn commented on net/ghttp/ghttp_request_param_file.go
> +	return json.Marshal(gconv.Map(f))
```go
return json.Marshal(f.FileHeader)
```
此外，issue#1748 的主因并不是这个，应该是属性初始化的问题。

2022-05-11 06:08 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		File       *ghttp.UploadFile `type:"file" v:"required"`
该用例是测试上传功能本身的，不是测试校验，不应该加校验规则。

2022-05-11 06:08 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		File       ghttp.UploadFiles `type:"file" v:"required"`
属性应该用`*ghttp.UploadFile`

2022-05-11 06:08 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		if file == nil {
单例缺少校验组件的使用，应该使用`r.Parse`来测试`required`规则是否对`*ghttp.UploadFile`生效。
当客户端没有上传文件时，`r.File`应该是`nil`。

2022-05-11 06:54 UTC, houseme commented on net/ghttp/ghttp_request_param_file.go
> +	return json.Marshal(gconv.Map(f))
done

2022-05-11 06:54 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		File       *ghttp.UploadFile `type:"file" v:"required"`
done

2022-05-11 06:54 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		File       ghttp.UploadFiles `type:"file" v:"required"`
done

2022-05-11 06:58 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		if file == nil {
done

2022-05-12 12:43 UTC, gqcn requested changes

2022-05-12 12:43 UTC, gqcn commented on net/ghttp/ghttp_request_param_file.go
>  	ctx                   context.Context
当实现了`MarshalJSON`接口后，这里的`json:"-"`不再有意义。

2022-05-12 12:43 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		if file == nil {
这里的`if file == nil {`判断是没有意义的，因为`req.File`已经有`required`规则了，已经被校验组件校验通过了才能进入到这个地方。

注意：下面的断言一定要判断`required`规则结果。即：不上传文件请求来看该规则是否生效。

2022-05-12 12:43 UTC, gqcn commented on util/gconv/gconv_scan.go
> +
去掉空行。

2022-05-12 12:52 UTC, houseme commented on net/ghttp/ghttp_request_param_file.go
>  	ctx                   context.Context
这个如果去掉了，接口文档里就显示的是可以展开的对象了

2022-05-12 12:58 UTC, houseme commented on util/gconv/gconv_scan.go
> +
done

2022-05-13 12:30 UTC, gqcn requested changes

2022-05-16 12:58 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +func Test_Params_File_Upload_Required(t *testing.T) {
234行

2022-05-17 12:59 UTC, gqcn requested changes

2022-05-17 12:59 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		t.AssertNE(content, "upload file is required")
当文件不上传时，按理说应该返回`upload file is required`，所以你这里的断言应该是`t.Assert(content, "upload file is required")`。如果断言不通过那么表示`issue`并没有被修复。

2022-05-17 12:59 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +	gtest.C(t, func(t *gtest.T) {
不需要的`case`，类似单测已经被覆盖，请删除。

2022-05-17 12:59 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +	gtest.C(t, func(t *gtest.T) {
不需要的`case`，类似单测已经被覆盖，请删除。

2022-05-17 12:59 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +			r.Response.WriteExit("upload file is required")
`r.Response.WriteExit(err.Error())`

2022-05-17 12:59 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +func Test_Params_File_Upload_Required(t *testing.T) {
本单测不需要校验上传正确的逻辑，因为其他单测已经验证过了。该单测应该验证没有上传文件时，服务端应该返回校验错误。

2022-05-19 10:16 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +func Test_Params_File_Upload_Required(t *testing.T) {
done

2022-05-19 10:17 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +	gtest.C(t, func(t *gtest.T) {
done

2022-05-19 10:17 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +		t.AssertNE(content, "upload file is required")
done

2022-05-19 10:17 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +	gtest.C(t, func(t *gtest.T) {
done

2022-05-19 10:19 UTC, houseme commented on net/ghttp/ghttp_z_unit_feature_request_file_test.go
> +			r.Response.WriteExit("upload file is required")
done

2022-05-23 14:09 UTC, merged