Improve the code coverage of the gtcp module
gogf/gf pull request #1836
Opened 2022-05-14 08:04 UTC by huangqian1985

2022-05-19 13:06 UTC, gqcn requested changes

2022-05-19 13:06 UTC, gqcn commented on net/gtcp/gtcp_z_unit_pool_test.go
> +		t.AssertNE(err, nil)
缺少返回内容断言。

2022-05-19 13:06 UTC, gqcn commented on net/gtcp/gtcp_z_unit_pool_test.go
> +		t.AssertNE(err, nil)
缺少返回内容断言。

2022-05-19 13:06 UTC, gqcn commented on net/gtcp/gtcp_z_unit_pool_test.go
> +		t.AssertNil(err)
缺少返回内容断言。

2022-05-19 13:06 UTC, gqcn commented on net/gtcp/gtcp_z_unit_pool_test.go
> +		t.AssertNil(err)
服务端缺少接收客户端内容的正确性断言。
客户端缺少与服务端内容通信的连通性断言。

2022-05-19 13:19 UTC, huangqian1985 commented on net/gclient/gclient_z_example_test.go
> +	)
gclient的我手误merge进来了, 后面一起改了

2022-05-23 14:45 UTC, gqcn approved these changes

2022-05-23 14:45 UTC, merged