Feature/pgsql add pgsql unit test
gogf/gf pull request #1853
Opened 2022-05-18 04:55 UTC by chaggle

2022-05-18 13:37 UTC, gqcn requested changes

2022-05-18 14:14 UTC, gqcn requested changes

2022-05-18 15:08 UTC, chaggle commented on contrib/drivers/pgsql/pgsql_db_test.go
> +func Test_DB_TableFields(t *testing.T) {
done

2022-05-18 15:08 UTC, chaggle commented on contrib/drivers/pgsql/pgsql_init_test.go
> +	_ "github.com/lib/pq"
done

2022-05-19 12:07 UTC, gqcn requested changes

2022-05-19 12:07 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +			config.User, config.Pass, config.Host, config.Port,
这里不能去掉数据库名称配置，会引起数据库名称配置失效。
如果不想连接特定数据库，尝试设置数据库名称为空试试。

2022-05-23 13:31 UTC, merged