fix gf run custom arguments
gogf/gf pull request #1878
Opened 2022-05-24 13:12 UTC by omegamt

之前使用 gf run main.go --args "-www ./product debug true" 一直没法把参数传进去
经测试以下两运行方式接收到的参数一致
$ gf run main.go --args "-www ./product debug true"
$ ./main -www ./product debug true

2022-06-16 13:42 UTC, gqcn requested changes

2022-06-16 13:42 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +	mlog.Print(app.Args)
请去掉这两条调试信息。

2022-06-18 00:24 UTC, Essam790 approved these changes

2022-06-18 00:26 UTC, Essam790 approved these changes

2022-06-18 00:29 UTC, Essam790 reviewed
1

2022-06-23 13:25 UTC, gqcn commented
@omegamt

2022-06-30 12:25 UTC, gqcn commented
@omegamt duplicated with https://github.com/gogf/gf/pull/1879.

2022-06-30 12:25 UTC, closed without merging