fix gf run custom arguments and gf gen dao specify config file path
gogf/gf pull request #1879
Opened 2022-05-24 22:07 UTC by omegamt

不知为何gf gen dao工具一直没有把指定配置路径选项完善一下, 不是很常用吗 
https://goframe.org/pages/viewpage.action?pageId=3673173 的使用方式示例
gf gen dao -p ./model -c config.yaml -g user-center -t user,user_detail,user_login
-c 一直用不了,  短命令已被 DescriptionTag 占用了  short命令找不到合适的就用了cfg
以下测试没问题
gf gen dao -p ./src  -cfg ./myconf/conf.toml

之前使用 gf run main.go --args "-www ./product debug true" 一直没法把参数传进去
经测试以下两运行方式接收到的参数一致
$ gf run main.go --args "-www ./product -debug true"
$ ./main -www ./product -debug true

2022-06-23 13:28 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +	cRunArgsBrief  = `custom arguments`
`custom arguments for your process`

2022-06-30 12:18 UTC, gqcn approved these changes

2022-06-30 12:24 UTC, gqcn requested changes

2022-06-30 12:24 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_gen_dao.go
> +		ConfigPath     string `name:"configPath"      short:"cfg" brief:"{cGenDaoBriefConfigPath}"`
关于这个参数，我仔细思考了很久。
要么提到最外层，作为整个`gf`命令行的基础参数，提供统一的`-c/config`参数，因为其他命令也需要用到这个配置。将原有其他命令的`-c`参数改为其他名称。要么本次PR就删掉这个参数，我后面统一改。

2022-06-30 12:40 UTC, omegamt commented on cmd/gf/internal/cmd/cmd_gen_dao.go
> +		ConfigPath     string `name:"configPath"      short:"cfg" brief:"{cGenDaoBriefConfigPath}"`
好的, 大佬有时间统一改当然最好啦 , 已经删除了这个参数.

2022-07-04 12:42 UTC, gqcn approved these changes

2022-07-04 13:01 UTC, merged