Improve the code coverage of the gclient module
gogf/gf pull request #1899
Opened 2022-06-08 13:59 UTC by huangqian1985

Issue：https://github.com/gogf/gf/issues/1835

2022-06-09 13:04 UTC, gqcn requested changes

2022-06-09 13:04 UTC, gqcn commented on net/gclient/gclient_z_example_test.go
> +	client.Get(ctx, "")
1. 这个例子不是很好，你应当能展示出`Prefix`的具体作用。例如给每个请求增加`URI`前缀`/api/v1`之类的。可以再加点英文注释说明。
2. 这里的`Get`请求是想表达什么？

2022-06-09 13:04 UTC, gqcn commented on net/gclient/gclient_z_example_test.go
> +	// Output:
这个例子写得很好，展示得很完整。

2022-06-09 13:28 UTC, huangqian1985 commented on net/gclient/gclient_z_example_test.go
> +	// Output:
哈哈哈 谢谢夸奖

2022-06-09 13:28 UTC, huangqian1985 commented on net/gclient/gclient_z_example_test.go
> +	client.Get(ctx, "")
有点强行凑代码的意思。我改改

2022-06-13 11:31 UTC, gqcn approved these changes

2022-06-13 11:31 UTC, merged