Feature/pgsql last insert
gogf/gf pull request #1994
Opened 2022-07-12 06:50 UTC by hailaz

2022-07-12 09:33 UTC, hailaz commented
#1793

2022-07-13 12:33 UTC, gqcn requested changes

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +	case gdb.InsertOptionDefault:
缺少`InsertOptionIgnore`的`case`。

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +type pgResult struct {
这个结构体的定义和维护可以单独创建个文件`pgsql_result.go`

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		useCore    bool   = false
该变量为了判断是否在`master`上执行？可以使用`link.IsOnMaster`方法。

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +	pkField, ok := ctx.Value(internalPrimaryKeyInCtx).(gdb.TableField)
`ctx.Value(internalPrimaryKeyInCtx)`可能返回`nil`？

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		primaryKey = pkField.Name
如果`pkField`是`nil`或者`pkField.Name`就不应该加上`RETURNING`语句对吧？

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		sql += "RETURNING " + primaryKey
`RETURNING`前不用加空格？

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		if !strings.Contains(pkField.Type, "int") {
`pkField`可能为`nil`？

2022-07-13 12:33 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +	// sql, args = formatSql(sql, args) //TODO: internal function
注释换行。

2022-07-14 11:32 UTC, hailaz commented on contrib/drivers/pgsql/pgsql.go
> +		sql += "RETURNING " + primaryKey
前面的sql有空格

2022-07-27 12:04 UTC, gqcn requested changes

2022-07-27 12:04 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		Type:          gdb.SqlTypeQueryContext,
你这里相当于把所有的写入更新删除请求都通过`gdb.SqlTypeQueryContext`方式执行了，建议根据有无带`RETURNING`语句来做判断。

2022-07-28 02:14 UTC, hailaz commented on contrib/drivers/pgsql/pgsql.go
> +	return nil, gerror.NewCodef(gcode.CodeUnknown, "No affected rows")
这里是插入的逻辑

2022-07-28 02:25 UTC, hailaz commented on contrib/drivers/pgsql/pgsql.go
> +		Type:          gdb.SqlTypeQueryContext,
只有插入操作才会往下走，其它操作不会走到这里

2022-07-29 11:14 UTC, gqcn requested changes

2022-07-29 11:14 UTC, gqcn commented on contrib/drivers/pgsql/pgsql.go
> +		Type:          gdb.SqlTypeQueryContext,
由于你实现的是`DoExec`，这个接口在整个ORM操作流程中的位置如下：


![image](https://user-images.githubusercontent.com/26347176/181747578-2db4c0cb-eb2c-4cec-b1b5-87f2d1032cba.png)

2022-08-01 02:10 UTC, hailaz commented on contrib/drivers/pgsql/pgsql.go
> +		Type:          gdb.SqlTypeQueryContext,
372 return d.Core.DoExec(ctx, link, sql, args...)

2022-08-08 13:57 UTC, gqcn approved these changes

2022-08-09 11:45 UTC, merged