feature: issue (#2060)
gogf/gf pull request #2067
Opened 2022-08-15 05:02 UTC by LonelySally

2022-08-15 06:32 UTC, mingzaily reviewed
I think so.

2022-08-15 06:43 UTC, mingzaily approved these changes

2022-08-15 12:26 UTC, gqcn requested changes

2022-08-15 12:26 UTC, gqcn commented on net/ghttp/ghttp.go
>  var (
我们这里只需要关注`OpenAPI`里面`in`参数的`header`和`cookie`，其他方式的提交参数已经合并到了`data`中。

2022-08-15 12:26 UTC, gqcn commented on net/ghttp/ghttp.go
> +	inValueTags = []string{"in"}
- 只需要定义一个标签名称即可
- 注释更新下

2022-08-15 12:26 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +			if foundKey != "" {
不要在这里使用`gutil.MapPossibleItemByKey`判断，而是在对应的`case`中使用。
例如，在`header`中，那么应当使用`gutil.MapPossibleItemByKey(HeaderMap, field.Name())`。
此外，你应当考虑别名情况，所有的别名在`gconv.StructTagPriority`，可以通过`field.Tag(别名)`来判断。

2022-08-15 12:26 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +	if len(tagFields) > 0 {
如果`tagFields`为空，直接`return nil`

2022-08-15 12:44 UTC, LonelySally commented on net/ghttp/ghttp.go
>  var (
可以继续补cookie，但是我认为query form router是有必要的。入参是由用户端决定的，但是取参应当有能力让服务端决定

2022-08-15 12:45 UTC, LonelySally commented on net/ghttp/ghttp.go
> +	inValueTags = []string{"in"}
这里是为了与其它标签保持风格一致

2022-08-15 12:48 UTC, LonelySally commented on net/ghttp/ghttp_request_param_request.go
> +			if foundKey != "" {
一开始是考虑的别名的情况，但是看到了default标签的实现又感觉有必要与它保持一致（我想多数使用者已经习惯了d标签）。

2022-08-15 12:57 UTC, gqcn commented on net/ghttp/ghttp.go
>  var (
原本`data`中已经有`query/form/route/param`了，所以这里不需要额外处理了，有点冗余：https://github.com/gogf/gf/blob/43b84f40448c26ffb715aac61fe8dbffa5834351/net/ghttp/ghttp_request_param_request.go#L62

2022-08-15 12:58 UTC, gqcn commented on net/ghttp/ghttp.go
> +	inValueTags = []string{"in"}
其他的标签是因为有多个，你这里只有一个标签名称。

2022-08-15 12:59 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +			if foundKey != "" {
别名的处理是基于严谨的考虑，可以改一下。

2022-08-15 13:42 UTC, mingzaily commented on net/ghttp/ghttp_request_param_request.go
> +	if len(tagFields) > 0 {
我们也是，遇到异常，一般是提前抛出

2022-08-17 11:40 UTC, gqcn requested changes

2022-08-17 11:40 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +				if queryValue, ok := r.queryMap[foundKey]; ok {
使用`r.GetQuery`

2022-08-17 11:40 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +				if formValue, ok := r.formMap[foundKey]; ok {
使用`r.GetFom`

2022-08-17 11:40 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +				if routerValue, ok := r.routerMap[foundKey]; ok {
使用`r.GetRoute`

2022-08-17 11:40 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +			searchKey, _ = gutil.MapPossibleItemByKey(data, field.Name())
直接`data[searchKey] = foundValue`覆盖吧，当`data`中存在多个值时，`gconv`组件会按照优先级赋值。

2022-08-31 12:59 UTC, gqcn commented
@LonelySally 我看了你最新的提交，老实说，我有点看不懂了。。

2022-08-31 13:08 UTC, LonelySally commented
> @LonelySally 我看了你最新的提交，老实说，我有点看不懂是在干啥。。

- 在项目启动的时候把符合checkAndCreateFuncInfo校验条件的结构体设置到inputTagsMap里,这里结构体名称作为map的key
- 在请求发生时,用结构体名称通过GetInputTagInfo取到启动时对应结构体的反射结果,再解析需要的tag标签组获取对应的tag值.首次获取时采取匹配(类似orm的表结构缓存),后续直接以结构体名称+tag名称(数组转字符串逗号分割做为key)方式取匹配结果.
emm...大概就是这么个流程

2022-10-11 01:49 UTC, zcyc commented
i recommend change it to high priority, because it makes `in:header` not only for swagger in api.

2022-12-28 03:52 UTC, closed without merging