fix issue bot :ignore issue which without labels
gogf/gf pull request #2077
Opened 2022-08-18 01:43 UTC by LingCoder

2022-08-18 13:05 UTC, gqcn requested changes

2022-08-18 13:05 UTC, gqcn commented on .github/workflows/issue-check-inactive.yml
> +    - cron: "0 19 * * *"
不能改时区为东八区？比如：
![image](https://user-images.githubusercontent.com/26347176/185401849-ccc8946c-c19d-4e21-91b7-6de4a5a573be.png)

2022-08-18 13:05 UTC, gqcn commented on .github/workflows/issue-close-inactive.yml
> +name: Issue Close Require
为什么是`Require`而不是`Inactive`?

2022-08-19 02:17 UTC, LingCoder commented on .github/workflows/issue-close-inactive.yml
> +name: Issue Close Require
参考的模板没有修改干净。。。

2022-08-19 02:18 UTC, LingCoder commented on .github/workflows/issue-check-inactive.yml
> +    - cron: "0 19 * * *"
好的，我按照这上面的配置在个人仓库测试一下。确认可行后修改新PR

2022-08-31 12:50 UTC, gqcn approved these changes

2022-09-06 09:45 UTC, LingCoder commented
找个怎么没有通过

2022-09-11 12:05 UTC, gqcn approved these changes

2022-09-14 07:44 UTC, merged