gstr.CaseCamel add special case
gogf/gf pull request #2087
Opened 2022-08-23 03:11 UTC by promisingMan

special case, all characters are uppercase or numbers or underscores, eg:HELLO_WORLD->HelloWorld

@[https://github.com/gogf/gf/issues/2078]
@DGuang21

2022-08-24 13:30 UTC, gqcn requested changes

2022-08-24 13:30 UTC, gqcn commented on text/gstr/gstr_case.go
> +		if !((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
可以参考一下`CaseSnakeFirstUpper`方法的实现，新增一个`CaseCamelFirstUpper`方法，而不是修改原有方法，因为目前你这种判断会降低原有`CaseCamel*`方法的性能。

另外，考虑到基础方法的性能，请尽量不要两次遍历。

2022-08-27 05:02 UTC, promisingMan commented on text/gstr/gstr_case.go
> +		if !((c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
强哥，您好，根据您的建议我优化了一版，您看看 @gqcn

2022-08-30 04:03 UTC, gqcn requested changes

2022-08-30 04:03 UTC, gqcn commented on text/gstr/gstr_case.go
> +func CaseCamelAllUpper(s string) string {
建议使用`CaseCamelFirstUpper`名称，因为你这个逻辑其实是强制将每个单词按照如果首字母是大写就将单词首字母后面的字符的改为小写。按照你这样的逻辑，`HELLO_WORLD`和`Hello_WORLD`应当转换为`HelloWorld`对吧？

此外，记得将示例添加到顶部代码文件注释中。

2022-08-30 08:39 UTC, promisingMan commented on text/gstr/gstr_case.go
> +func CaseCamelAllUpper(s string) string {
好的👌

2022-08-31 12:24 UTC, gqcn requested changes

2022-08-31 12:24 UTC, gqcn commented on text/gstr/gstr_case.go
> +}
你这里使用的`isSpecial`有点特殊，这个方法对字符串执行两次遍历性能也挺弱的，你可以再参考下我之前的评论。

你可以加一个单例，`CaseCamelFirstUpper(Hello_WORLD) -> HelloWorld`。

2022-08-31 12:24 UTC, gqcn commented on text/gstr/gstr_case.go
> +//   | CaseCamelFirstUpper("ANY_KIND_OF_STRING")| AnyKindOfString    |
注释没有对齐。

2022-09-01 01:42 UTC, promisingMan commented on text/gstr/gstr_case.go
> +//   | CaseCamelFirstUpper("ANY_KIND_OF_STRING")| AnyKindOfString    |
![image](https://user-images.githubusercontent.com/26761403/187814239-d1b61477-d7b9-4dc7-9562-a94f18733d89.png)
我commit的时候是对齐的，我再看看

2022-09-19 11:25 UTC, gqcn commented
@promisingMan 请跟进。

2022-09-21 01:32 UTC, promisingMan commented
> 

收到，强哥，周末跟进，最近比较忙

2022-10-09 12:00 UTC, closed without merging