Feature/v2.2.0 gredis
gogf/gf pull request #2155
Opened 2022-09-27 04:19 UTC by FTLLOVE

2022-09-27 04:20 UTC, FTLLOVE commented
@gqcn

2022-09-27 14:40 UTC, houseme approved these changes
LGTM

2022-09-28 02:14 UTC, gqcn requested changes

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_db.go
> +// Exists Returns if key exists.
注意一下注释的语法，第二个单词应当是小写第三人称，其他方法也要调整一下哈。

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_db.go
> +// In Cluster mode, both key and newkey must be in the same hash slot, meaning that in practice only keys that have the same hash tag can be reliably renamed in cluster.
注释太长了注意换行，其他注释也注意一下哈。

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_db.go
> +func (r *RedisGroupDB) FlushDB(ctx context.Context, options string) (string, error) {
返回的`string`是否可以删除，只返回`error`？其他方法也检查下哈，如果`Redis Server`只是返回一个`OK`，其实就没必要返回这个`string`了。

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_expire.go
> +//See also the PTTL command that returns the same information with milliseconds resolution (Only available in Redis 2.6 or greater).
注释注意加一个空格。

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_hash.go
> +func (r *RedisGroupHash) HMSet(ctx context.Context, key string, fields ...map[string]interface{}) (bool, error) {
由于这些方法都是从你之前定义的`interface`生成出来的，一些细节可能需要检查一下，这里的`fields ...map[string]interface{}`是否改为`fields map[string]interface{}`合适？

2022-09-28 02:14 UTC, gqcn commented on database/gredis/gredis_redis_group_hash.go
> +	v, err := r.redis.Do(ctx, "HMSET", key, fields)
注意检查一下`Redis`官网上的命令格式，改方法的命令使用格式应当是这样的:
![image](https://user-images.githubusercontent.com/26347176/192671938-0df7208b-9e1e-400c-8ad4-300f62a07fd3.png)

2022-09-29 11:42 UTC, merged