feat: create polaris config
gogf/gf pull request #2170
Opened 2022-10-06 15:28 UTC by houseme

2022-10-08 14:09 UTC, gqcn requested changes

2022-10-08 14:09 UTC, gqcn commented on contrib/config/polaris/polaris.go
> +	LogDir string
我不太清楚`polaris`的实现机制，这里的日志控制能够让外部传递日志接口实现来控制吗？例如`glog.ILogger`?

2022-10-08 14:09 UTC, gqcn commented on contrib/config/polaris/polaris.go
> +		g.Log().Debug(ctx, "config file is empty")
- 在基础组件中不要随便打印日志，特别是使用`g.Log()`对象，基础组件的行为逻辑控制权全部交给上层调用方。
- 建议如果不必要的日志就去掉，特别是调试日志；如果实在有必要，就让用户传递日志接口实现`glog.ILogger`。

2022-10-08 14:09 UTC, gqcn commented on example/go.mod
> +	github.com/polarismesh/polaris-go v1.2.0-beta.3
能使用稳定版本吗？

2022-10-08 14:09 UTC, gqcn commented on example/config/polaris/testdata/polaris.yaml
> +      - 183.47.111.80:8093
看起来像是个公网地址？

2022-10-08 14:12 UTC, houseme commented on contrib/config/polaris/polaris.go
> +	Namespace string `v:"required#namespace is required"`
done

2022-10-08 14:17 UTC, houseme commented on contrib/config/polaris/polaris.go
> +	// Whether to watch the configuration.
done

2022-10-08 14:22 UTC, houseme commented on contrib/config/polaris/polaris.go
> +	LogDir string
暂时不可以  https://github.com/polarismesh/polaris-go/blob/0cadab43c5e1613f11180c99ef02b879faa28b15/pkg/log/log.go#L38

2022-10-08 14:25 UTC, houseme commented on example/config/polaris/testdata/polaris.yaml
> +      - 183.47.111.80:8093
这个是北极星的演示项目 `http://14.116.241.63:8080/`

2022-10-08 14:26 UTC, houseme commented on example/go.mod
> +	github.com/polarismesh/polaris-go v1.2.0-beta.3
暂时稳定版还没有发布

2022-10-08 14:32 UTC, houseme commented on contrib/config/polaris/polaris.go
> +		g.Log().Debug(ctx, "config file is empty")
已处理

2022-10-08 14:57 UTC, houseme commented on example/go.mod
> +	github.com/polarismesh/polaris-go v1.2.0-beta.3
这个等发版之后，和注册中心的sdk一起更新吧

2022-10-08 15:50 UTC, houseme commented on contrib/config/polaris/README.MD
> +        Watch:      true,
done

2022-10-09 01:16 UTC, gqcn approved these changes

2022-10-09 11:20 UTC, merged