feat: Upgrade clickhouse go mod depended on and base on go1.18.5 (htt…
gogf/gf pull request #2214
Opened 2022-10-16 08:35 UTC by DGuang21

Upgrade clickhouse go mod depended on and base on go1.18.5 (https://github.com/golang/go/issues/53852)

2022-10-16 08:42 UTC, houseme approved these changes

2022-10-17 07:08 UTC, gqcn requested changes

2022-10-17 07:08 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse.go
> -				config.Host, config.Port, config.Name, config.Charset, config.Debug,
`clickhouse`不支持字符集配置吗？

2022-10-17 07:08 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse.go
> -			m[k] = convertedValue
我看这里类型转换删除的代码有点多，请再次确认下。

2022-10-17 07:08 UTC, gqcn commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
请使用`big.Int`，新增加类型的话注意同步修改一下`cmd/gf`那边的`gen dao`命令，如果生成的代码中带有`big.Int`类型，那么需要引入`math/big`包。

2022-10-17 07:08 UTC, gqcn commented on database/gdb/gdb_core_structure.go
> +		return LocalTypeBigInt, nil
每个数据库有其特殊的数据类型，建议这个判断放到`driver`中自行判断，可以参考`pgsql`的例子，实现`CheckLocalTypeForField`方法。

2022-10-17 07:13 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> -				config.Host, config.Port, config.Name, config.Charset, config.Debug,
> `clickhouse`不支持字符集配置吗？

是的，加上会报错

2022-10-17 07:17 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> -			m[k] = convertedValue
> 我看这里类型转换删除的代码有点多，请再次确认下。

因为`ch`驱动处理`field`部分我也提交过一点代码，`time.Time / *time.Time / decimal.Decimal / *decimal.Decimal / uuid.UUID` 底层有做处理。

像之前添加的 `uuid.UUID / decimal.Decimal` 是因为在会触发到`driver.Valuer` 断言，导致变成String类型，又因为旧的`ch`驱动还没支持String转换，所以才需要特殊处理。

像这里现在只保留`gtime.time`是因为`gtime.time`实现了`String()`方法导致没有必要 time => string => time 解析。

转换部分以后有问题我会直接提Pr到clickhouse-go进行处理，咱们底层能省就省

2022-10-17 07:18 UTC, DGuang21 commented on database/gdb/gdb_core_structure.go
> +		return LocalTypeBigInt, nil
> 每个数据库有其特殊的数据类型，建议这个判断放到`driver`中自行判断，可以参考`pgsql`的例子，实现`CheckLocalTypeForField`方法。

这里有过这个考虑，但是出现的概率太低，如果在`ch`中实现了，对于大多数的类型来说，都需要判断两次，得不偿失

2022-10-17 07:18 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 请使用`big.Int`，新增加类型的话注意同步修改一下`cmd/gf`那边的`gen dao`命令，如果生成的代码中带有`big.Int`类型，那么需要引入`math/big`包。

晚点同步上去

2022-10-17 07:24 UTC, gqcn commented on database/gdb/gdb_core_structure.go
> +		return LocalTypeBigInt, nil
每个数据库特殊的字段类型都写到框架中来判断的话就比较乱，后面很难维护，建议每个`driver`自己的类型自己判断处理。关于性能损耗的话，这种断言也有几十纳秒的损耗，但是设计上解耦多了。

2022-10-17 07:30 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> -				config.Host, config.Port, config.Name, config.Charset, config.Debug,
> 

是的

2022-10-18 12:09 UTC, hd5723 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2

2022-10-18 12:30 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2

现在ci这里还有点东西没处理完，到时候处理完ci过了之后我@你，可以先临时replace

2022-10-20 00:56 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2

目前进度还差gf gen dao部分尚未补充完毕，若不需要使用到该功能，可在go mod 文件当中新增一个replace

replace github.com/gogf/gf =>  github.com/DGuang21/gf master

然后执行命令go mod tidy 即可

2022-10-20 00:57 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2

目前进度还差gf gen dao部分尚未补充完毕，若不需要使用到该功能，可在go mod 文件当中新增一个replace

replace github.com/gogf/gf/contrib/drivers/clickhouse/v2 => github.com/gogf/gf/contrib/drivers/clickhouse/v2 master

然后执行命令go mod tidy 即可，需要注意的是，从当前版本开始，gf-ch驱动最低需要Go Version >= 1.18.5

2022-10-20 01:09 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2

go mod 当中添加一行即可，需要注意的是，从该版本开始，需要 Go Version >= 1.18.5
```
replace github.com/gogf/gf/contrib/drivers/clickhouse/v2 => github.com/DGuang21/gf/contrib/drivers/clickhouse/v2 v2.0.0-20221018132849-8cf0eecb4c3f
```

2022-10-20 01:58 UTC, hd5723 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> > 请问下，现在有哪个分支的源代码可以支持的这次变更么，我本地的gf版本v2.1.2
> 
> go mod 当中添加一行即可，需要注意的是，从该版本开始，需要 Go Version >= 1.18.5
> 
> ```
> replace github.com/gogf/gf/contrib/drivers/clickhouse/v2 => github.com/DGuang21/gf/contrib/drivers/clickhouse/v2 v2.0.0-20221018132849-8cf0eecb4c3f
> ```

sdk版本没问题，我已经用1.9了

2022-10-20 02:33 UTC, hd5723 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
我本地gf版本v2.1.2的，replace之后有报错。
../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/v2@v2.0.0-20221018132849-8cf0eecb4c3f/clickhouse.go:105:13: config.Extra undefined (type *gdb.ConfigNode has no field or method Extra)
../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/v2@v2.0.0-20221018132849-8cf0eecb4c3f/clickhouse.go:106:49: config.Extra undefined (type *gdb.ConfigNode has no field or method Extra)
../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/v2@v2.0.0-20221018132849-8cf0eecb4c3f/clickhouse.go:146:21: undefined: gutil.GetOrDefaultStr

2022-10-20 02:35 UTC, DGuang21 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
> 我本地gf版本v2.1.2的，replace之后有报错。 ../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/[v2@v2.0.0-20221018132849-8cf0eecb4c3f](mailto:v2@v2.0.0-20221018132849-8cf0eecb4c3f)/clickhouse.go:105:13: config.Extra undefined (type *gdb.ConfigNode has no field or method Extra) ../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/[v2@v2.0.0-20221018132849-8cf0eecb4c3f](mailto:v2@v2.0.0-20221018132849-8cf0eecb4c3f)/clickhouse.go:106:49: config.Extra undefined (type *gdb.ConfigNode has no field or method Extra) ../../pkg/mod/github.com/!d!guang21/gf/contrib/drivers/clickhouse/[v2@v2.0.0-20221018132849-8cf0eecb4c3f](mailto:v2@v2.0.0-20221018132849-8cf0eecb4c3f)/clickhouse.go:146:21: undefined: gutil.GetOrDefaultStr

1. go mod 当中的gf 请使用最新的v2.2.1
2. 如果需要帮助，请勿将comment到此处，可在PR最底下发起评论，这里是review comment

2022-10-20 02:37 UTC, hd5723 commented on database/gdb/gdb.go
> +	LocalTypeBigInt      = "big-int"
我现在正常的replace:
replace github.com/ClickHouse/clickhouse-go/v2 => github.com/gogf/clickhouse-go/v2 v2.0.15-compatible

2022-10-26 11:02 UTC, houseme commented on cmd/gf/internal/cmd/gendao/gendao.go
> +		packageImportsArray.Append(`"github.com/shopspring/decimal"`)
这个decimal只是ch 使用吗?

2023-05-23 02:07 UTC, gqcn commented
@DGuang21 我看代码有冲突了麻烦再处理一下呢

2023-08-21 13:02 UTC, gqcn commented
Closed due to inactivity.

2023-08-21 13:02 UTC, closed without merging