attach and export real handler for request
gogf/gf pull request #2220
Opened 2022-10-18 08:05 UTC by SUDOCS

record user defined handler to request object before executing middlewares, which makes it possible to do something special according to the final target router in handler.

#2217

2022-10-25 11:41 UTC, gqcn requested changes

2022-10-25 11:41 UTC, gqcn commented on net/ghttp/ghttp.go
> +	HandlerParsedItem struct {
如果这个类型要对外开放，那么名称可以调整为`HandlerItemParsed`，与`HandlerItem`对应。

2022-10-27 10:37 UTC, SUDOCS commented on net/ghttp/ghttp.go
> +	HandlerParsedItem struct {
Thank you. I have renamed it to `HandlerParsedItem`.

2022-11-01 12:16 UTC, gqcn approved these changes

2022-11-01 12:17 UTC, merged