feat: improve golangci-lint action
gogf/gf pull request #2229
Opened 2022-10-22 16:40 UTC by houseme

2022-10-25 13:22 UTC, gqcn requested changes

2022-10-25 13:22 UTC, gqcn commented on internal/consts/consts.go
> +	CommaSpaceSeparator = ", "
- `CommaSpaceSeparator -> CommaSeparatorSpace`
- 如果不是多个组件共享的常量，请内聚到对应的组件中独立维护。例如这两个常量只是`gerror`组件使用，那么就放到`gerror`组件中定义和维护。

2022-10-25 13:22 UTC, gqcn commented on net/gclient/gclient_request.go
> +// Deprecated: use Post instead.
不能用`,`？

2022-10-25 13:22 UTC, gqcn commented on net/ghttp/ghttp_response_cors.go
> +		// err = gerror.WrapCodef(gcode.CodeInvalidParameter, err, `url.Parse failed for URL "%s"`, origin)
那就去掉吧。

2022-10-25 13:22 UTC, gqcn commented on net/gipv4/gipv4_ip.go
> +			// err = gerror.WrapCodef(gcode.CodeInvalidParameter, err, `strconv.ParseInt failed for string "%s"`, array[1])
那就去掉吧。

2022-10-25 13:22 UTC, gqcn commented on net/goai/goai.go
> +	return key == "-"
是不是应该`return key != "-"`

2022-10-25 13:22 UTC, gqcn commented on net/gudp/gudp_conn.go
> +	// return c.conn.RemoteAddr()
那就去掉吧。

2022-10-25 13:22 UTC, gqcn commented on os/gcache/gcache_adapter_memory.go
> +// and synchronize the results to the `expireTimes` and `expireSets` properties.
你把序号去掉了？

2022-10-25 13:22 UTC, gqcn commented on os/gres/gres_file.go
> +		// err = gerror.Wrapf(err, `open file failed for name "%s"`, f.Name())
那就去掉吧。

2022-10-25 13:22 UTC, gqcn commented on os/gres/gres_file.go
> +		// err = gerror.Wrapf(err, `read file content failed for name "%s"`, f.Name())
那就去掉吧。

2022-10-25 13:22 UTC, gqcn commented on os/gspath/gspath_cache.go
> +	// If it's a directory, it adds it's all sub files/directories recursively.
如果`its`报错，那么就改为`it adds all of its sub files/directories`或者`it adds all sub files/directories`吧。

2022-10-25 14:21 UTC, houseme commented on os/gspath/gspath_cache.go
> +	// If it's a directory, it adds it's all sub files/directories recursively.
done

2022-10-25 14:22 UTC, houseme commented on os/gres/gres_file.go
> +		// err = gerror.Wrapf(err, `open file failed for name "%s"`, f.Name())
done

2022-10-25 14:25 UTC, houseme commented on os/gcache/gcache_adapter_memory.go
> +// and synchronize the results to the `expireTimes` and `expireSets` properties.
只是整理了一下

2022-10-25 14:25 UTC, houseme commented on net/gudp/gudp_conn.go
> +	// return c.conn.RemoteAddr()
done

2022-10-25 14:38 UTC, houseme commented on database/gdb/gdb_model.go
> +//  1. Model names:
格式化的

2022-10-25 14:39 UTC, houseme commented on .golangci.yml
> +          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
等后续修改

2022-10-25 15:00 UTC, houseme commented on .golangci.yml
> -    - deadcode
done

2022-10-25 15:00 UTC, houseme commented on .golangci.yml
> +  skip-files: # 设置不需要检查的go源码文件，支持正则匹配
done

2022-10-26 13:24 UTC, gqcn requested changes

2022-10-26 13:24 UTC, gqcn commented on .golangci.yml
> +    keywords: # 建议设置为BUG、FIXME、OPTIMIZE、HACK
英文描述。

2022-10-27 05:26 UTC, houseme commented on net/gipv4/gipv4_ip.go
> +			// err = gerror.WrapCodef(gcode.CodeInvalidParameter, err, `strconv.ParseInt failed for string "%s"`, array[1])
done

2022-10-27 05:27 UTC, houseme commented on net/goai/goai.go
> +	return key == "-"
done

2022-10-27 05:31 UTC, houseme commented on net/gclient/gclient_request.go
> +// Deprecated: use Post instead.
https://studygolang.com/articles/4891

2022-10-27 05:37 UTC, houseme commented on internal/consts/consts.go
> +	CommaSpaceSeparator = ", "
其他地方的暂时没有替换了
```yaml
  goconst:
    # Minimal length of string constant.
    # Default: 3
    min-len: 2
    # Minimum occurrences of constant string count to trigger issue.
    # Default: 3
    # For subsequent optimization, the value is reduced.
    min-occurrences: 30
```

`min-occurrences` 这个值提高了。

2022-10-27 05:41 UTC, houseme commented on encoding/ghash/ghash_elf.go
> +	var x uint32
done

2022-10-27 05:47 UTC, houseme commented on database/gdb/gdb_model_insert.go
> +//	}).
done

2022-10-27 05:47 UTC, houseme commented on database/gdb/gdb_model_insert.go
> +//	}).
done

2022-10-27 05:57 UTC, houseme commented on net/ghttp/ghttp_response_cors.go
> +		// err = gerror.WrapCodef(gcode.CodeInvalidParameter, err, `url.Parse failed for URL "%s"`, origin)
done

2022-10-27 06:04 UTC, houseme commented on database/gdb/gdb_model_option.go
> +// Where("name", "").All()                -> SELECT xxx FROM xxx WHERE `name`=”
done

2022-10-27 06:05 UTC, houseme commented on database/gredis/gredis_redis_trace.go
> +	// }
暂时已还原，等大家讨论再处理

2022-10-27 11:24 UTC, gqcn approved these changes

2022-11-01 12:12 UTC, merged