feat: add `gcfg.Adapter` implements using nacos service
gogf/gf pull request #2232
Opened 2022-10-24 09:24 UTC by qinyuguang

2022-10-25 11:14 UTC, gqcn requested changes

2022-10-25 11:14 UTC, gqcn commented on contrib/config/nacos/go.mod
> +)
加一个`replace`语句，参开其他`Adapter`实现：
```go
replace github.com/gogf/gf/v2 => ../../../
```

2022-10-25 11:14 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +
请去掉无意义的空行。

2022-10-25 11:14 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +func (c *Client) doWatch() error {
我看你这个方法是在创建`Client`对象时的逻辑，修改名称为`addWatch`更合适一些？

2022-10-25 11:24 UTC, gqcn requested changes

2022-10-25 11:24 UTC, gqcn commented on .github/workflows/nacos/docker-compose.yml
> +    image: nacos/nacos-server:v2.1.2
改为`loads/nacos-server:v2.1.2`

2022-10-25 11:24 UTC, gqcn commented on .github/workflows/nacos/docker-compose.yml
> +    image: curlimages/curl:latest
改为`loads/curl:latest`

2022-10-25 11:24 UTC, gqcn commented on .github/workflows/nacos/image/mysql/Dockerfile
> +FROM mysql:5.7
改为`loads/mysql:5.7`

2022-10-25 11:30 UTC, gqcn requested changes

2022-10-25 11:30 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +	ConfigParam   vo.ConfigParam          `v:"required"` // See vo.ConfigParam
一个客户端配置需要配置`3`个对象属性，能简化吗？比如`ServerConfigs`看起来像是服务端配置，这个是必须的？

2022-10-25 15:11 UTC, qinyuguang commented on contrib/config/nacos/nacos.go
> +	ConfigParam   vo.ConfigParam          `v:"required"` // See vo.ConfigParam
是的，需要这三个，这三个结构中字段众多，所以直接用官方sdk里的结构而没有重新封一个Config

2022-10-26 10:44 UTC, gqcn approved these changes

2022-10-26 10:45 UTC, merged