zookeeper registry contrib
gogf/gf pull request #2284
Opened 2022-11-10 06:20 UTC by huyuanxin

2022-11-10 12:09 UTC, gqcn commented on contrib/registry/zookeeper/service.go
> +package zookeeper
请添加文件注释`copyright`，可以参考其他`registry`的源码。

2022-11-10 12:09 UTC, gqcn commented on contrib/registry/zookeeper/zookeeper.go
> +package zookeeper
- 请添加文件注释`copyright`，可以参考其他`registry`的源码。
- 请添加包说明注释。

2022-11-10 12:11 UTC, gqcn commented on contrib/registry/zookeeper/zookeeper_registrar.go
> +package zookeeper
请添加文件注释`copyright`，可以参考其他`registry`的源码。

2022-11-10 12:11 UTC, gqcn commented on contrib/registry/zookeeper/zookeeper_watcher.go
> +package zookeeper
请添加文件注释`copyright`，可以参考其他`registry`的源码。

2022-11-10 12:19 UTC, gqcn commented on contrib/registry/zookeeper/zookeeper_watcher.go
> +			// 每次 watch 只有一次有效期 所以循环 watch
源码中的注释请使用英文。

2022-11-10 12:22 UTC, gqcn commented
@huyuanxin 主要的问题点：
- 缺少完善注释，详见源码。
- 错误处理中的`error`直接从底层的`error`透传给上层，可能丢失堆栈信息，需要使用`gerror.Wrap/Wrapf`包裹，参考`etcd`的错误处理。
- 缺少`README.MD`文件，请参考其他`registry`的实现。

2022-11-11 00:16 UTC, huyuanxin commented on .github/workflows/gf.yml
> +        image: zookeeper
不使用官方镜像吗

2022-11-11 00:17 UTC, huyuanxin commented on .github/workflows/gf.yml
> +        image: zookeeper
我看了这个库四年前更新了3.4，昨天才更新的3.8

2022-11-12 03:09 UTC, gqcn requested changes

2022-11-12 03:09 UTC, gqcn commented on contrib/registry/zookeeper/zookeeper_registrar.go
> +	return err
这里注意一下`err`变量丢失了错误堆栈信息。框架的所有组件均需要保证在底层组件出错时，返回的`error`带有具体的错误定位。此外，如果底层操作产生了错误，可以多层`Wrap`都没问题的（不一定要在接口函数做`Wrap`），以能保证错误堆栈不丢失便于上层定位问题为目的。

2022-11-16 05:39 UTC, huyuanxin commented
@gqcn 大佬有时间看一看

2022-11-17 13:09 UTC, gqcn approved these changes

2022-11-17 13:09 UTC, gqcn commented on contrib/registry/zookeeper/README.MD
> +
缺少`Example`使用代码示例，具体请参考：https://github.com/gogf/gf/tree/master/contrib/registry/etcd

2022-11-18 06:06 UTC, gqcn approved these changes

2022-11-18 06:07 UTC, merged