add ut cases for package gcache
gogf/gf pull request #2341
Opened 2022-12-03 02:22 UTC by huangqian1985

2022-12-07 12:03 UTC, gqcn commented on os/gfile/gfile_z_unit_test.go
> +
Missing something?

2022-12-07 13:34 UTC, huangqian1985 commented on os/gfile/gfile_z_unit_test.go
> +
应该是想写的, 结果发现不好写. 已经删了.

2022-12-12 02:30 UTC, gqcn requested changes

2022-12-12 02:30 UTC, gqcn commented on os/gfile/gfile_z_unit_test.go
> +		fileobj, err := gfile.Create("./testdata/test/testfile_cc1.txt")
临时文件请创建到`gfile.Temp(xxx)`

2022-12-20 06:49 UTC, gqcn approved these changes

2022-12-20 06:49 UTC, merged