由于 clickhouse 的 position的初始值为 1，导致gdb_core_utility.HasField 中对 fieldsArray 初始化出错
gogf/gf pull request #2346
Opened 2022-12-05 04:18 UTC by qq375251855

由于 clickhouse 的 position的初始值为 1，导致gdb_core_utility.HasField 中对 fieldsArray 初始化出错

2022-12-05 11:38 UTC, gqcn commented
@qq375251855 CI failed.

2022-12-08 07:01 UTC, houseme commented
@DGuang21 辛苦看下

2022-12-08 09:16 UTC, DGuang21 commented
> @houseme 这个地方麻烦看下，我是从修复报错的角度出发的，不知道是否违背了你使用position的初衷

如果是影响到了```gdb_core_utility.HasField```，请补充一下对应的测试用例。需要覆盖错误及正确的情况~

2022-12-09 00:43 UTC, qq375251855 commented
> > @houseme 这个地方麻烦看下，我是从修复报错的角度出发的，不知道是否违背了你使用position的初衷
> 
> 如果是影响到了`gdb_core_utility.HasField`，请补充一下对应的测试用例。需要覆盖错误及正确的情况~

好的，明白

2022-12-09 04:27 UTC, houseme approved these changes

2022-12-11 15:14 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> +			Index:   m["position"].Int() - 1,
从防御性代码的角度上来讲，此处建议先提前判断一下值是否为 0，否则如果底层发生了改变导致 Position 从 0 开始，可能会对此处造成意料之外的结果。

2022-12-12 01:34 UTC, qq375251855 commented on contrib/drivers/clickhouse/clickhouse.go
> +			Index:   m["position"].Int() - 1,
好的，明白

2022-12-12 03:05 UTC, DGuang21 requested changes

2022-12-12 03:05 UTC, DGuang21 commented on contrib/drivers/clickhouse/clickhouse.go
> +		if result[0]["position"].Int() != 0 {
此处逻辑有误，如果这是一个空表没有字段，返回出来的 result 长度将会为 0，此时获取下标[0]将会发生 panic。

故应当在循环前添加判断
```
 overZero := len(result) > 0 && result[0] > 0
```
循环中的判断即可为
```
if overZero {
  position -= 1
}
```

2022-12-12 05:36 UTC, DGuang21 approved these changes

2022-12-22 09:00 UTC, merged