feat: 从标准路由in标签所指定的方式读取参数值
gogf/gf pull request #2450
Opened 2023-02-14 11:54 UTC by hailaz

https://github.com/gogf/gf/issues/2060

2023-02-15 01:53 UTC, gqcn requested changes

2023-02-15 01:53 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +	tagFields, err := gstructs.TagFields(pointer, []string{"in"})
`gstructs.TagFields`这个方法的执行效率很低，不太适合放到接受API请求参数。建议是在路由注册时就将`in`标签的内容读取出来存储到某个地方，在接受请求参数时直接拿来用，效率会很高。可以沿着这方面思考下。

2023-02-15 03:16 UTC, hailaz commented on net/ghttp/ghttp_request_param_request.go
> +	tagFields, err := gstructs.TagFields(pointer, []string{"in"})
我也觉得，上面的默认值也是如此。应该在把需要解析的在启动的时候缓存好。

2023-02-16 02:07 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +	tagFields, err := gstructs.TagFields(pointer, []string{"in"})
@hailaz 确实，默认值也可以这么改进下。

2023-02-16 02:20 UTC, gqcn requested changes

2023-02-16 02:20 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +	tagFields, err := gstructs.TagFields(pointer, []string{"in"})
@hailaz 要不咱们先完善功能，后续改进的内容你加个TODO项记录在这三个调用`gstructs.TagFields`的方法前面，我们后续找个时间来改进。我先评论你这个逻辑的内部实现。

2023-02-16 02:20 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +				if v := r.GetHeader(fieldKey); v != "" {
能否将`Header`的内容全部读取出来之后，统一通过`gutil.MapPossibleItemByKey`来判断键值是否存在？

2023-02-16 02:20 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +				if v := r.Cookie.Get(fieldKey); !v.IsEmpty() {
能否不对键名进行小写转换，直接将`Cookie`的内容全部读取出来之后，统一通过`gutil.MapPossibleItemByKey`来判断键值是否存在？

2023-02-16 02:20 UTC, gqcn commented on net/ghttp/ghttp_request_param_request.go
> +}
- 涉及到字符串硬编码的地方建议修改为内部常量。
- 缺少对应的单元测试，难以评估改动点是否满足功能。

2023-02-16 02:28 UTC, hailaz commented on net/ghttp/ghttp_request_param_request.go
> +	tagFields, err := gstructs.TagFields(pointer, []string{"in"})
把单元测试性能测试也写好，到时候可以对比性能。

2023-02-21 07:00 UTC, hailaz commented
@gqcn 反射的版本已经改好了

2023-03-02 06:14 UTC, gqcn approved these changes

2023-03-13 11:29 UTC, merged