fix: unified go.mod dependent version
gogf/gf pull request #2452
Opened 2023-02-15 09:18 UTC by hailaz

新增一个脚本，统一更新库内依赖版本，使得github依赖分析更加准确。
https://github.com/gogf/gf/network/dependencies

2023-02-20 13:55 UTC, gqcn requested changes

2023-02-20 13:55 UTC, gqcn commented on update_go.mod.sh
> +done
建议统一维护到`Makefile`中，参考`tidy`的实现方式。

2023-02-21 02:12 UTC, hailaz commented on update_go.mod.sh
> +done
好

2023-02-21 06:55 UTC, hailaz commented
@gqcn 改好了

2023-02-23 02:01 UTC, gqcn commented
@hailaz 没看出来这样改动的意义呢？所有的`go.mod`后续需要随时地更新维护吗？

2023-02-27 14:14 UTC, gqcn commented
@hailaz 看起来用处不是很大，反而需要增加一条Makefile指令，也会涉及到长期维护。我建议不做修改。

2023-03-21 09:48 UTC, hailaz commented
如果不保持更新，单独引入驱动使用的时候会报错无法启动

![image](https://user-images.githubusercontent.com/29968474/226570199-0bb78961-fd3a-4a6b-8a88-ac2a5042abba.png)

2023-03-28 01:25 UTC, gqcn approved these changes

2023-03-28 01:25 UTC, merged