feat: support graceful shutdown (#2469)
gogf/gf pull request #2475
Opened 2023-02-25 15:55 UTC by windvalley

Optimize the code to support graceful shutdown, and add configuration `server.shutdownGracefulTimeout` to allow users to customize the timeout, the default value is `5`(seconds).

2023-03-01 01:59 UTC, gqcn requested changes

2023-03-01 01:59 UTC, gqcn commented on net/ghttp/ghttp_server.go
> +
为什么要修改这里呢？

2023-03-01 01:59 UTC, gqcn commented on net/ghttp/ghttp.go
> -	gracefulShutdownTimeout     = 5 * time.Second
为什么要删除该常量？

2023-03-01 01:59 UTC, gqcn commented on net/ghttp/ghttp_server_config.go
> +		GracefulShutdownTimeout: 5, // seconds
请保持统一的时间格式配置。

2023-03-01 03:32 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
您好, 我的理解是: 
应该使用处理优雅关闭的代码逻辑来阻塞程序, 因为官方的Shutdown函数在执行后会先关闭端口监听使不再接收新请求, 再等待正在进行中的请求处理完后退出整个程序.  如果使用端口监听来阻塞程序, Shutdown运行后整个进程就直接退出了, 无法进行后续的优雅关闭逻辑的处理.

2023-03-01 03:34 UTC, windvalley commented on net/ghttp/ghttp.go
> -	gracefulShutdownTimeout     = 5 * time.Second
删除这个常量是为了和项目已有的优雅关闭的处理方式保持一致.

2023-03-01 03:35 UTC, windvalley commented on net/ghttp/ghttp_server_config.go
> +		GracefulShutdownTimeout: 5, // seconds
您好, 这里我只加了一条`GracefulShutdownTimeout: 5, // seconds`, 是为了和项目已有的`GracefulTimeout:         2, // seconds`保持一致.

2023-03-02 02:10 UTC, gqcn requested changes

2023-03-02 02:10 UTC, gqcn commented on net/ghttp/ghttp_server.go
> +
你好，这里的`handleProcessSignal`方法调用是在`serverProcessInit`方法中，该方法用于进程初始化，并不需要阻塞的作用。
我看了你的修改，只是增加了优雅退出的等待时间配置，并没有修改退出逻辑。我建议增加优雅退出的单元测试以判断你的修改是否有效。此外，`goframe server`引起的进程退出逻辑在这里：
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/26347176/222312667-6f9aadb3-7296-4976-80d1-c3c3313a4c50.png">

2023-03-02 02:25 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
goframe server引起的进程退出逻辑我之前看了, 本质上还是通过server端口监听来实现的阻塞(虽然表面是通过chan阻塞), 只是所有server实例监听被关闭后, 会向chan发信号, 从而chan退出阻塞. 没有给Shutdown函数继续执行的机会, 因为server监听在主goroutine中, 而Shutdown函数在子goroutine中, 主退出了, 子也就直接退出了. 所以修正逻辑就是将Shutdown房东主goroutine中, 控制阻塞.

2023-03-02 06:06 UTC, gqcn requested changes

2023-03-02 06:06 UTC, gqcn commented on net/ghttp/ghttp_server.go
> +
@windvalley 你好，只有所有的`server shutdown`之后进程才会退出，而`shutdown`方法我理解目前是带有优雅退出逻辑的，因为我理解只有所有请求执行完成`shutdown`函数才会返回。
而`goframe server`的阻塞逻辑是使用的`Serve`方法实现阻塞的，是否这个`Serve`方法并没有关心优雅退出，而是`listener`一退出就返回？
这两块逻辑的细节我建议你可以梳理一下，只有了解细节才好做优化。

2023-03-02 07:01 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
@gqcn  `"net/http".Server.Serve`方法本身不关心优雅退出, 关闭就会返回,  关心优雅退出的是`"net/http".Server.Shutdown`方法, 该方法首先会通过`lnerr := srv.closeListenersLocked(); srv.closeDoneChanLocked()`关闭server的所有监听(不再阻塞, 按gf框架目前的写法, 到这里整个进程就退出了), 然后处理设置的回调(如果设置了的话), 最后通过`for+select+chan`阻塞, 等待所有请求处理完或超时就退出程序.

2023-03-03 01:57 UTC, gqcn requested changes

2023-03-03 01:57 UTC, gqcn commented on net/ghttp/ghttp_server.go
> +
@windvalley 嗯，看样子跟我猜测的一样。那你可以尝试着提个pr改进下呢？

2023-03-03 04:48 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
@gqcn 好的, 我试着进一步优化一下

2023-03-03 05:20 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
@gqcn 我将`handleProcessSignal()` 从 Start函数移到了Run函数, 避免阻塞Start函数导致现有包含Start的单元测试因为阻塞无法执行.

2023-03-03 05:23 UTC, windvalley commented on net/ghttp/ghttp_server.go
>  	<-s.closeChan
@gqcn 这里的阻塞逻辑对优雅重启起作用, 也不影响优雅关闭, 所以需要保留.

2023-03-03 05:44 UTC, windvalley commented on net/ghttp/ghttp_server.go
> +
@gqcn 您好, 已增加了针对优雅关闭功能的单元测试.

2023-03-13 11:21 UTC, gqcn approved these changes

2023-03-13 11:21 UTC, merged