improve unit testing cases
gogf/gf pull request #2480
Opened 2023-02-28 05:25 UTC by hailaz

2023-02-28 13:51 UTC, gqcn requested changes

2023-02-28 13:51 UTC, gqcn commented on text/gstr/gstr_parse.go
> -			key = key[1:]
为什么要修改这里呢?

2023-03-01 02:38 UTC, hailaz commented on text/gstr/gstr_parse.go
> -			key = key[1:]
不改会panic

2023-03-02 02:19 UTC, gqcn requested changes

2023-03-02 02:19 UTC, gqcn commented on text/gstr/gstr_parse.go
> -			key = key[1:]
如果这样的话是否改为这样更合适？
```go
for len(key) > 0 && key[0] == ' ' {
	key = key[1:]
}
```

2023-03-07 13:27 UTC, gqcn approved these changes

2023-03-07 13:27 UTC, merged