fix: cli gen service:BUG #2310
gogf/gf pull request #2485
Opened 2023-03-02 08:44 UTC by sanrentai

2023-03-03 02:08 UTC, gqcn requested changes

2023-03-03 02:08 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice.go
> +			fileContent, err := gregex.ReplaceString("/(.*)\n", "", fileContent)
这里的正则是否使用`//(.*)`更合适？

2023-03-03 02:08 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice_calculate.go
> +	matches, err := gregex.MatchAllString(`func \((.+?)\) ([\s\S]+?) {`, fileContent)
这里不需要修改吧？

2023-03-03 05:07 UTC, sanrentai commented on cmd/gf/internal/cmd/genservice/genservice_calculate.go
> +	matches, err := gregex.MatchAllString(`func \((.+?)\) ([\s\S]+?) {`, fileContent)
不需要改，之前改了忘改回来了

2023-03-13 11:17 UTC, gqcn approved these changes

2023-03-13 11:17 UTC, merged