update default logging time format using SetTimeFormat
gogf/gf pull request #2611
Opened 2023-04-27 11:43 UTC by mason51

https://github.com/gogf/gf/pull/2583

```yaml
logger:
  level: "DEBUG"
  stdout: true
  timeFormat: "2006-01-02T15:04:05Z07:00"
```

2023-05-08 12:52 UTC, gqcn requested changes

2023-05-08 12:52 UTC, gqcn commented on os/glog/glog_z_unit_test.go
> +	})
- 在单测中不要修改全局的`Logger`，你可以创建一个`Logger`然后调用`SetTimeFormat`。
- 此外，你需要写入一段日志，获取日志内容判断是否打印的时间格式符合预期。可以使用自定义`Writer`，请参考已有单例实现。

2023-05-19 05:37 UTC, mason51 commented on os/glog/glog_z_unit_test.go
> +	})
@gqcn , 修改了单元测试, 再看看

2023-05-23 12:59 UTC, gqcn approved these changes

2023-05-23 12:59 UTC, merged