feat: Add method ScanAndCount and AllAndCount
gogf/gf pull request #2635
Opened 2023-05-09 06:23 UTC by lusson-luo

feat: 添加方法两个 ScanAndCount, AllAndCount.

2023-05-09 06:43 UTC, houseme commented on database/gdb/gdb_model_select.go
> +	count, err = m.Count(where)
是不是应该先查询是否有数据，如果count 没有数据，就可以直接返回了，下面的也一样，先处理 count

2023-05-09 06:48 UTC, houseme commented on database/gdb/gdb_model_select.go
> +func (m *Model) ScanAndCount(pointer interface{}, pointerCount *int, where ...interface{}) error {
这个 count 的值返回指针的目标是什么呢？以及是不是应该先判断当前条件的可以查询到数据的条数，再去具体查询数据。

2023-05-09 06:49 UTC, houseme reviewed
建议补上对应的单元测试代码

2023-05-09 06:57 UTC, lusson-luo commented on database/gdb/gdb_model_select.go
> +	count, err = m.Count(where)
嗯嗯，先处理 count 了

2023-05-09 06:59 UTC, lusson-luo commented on database/gdb/gdb_model_select.go
> +func (m *Model) ScanAndCount(pointer interface{}, pointerCount *int, where ...interface{}) error {
count 指针是参数，不是返回，作用是参数传入一个 count 指针，方法执行后给改指针赋值

2023-05-09 07:01 UTC, lusson-luo commented on database/gdb/gdb_model_select.go
> +func (m *Model) ScanAndCount(pointer interface{}, pointerCount *int, where ...interface{}) error {
因为 Scan 方法就是通过传 stuct 指针实现赋值，所以 count 我也通过指针来赋值

2023-05-09 07:02 UTC, lusson-luo commented
> 建议补上对应的单元测试代码

单元测试有例子吗，我看 Scan 和 All 之前没有单元测试，担心 orm 依赖数据库，可以不依赖数据库写单元测试吗？

2023-05-09 07:39 UTC, houseme commented
> > 建议补上对应的单元测试代码
> 
> 单元测试有例子吗，我看 Scan 和 All 之前没有单元测试，担心 orm 依赖数据库，可以不依赖数据库写单元测试吗？

有安装 mysql 的数据库的，你直接模拟先写书 20 条，在按照条件去查询就可以了

2023-05-09 12:38 UTC, lusson-luo commented on database/gdb/gdb_model_select.go
> +func (m *Model) ScanAndCount(pointer interface{}, pointerCount *int, where ...interface{}) error {
ScanAndAll 有两种写法，一种将 count 以指针形式放到参数修改，一种放到返回值修改，目前采用第二种
<img width="1223" alt="image" src="https://github.com/gogf/gf/assets/19859400/ad198839-0736-4b38-8b10-e0ccb3a48fc3">
![image](https://github.com/gogf/gf/assets/19859400/b0e4dcc2-64d5-40af-b7e7-0660cab12822)

2023-05-09 12:39 UTC, lusson-luo commented
> > > 建议补上对应的单元测试代码
> > 
> > 
> > 单元测试有例子吗，我看 Scan 和 All 之前没有单元测试，担心 orm 依赖数据库，可以不依赖数据库写单元测试吗？
> 
> 有安装 mysql 的数据库的，你直接模拟先写书 20 条，在按照条件去查询就可以了

在 sqlite 上补充单元测试代码

2023-05-10 06:51 UTC, houseme approved these changes

2023-05-11 02:37 UTC, lusson-luo commented
@gqcn 大佬审核下 pr

2023-05-11 12:27 UTC, gqcn commented on contrib/drivers/sqlite/sqlite_model_test.go
> +}
请增加以下两条Case:
- 带有`Page`分页。
- 带有正常数据返回的查询。

2023-05-11 12:27 UTC, gqcn commented on contrib/drivers/sqlite/sqlite_model_test.go
> +func Test_Model_ScanAndCount(t *testing.T) {
请增加以下两条Case:
- 带有`Page`分页。
- 带有正常数据返回的查询。

2023-05-11 12:33 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +func (m *Model) ScanAndCount(pointer interface{}, where ...interface{}) (count int, err error) {
方法需要定义为`ScanAndCount(pointer interface{}, count *int) (err error)`

2023-05-12 02:20 UTC, gqcn commented
@lusson-luo The feature is awesome, but the CI failed, please have a check.

2023-05-15 03:45 UTC, lusson-luo commented
> @lusson-luo The feature is awesome, but the CI failed, please have a check.



> @lusson-luo The feature is awesome, but the CI failed, please have a check.

@gqcn  ok, i finish ci failed

2023-05-17 02:36 UTC, lusson-luo commented
@gqcn 大佬审核下 pr

2023-05-22 13:09 UTC, gqcn requested changes

2023-05-29 12:34 UTC, gqcn commented
@lusson-luo I'm watching this.

2023-05-29 12:37 UTC, lusson-luo commented
> @lusson-luo I'm watching this.

ok

2023-05-29 12:38 UTC, lusson-luo commented
@gqcn 嗯嗯，上面的问题我都答复了，我认为 count(1) 可能比 count(filed) 更适合一点，理由也在上面

2023-06-01 13:30 UTC, gqcn requested changes

2023-06-01 13:33 UTC, gqcn approved these changes

2023-06-01 13:33 UTC, merged