doc: 修复Charset注释描述
gogf/gf pull request #2649
Opened 2023-05-17 01:57 UTC by hailaz

2023-05-22 14:19 UTC, gqcn requested changes

2023-05-22 14:19 UTC, gqcn commented on contrib/drivers/mysql/mysql.go
> +		// TODO: Do not set charset when charset is not specified (in v2.5.0)
我觉得你这里可以直接加上`if`判断，如果`config.Charset`有值才加上`?charset=`

2023-05-24 02:10 UTC, hailaz commented on contrib/drivers/mysql/mysql.go
> +		// TODO: Do not set charset when charset is not specified (in v2.5.0)
这里判断没用，在这之前Charset已经被改动了 @gqcn

2023-05-25 14:00 UTC, gqcn approved these changes

2023-05-25 14:00 UTC, merged