ORM字段类型自定义转换
gogf/gf pull request #2656
Opened 2023-05-19 03:31 UTC by LonelySally

2023-05-25 01:47 UTC, hailaz approved these changes

2023-05-29 12:57 UTC, gqcn requested changes

2023-05-29 12:57 UTC, gqcn commented on database/gdb/gdb_func.go
> +type checkLocalTypeForFieldFunc func(ctx context.Context, typeName, typePattern, fieldType string, fieldValue interface{}) (string, error)
建议去掉自定义类型名称检测方法的设计，而是在CLI工具中预定义转换，不在基础组件中开放这个特性。

2023-05-29 12:57 UTC, gqcn commented on cmd/gf/internal/cmd/gendao/gendao.go
> +			gdb.RegistCheckLocalTypeForField(typeName, func(ctx context.Context, typeName, typePattern, fieldType string, fieldValue interface{}) (string, error) {
去掉自定义函数的设计，直接在这里进行类型转换，使用用户配置的数据类型而不是基础组件预定义的数据类型。

2023-06-05 03:20 UTC, LonelySally commented
关于全局注册CheckLocalTypeForField的讨论记录.
1. 当前框架可以通过注册私有驱动,通过重写ConvertValueForLocal方法来实现类型的替换. 入口固定易于管理,实现成本较高,需要私有驱动编码+配置.
2. 通过对gdb注册的方式在Core的ConvertValueForLocal方法内执行匹配强制返回用户声明类型. 入口为方法调用(类似gdb.Register),灵活度高但无法限制调用者,使用成本低,同协议的不同数据库接入不需要额外编码.

2023-06-05 04:16 UTC, hinego commented
可以看看 我实现的方案 你这个方案似乎改动不少啊

https://github.com/gogf/gf/pull/2686

2023-06-05 04:39 UTC, hinego commented
看完了你的pr emmm 感觉这种尽量一次到位比较好

commit次数太多了 看起来很多

我们方案的差别：
```
	case
		fieldTypeDecimal,
		fieldTypeMoney,
		fieldTypeNumeric,
		fieldTypeSmallmoney:
		return LocalTypeString, nil
```

这里其实只有 `fieldTypeDecimal`和`fieldTypeNumeric`需要转成string其他的float64是可以的（分别是8字节和4字节 而float64是8字节）

自定义类型时似乎没有考虑到引入第三方库，如果引入第三方库需要import

2023-06-05 05:14 UTC, LonelySally commented
> 看完了你的pr emmm 感觉这种尽量一次到位比较好
> 
> commit次数太多了 看起来很多
> 
> 我们方案的差别：
> 
> ```
> 	case
> 		fieldTypeDecimal,
> 		fieldTypeMoney,
> 		fieldTypeNumeric,
> 		fieldTypeSmallmoney:
> 		return LocalTypeString, nil
> ```
> 
> 这里其实只有 `fieldTypeDecimal`和`fieldTypeNumeric`需要转成string其他的float64是可以的（分别是8字节和4字节 而float64是8字节）
> 
> 自定义类型时似乎没有考虑到引入第三方库，如果引入第三方库需要import

这个pr的commit历史实际上是社区成员的讨论历史,有记录性质,因此并没有重新提写pr.
关于两个money类型本质定义同为高精度因此归为一组.
关于第三方包,初考虑为由用户自定义type后手动引用.即
code:
type Decimal decimal.Decimal 

config:
typeMapping:
  decimal: "Decimal"

若有兴趣加入社区共建可以找强哥进群.

2023-06-05 05:50 UTC, LonelySally commented
> 看完了你的pr emmm 感觉这种尽量一次到位比较好
> 
> commit次数太多了 看起来很多
> 
> 我们方案的差别：
> 
> ```
> 	case
> 		fieldTypeDecimal,
> 		fieldTypeMoney,
> 		fieldTypeNumeric,
> 		fieldTypeSmallmoney:
> 		return LocalTypeString, nil
> ```
> 
> 这里其实只有 `fieldTypeDecimal`和`fieldTypeNumeric`需要转成string其他的float64是可以的（分别是8字节和4字节 而float64是8字节）
> 
> 自定义类型时似乎没有考虑到引入第三方库，如果引入第三方库需要import

这个pr的commit历史实际上是社区成员的讨论历史,有记录性质,因此并没有重新提写pr(最初是想解决底层数据类型与本地类型关系的定义,gen dao的功能实质是属于衍生行为).
关于两个money类型本质定义同为高精度因此归为一组.
关于第三方包,初考虑为由用户自定义后手动引用类型名称(尚在讨论).你的实现也是一种解决方案,再需要考虑mod不存在包的情况的额外处理会更完善.
若有兴趣加入社区共建可以找强哥进群.

2023-06-06 08:05 UTC, gqcn requested changes

2023-06-07 04:31 UTC, LonelySally commented
引入import
`
gfcli:
  gen:
    dao:
      - link: ""
        typeMapping:
          decimal:
            local: "decimal.Decimal" # 自定义类型
            import: "github.com/shopspring/decimal" # 配置不为空时强制校验go.mod是否存在该包
`

2023-06-27 13:49 UTC, gqcn commented
@LonelySally @hinego 我从源分支新开了一个分支，并提交到了 https://github.com/gogf/gf/pull/2722

2023-06-27 13:49 UTC, closed without merging