add redis-config Auth Username
gogf/gf pull request #2684
Opened 2023-06-03 01:45 UTC by wanov

2023-06-06 13:01 UTC, gqcn commented
@wanov 你好，感谢参与贡献，请提交对应修改的单元测试。

2023-06-08 07:22 UTC, wanov reviewed
add test

2023-06-27 12:48 UTC, gqcn commented
@wanov 你好，你的单例执行失败了，应该是和当前项目的CI中的redis server不对应，请参考已有代码改进一下呢。

2023-06-28 06:05 UTC, wanov reviewed
人生首次PR，太刺激了~

2023-06-29 12:22 UTC, gqcn requested changes

2023-06-29 12:22 UTC, gqcn commented on contrib/nosql/redis/redis_z_unit_config_test.go
> +			Pass:    "isBest!1",
不要使用公网的服务地址，使用`CI`中的`redis`服务，你参考已有单测代码实现呢？

2023-07-04 08:38 UTC, wanov commented
已删除

2023-07-04 11:54 UTC, gqcn requested changes

2023-07-04 11:54 UTC, gqcn commented on contrib/nosql/redis/redis_z_unit_config_test.go
> +	})
你好，你的单例中并没有覆盖使用用户登录时执行指令的逻辑，例如简单的KV操作即可。

2023-07-04 13:18 UTC, wanov commented on contrib/nosql/redis/redis_z_unit_config_test.go
> +	})
好的 已经添加

2023-07-06 12:58 UTC, merged