gf gen service will automatically generate New and service.RegisterUser(New()) codes
gogf/gf pull request #2691
Opened 2023-06-07 02:32 UTC by hinego

automatically generate init.gen.go file for service logic register.

implement：https://github.com/gogf/gf/issues/2674

In default it will automatically generate init.gen.go file like:
```
// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package xxxx

import "xxxxx/service"

func NewDest() service.IDest {
	return &sDest{}
}
func NewUser() service.IUser {
	return &sUser{}
}
func init() {

	service.RegisterDest(NewDest())
	service.RegisterUser(NewUser())
}
```
If the developer's code already contains `registerXxx`, it will be ignored, and only unregistered Logic will be automatically registered

2023-06-12 12:28 UTC, gqcn requested changes

2023-06-12 14:42 UTC, hinego commented on cmd/gf/internal/cmd/genservice/genservice_generate.go
> +	return gfile.PutContents(gfile.Join(in.SrcFolderPath, "init.gen.go"), generatedCode.String())
搞定了

2023-06-12 15:28 UTC, hinego commented on cmd/gf/internal/cmd/genservice/genservice_generate.go
> +	return gfile.PutContents(gfile.Join(in.SrcFolderPath, "init.gen.go"), generatedCode.String())
> `init.gen.go`是否修改为`报名.init.go`更合适？`go`语言里面对`gen`并没有什么特殊特性，`goframe`框架也没有这样的风格。

有一个问题 为什么`cmd/gf/internal/cmd/genservice/genservice_generate.go`会有 
```
		generatingInterfaceCheck = fmt.Sprintf(`[^\w\d]+%s.I%s[^\w\d]`, in.DstPackageName, structName)
		if gregex.IsMatchString(generatingInterfaceCheck, generatedContent) {
			continue
		}
```

这一段代码？这使得service代码的interface中无法存在类似这样的代码：
即某些情况可能需要New一下自己 
````
	type IBlock interface {
		New(ID int64) (block IBlock)
       }
```

只要出现返回值是 Interface 名称的 就会导致下面的代码无法成功生成（会被略过）

```
var (
	localBlock IBlock
)

func Block() IBlock {
	if localBlock == nil {
		panic("implement not found for interface IBlock, forgot register?")
	}
	return localBlock
}

func RegisterBlock(i IBlock) {
	localBlock = i
}

```

2023-06-27 12:50 UTC, gqcn commented
@hinego 有个疑问，什么时候会触发`xxx.init.go`文件的生成？我发现目前的代码生成触发不了使用。

2023-06-30 09:18 UTC, hinego commented
> @hinego 有个疑问，什么时候会触发`xxx.init.go`文件的生成？我发现目前的代码生成触发不了使用。

如果开发者已经写了注册了就不会生成了

2023-07-04 12:22 UTC, closed without merging