feat: Using sqlite CGO is for building a 32-bit Windows operating system
gogf/gf pull request #2743
Opened 2023-07-05 14:48 UTC by horizon220222

#### Why do we need to use github.com/gogf/gf/contrib/drivers/sqlite/cgo?

Using sqlite CGO is for building a 32-bit Windows operating system

https://github.com/glebarez/go-sqlite does not support building a  32-bit Windows operating system.

#### sqlite

【using CGO】github.com/mattn/go-sqlite3
【not using CGO】https://github.com/glebarez/go-sqlite

#### goframe driver

[using CGO]github.com/gogf/gf/contrib/drivers/sqlite/cgo
[not using CGO]github.com/gogf/gf/contrib/drivers/sqlite/v2

2023-07-06 06:10 UTC, horizon220222 commented
You need to set the environment variable CGO_ENABLED=1 and make sure that GCC is installed on your path.

windows: https://jmeubank.github.io/tdm-gcc/

2023-07-06 11:44 UTC, gqcn commented
@horizon220222 CI失败了，可以参考已有的CI脚本是怎么写的 https://github.com/gogf/gf/blob/master/.github/workflows/build_and_test.sh
<img width="1408" alt="image" src="https://github.com/gogf/gf/assets/26347176/19f91858-afae-495f-8f68-dcf6c2fb93ba">

2023-07-07 02:47 UTC, horizon220222 commented
I will take care of it over the weekend.

2023-07-09 05:08 UTC, horizon220222 commented
![20230709130705](https://github.com/gogf/gf/assets/23274077/5dbde16f-d0a4-4e75-83a4-2445cda947f5)

fix: building errors 1.15 and 1.16 (undefined: math.MaxInt)

2023-07-19 14:09 UTC, gqcn requested changes

2023-07-29 12:53 UTC, horizon220222 commented
最近比较忙，已经修改

2023-08-01 13:20 UTC, gqcn requested changes

2023-08-01 13:20 UTC, gqcn commented on contrib/drivers/sqlitecgo/sqlite.go
> +package sqlitecgo
缺少包注释描述，可以参考下其他`driver`包怎么写的包注释描述哈。

2023-08-01 13:24 UTC, gqcn commented on contrib/drivers/sqlitecgo/sqlite.go
> +// 1. It needs manually import: _ "https://github.com/mattn/go-sglite3"
@horizon220222 只是去掉这一行的注释，因为注释是错误的。

2023-08-02 16:09 UTC, horizon220222 commented on contrib/drivers/sqlitecgo/sqlite.go
> +package sqlitecgo
哈哈哈 注释确实没写啊 我补充下

2023-08-03 11:58 UTC, gqcn approved these changes

2023-08-03 11:58 UTC, merged