fix: 格式化输出前校验有效性
gogf/gf pull request #2755
Opened 2023-07-11 05:50 UTC by LonelySally

2023-07-11 06:06 UTC, LonelySally commented
关于StrToTime方法中匹配正则改成(\d{4})[-/\.](\d{1,2})[-/\.](\d{1,2})直接获取年月日匹配结果?

2023-07-11 11:48 UTC, gqcn requested changes

2023-07-11 11:48 UTC, gqcn commented on os/gtime/gtime_z_unit_time_test.go
> +	// 非常规的类型
代码中的注释请使用英文

2023-07-11 11:49 UTC, gqcn commented
> 关于StrToTime方法中匹配正则改成
> 
> ```
> (\d{4})[-/\.](\d{1,2})[-/\.](\d{1,2})
> ```
> 
> 直接获取年月日匹配结果?

不建议支持这种。

2023-07-19 13:11 UTC, gqcn approved these changes

2023-07-19 13:11 UTC, merged