remove replace directives in cmd/gf/go.mod
gogf/gf pull request #2797
Opened 2023-07-22 10:38 UTC by wsy998

Removed the 'replace' directives in cmd/gf/go.mod to enable users to install gf-cli using 'go install' method.

2023-07-22 10:55 UTC, wsy998 commented
Using 'go install' is more user-friendly for users in China. This allows them to set up a proxy using 'goproxy' and then proceed with downloading and installing 'gf-cli' using 'go install'.

2023-07-25 13:39 UTC, gqcn approved these changes

2023-07-25 13:46 UTC, gqcn requested changes

2023-07-25 13:46 UTC, gqcn commented on cmd/gf/go.mod
> -)
当发布新版本时，`cmd/gf`依赖本地库的版本管理会有一些问题，会报找不到库，所以目前不建议这么修改，直接下载`release`也挺好的。

2023-07-25 13:46 UTC, closed without merging