fix: disable map tag `summary` and `description` from the OpenAPI `Operation` to `PathItem`
gogf/gf pull request #2823
Opened 2023-08-01 06:58 UTC by WankkoRee

因为当前 tag 都是针对 Operation 对象设置的，不应该将 Operation 的 summary 和 description 直接添加到 PathItem 。

如存在`POST /user`的 summary 为`新增用户`，存在`DELETE /user`的 summary 为`删除用户`，两者为相反操作，其 PathItem 的 summary 应当留空而不是使用其中一个。

实际测试：

```golang
package main

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type HelloReq struct {
	g.Meta `path:"/hello" method:"get" sm:"sm" dc:"dc"`
	Name   string `v:"required" dc:"Your name"`
}
type HelloRes struct {
	Reply string `dc:"Reply content"`
}

type Hello struct{}

func (Hello) Say(ctx context.Context, req *HelloReq) (res *HelloRes, err error) {
	g.Log().Debugf(ctx, `receive say: %+v`, req)
	res = &HelloRes{
		Reply: fmt.Sprintf(`Hi %s`, req.Name),
	}
	return
}

func main() {
	s := g.Server()
	s.Use(ghttp.MiddlewareHandlerResponse)
	s.Group("/", func(group *ghttp.RouterGroup) {
		group.Bind(
			new(Hello),
		)
	})
	s.Run()
}
```

```diff
{
    "openapi": "3.0.0",
    "components": {
        "schemas": {
            "main.HelloReq": {
                "description": "dc",
                "properties": {
                    "Name": {
                        "description": "Your name",
                        "format": "string",
                        "properties": {},
                        "type": "string"
                    }
                },
                "required": [
                    "Name"
                ],
                "type": "object"
            },
            "main.HelloRes": {
                "properties": {
                    "Reply": {
                        "description": "Reply content",
                        "format": "string",
                        "properties": {},
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "title": "",
        "version": ""
    },
    "paths": {
        "/hello": {
-           "description": "dc",
            "get": {
                "description": "dc",
                "parameters": [
                    {
                        "description": "Your name",
                        "in": "query",
                        "name": "Name",
                        "required": true,
                        "schema": {
                            "description": "Your name",
                            "format": "string",
                            "properties": {},
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/main.HelloRes"
                                }
                            }
                        },
                        "description": ""
                    }
                },
                "summary": "sm"
+           }
-           },
-           "summary": "sm"
        }
    }
}
```

----

各家支持解析 OpenAPI 的工具对于 PathItem 中的 summary 和 description 并不友好，所以理论上不太存在需要自定义这两个字段的需求。

如 Apifox 会把 summary 当成一个方法：

![a31f5de0d3a28d3488b27bb8b0881c4](https://github.com/gogf/gf/assets/21287731/be0999e9-a3a8-452c-90d3-d535f7235ace)

2023-08-01 14:05 UTC, gqcn commented
@WankkoRee 感谢您的贡献，我需要花点时间仔细看看哈。

2023-08-01 14:08 UTC, gqcn requested changes

2023-08-01 14:08 UTC, gqcn commented on net/goai/goai_path.go
> +		inputMetaMapForPath := gmap.NewStrStrMapFrom(inputMetaMap).Clone()
- 这个修改不错 👍🏻
- 请在这里增加点注释说明，防止后面的维护者看不太明白为什么要删除

2023-08-01 14:09 UTC, gqcn commented
@WankkoRee CI失败了请看看呢，另外请增加该修改对应的单测哈。

2023-08-02 02:37 UTC, WankkoRee commented
单测已修复。

2023-08-02 12:45 UTC, gqcn approved these changes

2023-08-02 12:45 UTC, merged