Fixed: The clickhouse time is automatically written, causing the modi…
gogf/gf pull request #2826
Opened 2023-08-01 15:43 UTC by xgd16

Fixed: The clickhouse time is automatically written, causing the modification operation to fail

2023-08-02 01:57 UTC, gqcn requested changes

2023-08-02 01:57 UTC, gqcn commented on database/gdb/gdb_model_insert.go
> +		now             = gtime.Now().Time
直接改基础组件的逻辑可能会引起其他`driver`失败，如果只是特定数据库类型的数据类型转换问题，是不是修改这里 https://github.com/gogf/gf/blob/574d63b4fd81cbef7c3247ceebdcc02415212b9a/contrib/drivers/clickhouse/clickhouse.go#L366 更合适一些？

2023-08-02 02:20 UTC, xgd16 commented on database/gdb/gdb_model_insert.go
> +		now             = gtime.Now().Time
[database/gdb/gdb_model_insert.go](https://github.com/gogf/gf/pull/2826/files/2968370918f18abb1dfddad09cba2ebc41ee371d#diff-88304ddb7791aedbd83dafb68374aecab286d1356a7f2f149a8e57ac1a7f40b4) 请查阅此文件 此函数中的内容 自动写入时间 后置 于 类型转换 调用 导致 走不到 [gf/contrib/drivers/clickhouse/clickhouse.go](https://github.com/gogf/gf/blob/574d63b4fd81cbef7c3247ceebdcc02415212b9a/contrib/drivers/clickhouse/clickhouse.go#L366) 中的转换函数

2023-08-07 12:28 UTC, gqcn commented
@xgd16 Merged and commit in https://github.com/gogf/gf/pull/2830

2023-08-07 12:28 UTC, closed without merging