Modify the gproc.manager.KillAll function to prevent partial processes
gogf/gf pull request #2842
Opened 2023-08-06 05:06 UTC by wsy998

Modify the gproc.manager.KillAll function to prevent partial processes from not being terminated due to premature termination.

2023-08-07 12:38 UTC, gqcn commented
@wsy998 Hello, what is your business scenario of this update?

2023-08-08 02:01 UTC, wsy998 commented
翻译：当某个进程结束后，如果忘记从gproc.Manager内移除，会返回err，此时如果gproc.Manager还有其他的进程的话，就不会被结束掉

2023-08-08 02:02 UTC, wsy998 commented
After a process is terminated, if it is forgotten to be removed from the gproc.Manager, an error will be returned. In this case, if there are other processes still present in the gproc.Manager, it will not be terminated.

2023-08-08 02:10 UTC, wsy998 commented
By returning a map in this manner, it is possible to attempt to terminate processes within the manager as much as possible, while also providing feedback to the developer about which processes were not terminated and the reasons for their persistence. This approach avoids returning an error within a loop. Doing so ensures that even if one process termination fails, the execution can continue for others, thereby preventing an interruption in achieving a complete "killAll" operation.

2023-08-08 12:35 UTC, gqcn commented
@wsy998 你好，我理解只有在被管理的进程不存在的时候这个`KillAll`才会返回`error`。这里要改进的话，可以在`Process.Kill`中再做个存在性判断，同时也可以改进下`SignalAll`方法。不建议修改已有的方法定义，会引起不兼容变更。

2023-08-09 08:24 UTC, wsy998 commented
我在循环的时候直接判断进程有没有存在,不存在就放到一个slice里，最后做清理

2023-08-10 14:09 UTC, gqcn requested changes

2023-08-10 14:09 UTC, gqcn commented on os/gproc/gproc.go
> +	err = process.Signal(syscall.Signal(0))
是不是`os.FindProcess`就可以判断进程是否存在了，这里是否有必要再发送一个信号来做判断？

2023-08-10 14:09 UTC, gqcn commented on os/gproc/gproc.go
> +func ProcessExist(pid int) bool {
命名用`IsProcessExist`？

2023-08-10 14:09 UTC, gqcn commented on os/gproc/gproc_manager.go
>  		if err := p.Kill(); err != nil {
- 进程的存在和删除是否在`Process.Kill`中做比较合适？如果进程不存在是否就代表`Kill`就算是成功了？
- 其实这里还有个细节，就是你根据`pid`去判断进程是否存在，但并没有检查存在的这个进程是否当前`Process`的这个进程，可能这个进程已经意外退出了，另外一个不同的进程占用了这个`pid`。所以可能需要判断下`Cmd`的一些关键属性。

2023-08-11 10:21 UTC, wsy998 commented on os/gproc/gproc.go
> +	err = process.Signal(syscall.Signal(0))
> 是不是`os.FindProcess`就可以判断进程是否存在了，这里是否有必要再发送一个信号来做判断？

这个发送信号是判断进程是否存活，就是死了，但可能还没被回收，如果不需要判断我可以去掉。

2023-08-11 13:40 UTC, wsy998 commented on os/gproc/gproc_manager.go
>  		if err := p.Kill(); err != nil {
第一点：Kill应该够用了，没必要再判断了吧，还是说有可能Kill返回err，但是仍被kill的情况
第二点：您觉得如果再加一个`Cmd.Args`够了吗？

2023-08-15 11:36 UTC, gqcn requested changes

2023-08-15 11:36 UTC, gqcn commented on os/gproc/gproc_manager.go
>  		}
使用原来的错误处理即可，如果失败则立即返回，不用在意是否所有的Kill完毕：
```go
if err = p.Kill(); err != nil {
    return err
}
```

2023-08-15 11:36 UTC, gqcn commented on os/gproc/gproc_manager.go
> +			}
`gerror.Wrap`是用于错误堆栈，带层级的错误管理，这里每个错误都是独立。使用原来的错误判断即可。
```go
if err = p. Signal(sig); err != nil {
    err = gerror.Wrapf(err, `send signal to process failed for pid "%d" with signal "%s"`, p.Process.Pid, sig)
    return err
}
```

2023-08-15 11:36 UTC, gqcn commented on os/gproc/gproc_process.go
> +	process2 "github.com/shirou/gopsutil/process"
没要引入第三方就尽量不要引入。

2023-08-15 11:36 UTC, gqcn commented on os/gproc/gproc_process.go
> +func (p *Process) IsSameProgress(process *os.Process) bool {
该方法是否有必要公开？

2023-08-15 11:36 UTC, gqcn commented on os/gproc/gproc_process.go
> +	createTime, err := newProcess.CreateTime()
判断`command line&args`即可

2023-08-16 09:14 UTC, wsy998 commented on os/gproc/gproc_process.go
> +	createTime, err := newProcess.CreateTime()
Command line可能不太好获取，主要是golang在windows上会对`"`做转义，并不是简单的拼接，所以我想引用第三方包来处理比较方便

2023-08-16 13:21 UTC, gqcn commented on os/gproc/gproc_process.go
> +	createTime, err := newProcess.CreateTime()
我看了一下确实不太好处理，这个`Manager`对象的功能其实比较简单，也很少场景会用，你也发现内部实现写有些小问题，可能考虑未来会删除它。所以这个`pr`我建议就不继续了，辛苦了 @wsy998 。

2023-08-16 13:23 UTC, closed without merging