fix: marked gcode.CodeInternalPanic for panic
gogf/gf pull request #2860
Opened 2023-08-11 03:32 UTC by LonelySally

2023-08-11 11:30 UTC, gqcn requested changes

2023-08-11 11:30 UTC, gqcn commented on util/gconv/gconv_struct.go
> +				err = gerror.WrapCodef(gcode.CodeInternalPanic, err, `error binding value to attribute "%s"`, attrName)
这里不用加`CodeInternalPanic`处理哈，这里只是判断有无`panic`随后进入另一个转换逻辑。

2023-08-14 01:52 UTC, gqcn approved these changes

2023-08-14 01:53 UTC, merged

2023-08-17 11:24 UTC, shuqingzai commented
这应该需要标记 #2852 以关联相关 issue