docs: fix code comment err in Model Join case
gogf/gf pull request #2884
Opened 2023-08-21 09:03 UTC by BugKillerPro

fix code comment err in Model Join case

2023-08-22 01:25 UTC, BugKillerPro commented
@gqcn 
`
// LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
// The parameter `table` can be joined table and its joined condition,
// and also with its alias name.
//
// Eg:
// Model("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
// Model("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
// Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid").
func (m *Model) LeftJoin(table ...string) *Model {
	return m.doJoin("LEFT", table...)
}
`
Eg:Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid").
got Sql:  select * from user u left join (SELECT xxx FROM xxx AS a) on a.uid=u.uid; 
and with err : "Every derived table must have its own alias"

if change above Eg to:Model("user", "u").LeftJoin("SELECT xxx FROM xxx","a", "a.uid=u.uid").
we got right Sql: select * from user u left join (SELECT xxx FROM xxx ) AS a on a.uid=u.uid;

2023-08-23 12:07 UTC, gqcn commented
> @gqcn
> 
> ```go
> // LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
> // The parameter `table` can be joined table and its joined condition,
> // and also with its alias name.
> //
> // Eg:
> // Model("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
> // Model("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
> // Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid").
> func (m *Model) LeftJoin(table ...string) *Model {
> 	return m.doJoin("LEFT", table...)
> }
> ```
> 
> Eg:Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid"). got Sql: ` select * from user u left join (SELECT xxx FROM xxx AS a) on a.uid=u.uid;` and with err : `"Every derived table must have its own alias"`
> 
> if change above Eg to:Model("user", "u").LeftJoin("SELECT xxx FROM xxx","a", "a.uid=u.uid"). we got right Sql: `select * from user u left join (SELECT xxx FROM xxx ) AS a on a.uid=u.uid;`

Awesome! Would you please post another pr to fix these comments?

2023-08-24 01:10 UTC, BugKillerPro commented
Would you please update the parameter name as well?
Done

2023-08-24 01:11 UTC, BugKillerPro commented
> > @gqcn
> > ```go
> > // LeftJoin does "LEFT JOIN ... ON ..." statement on the model.
> > // The parameter `table` can be joined table and its joined condition,
> > // and also with its alias name.
> > //
> > // Eg:
> > // Model("user").LeftJoin("user_detail", "user_detail.uid=user.uid")
> > // Model("user", "u").LeftJoin("user_detail", "ud", "ud.uid=u.uid")
> > // Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid").
> > func (m *Model) LeftJoin(table ...string) *Model {
> > 	return m.doJoin("LEFT", table...)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Eg:Model("user", "u").LeftJoin("SELECT xxx FROM xxx AS a", "a.uid=u.uid"). got Sql: ` select * from user u left join (SELECT xxx FROM xxx AS a) on a.uid=u.uid;` and with err : `"Every derived table must have its own alias"`
> > if change above Eg to:Model("user", "u").LeftJoin("SELECT xxx FROM xxx","a", "a.uid=u.uid"). we got right Sql: `select * from user u left join (SELECT xxx FROM xxx ) AS a on a.uid=u.uid;`
> 
> Awesome! Would you please update the parameter name as well?
@gqcn 
Done!

2023-08-28 13:50 UTC, gqcn requested changes

2023-08-29 05:06 UTC, BugKillerPro commented on database/gdb/gdb_model_join.go
>  func (m *Model) LeftJoin(table ...string) *Model {
done

2023-09-04 12:05 UTC, gqcn approved these changes

2023-09-04 12:05 UTC, merged