预处理标准路由的参数tag反射
gogf/gf pull request #2923
Opened 2023-09-01 10:25 UTC by hailaz

https://github.com/gogf/gf/issues/2060
顺便修一个bug https://github.com/gogf/gf/issues/2904

2023-09-04 13:30 UTC, gqcn commented
@hailaz CI失败了，请查看一下呢。另外这提交的修改代码量有点多，能否把`bug`修复和改进分成两个`pr`方便`review`。

2023-09-05 01:45 UTC, hailaz commented
> @hailaz CI失败了，请查看一下呢。另外这提交的修改代码量有点多，能否把`bug`修复和改进分成两个`pr`方便`review`。

@gqcn 先看https://github.com/gogf/gf/pull/2931

2023-09-12 13:46 UTC, gqcn requested changes

2023-09-12 13:46 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +		info.Func = func(r *Request) {
你把执行阶段的那段代码块挪到了路由注册这里，使用闭包方法来维护并没有看出有什么优化的点？反而需要额外增加一个`info.IsOpenAPI`的属性变量。

2023-09-12 13:46 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +
毫无意义的空行。

2023-09-12 13:46 UTC, gqcn commented on net/ghttp/ghttp.go
> +		ReqFields []gstructs.Field
`ReqTagFields`?

2023-09-18 02:28 UTC, hailaz commented on net/ghttp/ghttp.go
> +		ReqFields []gstructs.Field
这个是struct的fields应该不限于tag吧，只是目前只用到他的tag。

2023-09-18 02:50 UTC, hailaz commented on net/ghttp/ghttp_server_service_handler.go
> +		info.Func = func(r *Request) {
我认为这样更加清晰，上方判断了传入的函数情况，在下面确认函数执行步骤。按之前的方式，在阅读源码的时候还要想funcInfo.Type到底在哪赋值，有一定割裂感。

2023-09-19 12:44 UTC, gqcn requested changes

2023-09-19 12:44 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +				`invalid handler: defined as "%s", but the second input parameter should be type of pointer to struct(*BizReq)`,
`invalid handler: defined as "%s", but the second input parameter should be type of pointer to struct like "*BizReq"`

2023-09-19 12:44 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +				`invalid handler: defined as "%s", but the first output parameter should be type of pointer to struct(*BizRes)`,
`invalid handler: defined as "%s", but the first output parameter should be type of pointer to struct like "*BizRes"`

2023-09-19 12:44 UTC, gqcn commented on net/ghttp/ghttp_request_middleware.go
> +			m.request.error = gerror.New("Handler function not found.")
路由执行不可能到这里，把这块判断去掉吧。

2023-09-19 12:44 UTC, gqcn commented on net/ghttp/ghttp.go
> +		ReqFields []gstructs.Field
完善一下注释吧。

2023-09-19 12:44 UTC, gqcn commented on net/ghttp/ghttp.go
> +		IsOpenAPI bool          // Is OpenAPI handler.
这个属性名称修改为`IsStrictRoute`吧，跟`OpenAPI`没直接关系。

2023-09-25 13:34 UTC, gqcn approved these changes

2023-09-25 13:34 UTC, merged