Make GTime support multiple formats
gogf/gf pull request #2933
Opened 2023-09-05 05:09 UTC by bigger-boss

Make GTime method support multiple formats

2023-09-05 12:29 UTC, gqcn commented
@bigger-boss What is the business scenario for?

2023-09-05 12:45 UTC, bigger-boss commented
The time string my

> @bigger-boss What is the business scenario for?

The time data string may not only come from a fixed format front-end component, but also from some sources without a fixed format, such as a column in an Excel table. Different users may use 2023 / 09 / 05 or 2023-09-05 or other formats to express time, which is not easy to control. The parameters here are variable, giving me the first impression that there may not be one, or there may be multiple. However, it was found that multiple types did not work.

2023-09-11 02:11 UTC, gqcn commented
> The time string my
> 
> > @bigger-boss What is the business scenario for?
> 
> The time data string may not only come from a fixed format front-end component, but also from some sources without a fixed format, such as a column in an Excel table. Different users may use 2023 / 09 / 05 or 2023-09-05 or other formats to express time, which is not easy to control. The parameters here are variable, giving me the first impression that there may not be one, or there may be multiple. However, it was found that multiple types did not work.

I see. There is another function `ParseTimeFromContent` should also be updated, and associated the comments of the functions should also be updated.

2023-09-11 02:12 UTC, gqcn requested changes

2023-09-11 02:12 UTC, gqcn commented on util/gconv/gconv_time.go
> +		return nil
There is another function `ParseTimeFromContent` should also be updated, and associated the comments of the functions should also be updated.

2023-09-12 12:51 UTC, gqcn commented
@bigger-boss I see the ci failed. Please pull the latest master branch of the main repo `git pull https://github.com/gogf/gf master` and push your branch again.

2023-09-12 12:52 UTC, gqcn requested changes

2023-09-13 02:18 UTC, bigger-boss commented
I have fixed the problem, but I cannot find any button on this browser page to merge into the official repository. And when I resubmit the pull request in my fork repository, it still doesn't have a button and will jump to this page. Please help me.

2023-09-13 02:23 UTC, bigger-boss commented on util/gconv/gconv_time.go
> +// It returns the converted value that matched the first format of the formats slice
ok

2023-09-13 11:29 UTC, gqcn approved these changes

2023-09-13 11:29 UTC, merged