fix: 修复代码中静态检查的警告
gogf/gf pull request #2935
Opened 2023-09-05 08:44 UTC by hailaz

2023-09-05 12:45 UTC, gqcn requested changes

2023-09-05 12:45 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_router_domain_basic_test.go
>  		t.AssertNil(err)
可以把`t.AssertNil(err)`往前挪。以下同。

2023-09-05 12:45 UTC, gqcn commented on net/ghttp/ghttp_request.go
> -type handlerResponse struct {
确认未使用可直接删除。

2023-09-05 12:45 UTC, gqcn commented on net/ghttp/ghttp_server_graceful.go
> -// setFd sets the file descriptor for current server.
确认未使用可删除。

2023-09-06 02:49 UTC, hailaz commented on net/ghttp/ghttp_z_unit_feature_router_domain_basic_test.go
>  		t.AssertNil(err)
done

2023-09-06 02:49 UTC, hailaz commented on net/ghttp/ghttp_request.go
> -type handlerResponse struct {
done

2023-09-06 02:49 UTC, hailaz commented on net/ghttp/ghttp_server_graceful.go
> -// setFd sets the file descriptor for current server.
done

2023-09-07 12:22 UTC, gqcn approved these changes

2023-09-07 12:22 UTC, merged