feat: 🎸 1、ctx初始化不上报span；2、middleware上报请求url改为path
gogf/gf pull request #2937
Opened 2023-09-05 14:50 UTC by will0306

1、项目底层上流调用链上报了WithCtx，此处干扰视线，影响界面显示，没法正常直观得看到展示的调用层
2、调用链上报的operation 是url, 这样会导致openration遍地繁衍，杂乱五章，如果想看具体请求业务日志，应当去日志系统查看

2023-09-06 02:27 UTC, gqcn requested changes

2023-09-06 02:27 UTC, gqcn commented on net/ghttp/ghttp_middleware_tracing.go
> +	carrierData.Add("url", r.URL.String())
这里添加`url`会修改原有的`header`，不建议修改`header`内容。而是将`url`添加到后面`94`行的`span.AddEvent`中。注意参考现有代码使用常量，例如：
```go
tracingEventHttpRequestUrl = "http.request.url"
```

2023-09-06 02:48 UTC, will0306 commented on net/ghttp/ghttp_middleware_tracing.go
> +	carrierData.Add("url", r.URL.String())
已改

2023-09-11 02:13 UTC, gqcn approved these changes

2023-09-11 02:14 UTC, merged