fix(gutil): panic when field is []byte(BINARY in mysql)
gogf/gf pull request #2957
Opened 2023-09-12 07:17 UTC by laushunyu

## Preview
在数据表定义时，我使用了 binary(32) 作为其主键，并使用 gf 生成了对应的 do 与 entity, 其主键类型为 []byte 。在数据关联查询过程中使用了 ListItemValuesUnique 导致了 panic，debug 发现当去重的 map 指定的 key 为 []byte 时，go 会认为其 not comparable 直接 panic， 考虑到 []byte 与 string 强转的内存拷贝问题，这里使用了 unsafe 来转换 StringHeader 与 SliceHeader 并将结果的 string 作为 key 进行去重操作 

## Testcase
```
func Test_ListItemValuesUnique_Binary_ID(t *testing.T) {
	gtest.C(t, func(t *gtest.T) {
		listMap := g.List{
			g.Map{"id": []byte{1}, "score": 100},
			g.Map{"id": []byte{2}, "score": 100},
			g.Map{"id": []byte{3}, "score": 100},
			g.Map{"id": []byte{4}, "score": 100},
			g.Map{"id": []byte{4}, "score": 100},
		}
		t.Assert(gutil.ListItemValuesUnique(listMap, "id"), g.Slice{[]byte{1}, []byte{2}, []byte{3}, []byte{4}})
		t.Assert(gutil.ListItemValuesUnique(listMap, "score"), g.Slice{100})
	})
}
```

### Before
```
=== RUN   Test_ListItemValuesUnique_Binary_ID
runtime error: hash of unhashable type []uint8
1.  github.com/gogf/gf/v2/util/gutil.ListItemValuesUnique
    /home/macoo/gf/util/gutil/gutil_list.go:126
2.  github.com/gogf/gf/v2/util/gutil_test.Test_ListItemValuesUnique_Binary_ID.func1
    /home/macoo/gf/util/gutil/gutil_z_unit_list_test.go:259
3.  github.com/gogf/gf/v2/util/gutil_test.Test_ListItemValuesUnique_Binary_ID
    /home/macoo/gf/util/gutil/gutil_z_unit_list_test.go:251
--- FAIL: Test_ListItemValuesUnique_Binary_ID (0.00s)
```

### After
```
=== RUN   Test_ListItemValuesUnique_Binary_ID
--- PASS: Test_ListItemValuesUnique_Binary_ID (0.00s)
PASS
```

2023-09-13 13:12 UTC, gqcn requested changes

2023-09-13 13:12 UTC, gqcn commented on util/gutil/gutil_list.go
> +				value = unsafeString(t)
```
不建议在框架中使用unsafe的相关操作哈，会遇到一些莫名其妙的内存访问问题，且难以排查。

                        -- 不是鲁迅，来自一位被unsafe坑过多次的开发者现身说法。
```

2023-09-15 03:54 UTC, laushunyu commented on util/gutil/gutil_list.go
> +				value = unsafeString(t)
其实 slice header 转到 string header 还是比较 safe 的我认为。

不过那我还是改掉把。

2023-09-18 12:15 UTC, gqcn commented on util/gutil/gutil_list.go
> +				value = unsafeString(t)
一位曾经因为`unsafe`使用造成生产事故的开发者认为这样最好。

2023-09-18 12:16 UTC, gqcn approved these changes

2023-09-18 12:16 UTC, merged