feat: add gstr.PadEnd,gstr.PadStart func
gogf/gf pull request #2960
Opened 2023-09-13 12:48 UTC by YanCastle

add two func
gstr.PadEnd
gstr.PadStart

2023-09-13 13:18 UTC, gqcn requested changes

2023-09-13 13:18 UTC, gqcn commented on text/gstr/gstr_pad.go
> +// pads this string with another string (multiple times, if needed)
注释应当使用方法名打头哦。

2023-09-13 13:18 UTC, gqcn commented on text/gstr/gstr_pad.go
> +func PadStart(s, padStr string, targetLen int) string {
- 建议使用`Left/Right`这样的关键字替代`Starr/End`，没有好坏，只是保持方法命名统一让开发者便于理解罢了。
- `targetLen` -> `padLen`

2023-09-13 13:28 UTC, YanCastle commented
padStart/End 是来源于js的string的方法名称，

2023-09-13 13:29 UTC, YanCastle commented
targetLen 是目标长度

2023-09-13 13:30 UTC, YanCastle commented
targetLen 是目标长度
padLen 字面意思是追加的长度，
此处的含义为希望追加后的字符长度是多少而不是要追加多少长度，

2023-09-14 01:57 UTC, gqcn commented
> targetLen 是目标长度 padLen 字面意思是追加的长度， 此处的含义为希望追加后的字符长度是多少而不是要追加多少长度，

明白了，那在注释里面介绍清楚吧，不然容易引起误解。像我一样。

2023-09-14 01:58 UTC, gqcn commented
@YanCastle CI失败了哦，看起来是单测没有更新哈。

2023-09-18 12:21 UTC, gqcn commented
@YanCastle Any updates？

2023-09-25 13:08 UTC, gqcn commented
@YanCastle Any updates?

2023-10-08 11:19 UTC, gqcn commented
@YanCastle Closed due to inactivity.

2023-10-08 11:19 UTC, closed without merging