fix: gi18n default manager无法读取gres资源问题
gogf/gf pull request #2961
Opened 2023-09-14 06:54 UTC by hailaz

https://github.com/gogf/gf/issues/2874

2023-09-14 12:06 UTC, gqcn requested changes

2023-09-14 12:06 UTC, gqcn commented on i18n/gi18n/gi18n_manager.go
> +		}
这个修复挺好的。

2023-09-14 12:06 UTC, gqcn commented on i18n/gi18n/gi18n_z_unit_test.go
> +}
- 不要直接增加一个默认的资源，这样单测在启动的时候就会加载这个资源，并且可能会影响其他单例。
- 建议在`package gres`下编写单测，并且提供内部的清理方法可以清空内部的资源。
- 一个单例在执行完毕后要恢复现场不能影响其他单例，创建和清理都应该在一个单例中实现。

2023-09-15 02:47 UTC, hailaz commented on i18n/gi18n/gi18n_z_unit_test.go
> +}
嗯，这样的确影响了其它单测了。

2023-09-18 12:39 UTC, gqcn requested changes

2023-09-19 03:00 UTC, hailaz commented on i18n/gi18n/gi18n_ctx.go
> +type CtxLanguage string
有个语法警告，上下文个key不建议使用内置类型。所以自定义一个类型。

2023-09-19 03:04 UTC, hailaz commented on i18n/gi18n/gi18n_manager.go
> +	pathType   PathType       // Path type for i18n files.
有这样想过，但是在DefaultOptions中就没法进行标记了。

2023-09-19 12:23 UTC, gqcn commented on i18n/gi18n/gi18n_ctx.go
> +type CtxLanguage string
@hailaz 那可以使用`gstr.StrKey`类型。

2023-09-19 12:29 UTC, gqcn requested changes

2023-09-19 12:29 UTC, gqcn commented on i18n/gi18n/gi18n_manager.go
> +type PathType string
如果此类型不对外使用的话请设置不公开。

2023-09-19 12:29 UTC, gqcn commented on i18n/gi18n/gi18n_manager.go
> +	pathType   PathType       // Path type for i18n files.
@hailaz 既然如此的话，那把`DefaultOptions`的逻辑挪到`New`方法里面去怎么样？

2023-09-21 02:53 UTC, hailaz commented on i18n/gi18n/gi18n_ctx.go
> +type CtxLanguage string
是gctx.StrKey

2023-09-25 13:07 UTC, gqcn requested changes

2023-10-09 12:02 UTC, gqcn requested changes

2023-10-10 12:02 UTC, gqcn approved these changes

2023-10-10 12:02 UTC, merged