fix issues #2980
gogf/gf pull request #2994
Opened 2023-09-28 16:12 UTC by oldme-git

gconv.Scan() is the time zone consistent in recursive. View at https://github.com/gogf/gf/issues/2980, please.

```
type Post struct {
	CreatedAt *gtime.Time `json:"createdAt" `
}

type PostWithUser struct {
	Post
	UserName string `json:"UserName"`
}

gtest.C(t, func(t *gtest.T) {
	params := g.Map{
		"CreatedAt": gtime.New("2023-09-22 12:00:00").UTC(),
		"UserName":  "Galileo",
	}
	postWithUser := new(PostWithUser)
	err := gconv.Scan(params, postWithUser)
	t.AssertNil(err)
	g.Dump(postWithUser.CreatedAt.Location()) // result: Local
})

gtest.C(t, func(t *gtest.T) {
	params := g.Map{
		"CreatedAt": gtime.New("2023-09-22 12:00:00").UTC(),
	}
	post := new(Post)
	err := gconv.Scan(params, post )
	t.AssertNil(err)
	g.Dump(post .CreatedAt.Location()) // result: UTC
})
```

2023-09-28 16:13 UTC, oldme-git commented
@houseme 之前的PR关掉了，我重新提交一个，帅哥哥帮忙看看o.O

2023-10-07 12:50 UTC, gqcn requested changes

2023-10-07 12:50 UTC, gqcn commented on util/gconv/gconv_struct.go
> +				FromValue:  value.(interface{}),
You cannot use `value.(interface{})` here as the `value` is already type of `interface{}`.

2023-10-09 12:05 UTC, gqcn commented
@oldme-git Any updates.

2023-10-10 12:12 UTC, gqcn commented
> @gqcn 匿名结构体在 doStruct 的递归中丢失了细节信息，看一下这个代码示例：
> 
> ```
> func Test_Struct_Issue2980C(t *testing.T) {
> 	var pointer interface{} = gtime.New("2023-09-22 12:00:00").UTC()
> 	fmt.Println(pointer.(*gtime.Time).Location()) // UTC
> 	if v, ok := pointer.(iUnmarshalText); ok {
> 		var valueBytes []byte
> 		if b, ok := pointer.([]byte); ok {
> 			valueBytes = b
> 		} else if s, ok := pointer.(string); ok {
> 			valueBytes = []byte(s)
> 		} else if f, ok := pointer.(iString); ok {
> 			// !!!!! gtime.Time的String方法只会转换2006-01-02 15:04:05格式，导致细节丢失
> 			valueBytes = []byte(f.String()) 
> 		}
> 		if len(valueBytes) > 0 {
> 			v.UnmarshalText(valueBytes)
> 		}
> 	}
> 	fmt.Println(pointer.(*gtime.Time).Location()) // Local
> }
> ```
> 
> **第一次执行数据绑定时，嵌套结构体中时间字段尚且是空的，所以可以绑定成功。当递归到第二次的时候，嵌套结构体有了默认值，在执行 bindVarToReflectValueWithInterfaceCheck 时，触发了 gtime 的 UnmarshalText 方法，使时间细节丢失。**
> 
> 这里面的逻辑有些绕，具体的这段代码在 gconv_struct.go 的 409 行 444 行。
> 
> 强哥有什么其他的好的修改方法吗？

我看看呢

2023-10-11 13:28 UTC, merged