the registry of nacos
gogf/gf pull request #2995
Opened 2023-09-29 04:34 UTC by joy999

2023-10-07 12:53 UTC, gqcn commented
@joy999 Thanks for your contribution! But it seems that there's some data race issue in your dependent package `github.com/nacos-group/nacos-sdk-go/v2`.

2023-10-07 13:07 UTC, gqcn requested changes

2023-10-07 13:07 UTC, gqcn commented on contrib/registry/nacos/nacos_endpoint.go
> +type Endpoint struct {
可以使用`gsvc.LocalEndpoint`而不是重新定义一个新的数据结构。

2023-10-07 13:07 UTC, gqcn commented on contrib/registry/nacos/nacos_service.go
> +type Service struct {
可以使用`gsvc.LocalService`而不是重新定义一个新的数据结构。

2023-10-08 06:49 UTC, joy999 commented on go.mod
> +	github.com/nacos-group/nacos-sdk-go/v2 v2.2.3
已调整

2023-10-08 06:51 UTC, joy999 commented on contrib/registry/nacos/nacos.go
> +type Registry struct {
已添加注释

2023-10-08 06:52 UTC, joy999 commented on contrib/registry/nacos/nacos.go
> +	cacheDir := conf.MustGet(ctx, "nacos.cache_dir").String()
那这个函数可以去掉。显式调用是在New方法中进行的。这个只是一个包装。

2023-10-08 06:55 UTC, joy999 commented on contrib/registry/nacos/nacos.go
> +package nacos
已补充。

2023-10-08 07:01 UTC, joy999 commented on contrib/registry/nacos/nacos_endpoint.go
> +type Endpoint struct {
已处理

2023-10-08 07:06 UTC, joy999 commented on contrib/registry/nacos/nacos_service.go
> +type Service struct {
已调整

2023-10-10 13:07 UTC, gqcn requested changes

2023-10-10 13:07 UTC, gqcn commented on contrib/registry/nacos/go.mod
> +)
请参考其他`contrib/registry`组件在`go.mod`中增加`replace`语句：
```
replace github.com/gogf/gf/v2 => ../../../
```

2023-10-10 13:07 UTC, gqcn commented on contrib/registry/nacos/nacos.go
> +// ClientConfig is cname the constant.ClientConfig
这个注释有点看不懂。建议这个注释可以从别名的常量那边的源码中拷贝过来。

2023-10-10 13:28 UTC, houseme commented on contrib/registry/nacos/nacos.go
> +		clusterName: "DEFAULT",
`clusterName` 和 `groupName ` 这2个参数都是固定值吗？有可能发生变化吗？

2023-10-10 13:31 UTC, houseme commented on contrib/registry/nacos/nacos_discovery.go
> +		info := gstr.SplitAndTrim(gstr.Trim(in.Prefix, "/"), "/")
这个`/` 在`gsvc`中有静态常量 `gsvc.DefaultSeparator` 可以替换

2023-10-10 13:32 UTC, houseme commented on contrib/registry/nacos/nacos_discovery.go
> +	sArr := gstr.Split(key, "/")
同上 `gsvc.DefaultSeparator`

2023-10-10 13:33 UTC, houseme commented on contrib/registry/nacos/nacos_discovery.go
> +	serviceName := sArr[4]
这里的数组长度是不是需要判断一下呢？

2023-10-10 13:35 UTC, houseme commented on contrib/registry/nacos/nacos_discovery.go
> +	err = c.Subscribe(param)
个人喜欢 直接 
```go
if err = c.Subscribe(param);err!=nil{
       return
}
```

2023-10-10 13:37 UTC, houseme commented on contrib/registry/nacos/nacos_register.go
> +	c := reg.client
这里的`c :=reg.client` 是不是可以在48行前面在处理 ？

2023-10-10 13:42 UTC, houseme commented on contrib/registry/nacos/nacos_service.go
> +	if gstr.Contains(serviceName, "@@") {
建议 `@@` 让常量代替

2023-10-10 13:42 UTC, houseme commented on contrib/registry/nacos/nacos_service.go
> +		Version:   "latest",
`latest` 可以使用 `gsvc.DefaultVersion` 替换

2023-10-10 14:01 UTC, houseme reviewed
根目录下 `go.mod` 可以复原一下

2023-10-10 14:07 UTC, joy999 commented on contrib/registry/nacos/go.mod
> +)
已增加

2023-10-10 14:08 UTC, joy999 commented on contrib/registry/nacos/nacos.go
> +		clusterName: "DEFAULT",
会发生变化，有提供修改接口。SetClusterName及SetGroupName

2023-10-10 14:10 UTC, joy999 commented on contrib/registry/nacos/nacos_discovery.go
> +		info := gstr.SplitAndTrim(gstr.Trim(in.Prefix, "/"), "/")
已调整

2023-10-10 14:12 UTC, joy999 commented on contrib/registry/nacos/nacos_discovery.go
> +	serviceName := sArr[4]
已加判定

2023-10-10 14:14 UTC, joy999 commented on contrib/registry/nacos/nacos_discovery.go
> +	err = c.Subscribe(param)
我都有在用。单独一行不容易写错代码。给调整了下风格。这里可以合并。

2023-10-10 14:16 UTC, joy999 commented on contrib/registry/nacos/nacos_register.go
> +	c := reg.client
可以直接使用了。就一处用到了。这是遗留问题，之前没用BatchRegister，有个循环调用。所以放在最上面在。给改过了。

2023-10-10 14:19 UTC, joy999 commented on contrib/registry/nacos/nacos_service.go
> +	if gstr.Contains(serviceName, "@@") {
已处理

2023-10-10 14:24 UTC, joy999 commented on contrib/registry/nacos/nacos_discovery.go
> +	sArr := gstr.Split(key, "/")
已处理

2023-10-10 14:25 UTC, joy999 commented on contrib/registry/nacos/nacos.go
> +// ClientConfig is cname the constant.ClientConfig
直接把它去掉，感觉也没必要。嘿嘿~

2023-10-10 14:33 UTC, houseme approved these changes

2023-10-11 13:33 UTC, gqcn approved these changes

2023-10-12 13:06 UTC, merged