feat: add `-w/--watchPaths` for subcommand `gf run`
gogf/gf pull request #3009
Opened 2023-10-10 02:43 UTC by windvalley

Live reload supports files specified using the "-w" parameter in addition to Go files.

Usage Example:

1) Watch one file
$ gf run main.go -w manifest/config/config.yaml

2) Watch multiple files, seprated by commas
$ gf run main.go -w manifest/config/config.yaml,otherpath/otherfile

Fixes #2822

2023-10-10 13:37 UTC, gqcn requested changes

2023-10-10 13:37 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +		WatchPaths string `name:"watchPaths" short:"w"  brief:"{cRunWatchPathsBrief}"`
这个参数不是很好能理解如何使用，建议增加命令行中的帮助信息，信息如：
```
gf run main.go -w "*.go,manifest/config/*.yaml"
```

2023-10-10 13:37 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +func matchWatchPaths(watchPaths []string, eventPath string) bool {
建议内部使用`filepath.Match`来做规则匹配，可以研究一下这个标准库的方法。

2023-10-10 15:16 UTC, windvalley commented on cmd/gf/internal/cmd/cmd_run.go
> +func matchWatchPaths(watchPaths []string, eventPath string) bool {
已经改为使用标准库`filepath.Match`来匹配:)

2023-10-11 13:38 UTC, gqcn requested changes

2023-10-11 13:38 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +			mlog.Printf(`file changes: %s`, event.String())
`file changes` -> `watched file changes`

2023-10-11 13:38 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +		WatchPaths string `name:"watchPaths" short:"w"  brief:"{cRunWatchPathsBrief}"`
@windvalley 这个描述不错。另外在`50`行增加使用示例。

2023-10-11 14:40 UTC, windvalley commented on cmd/gf/internal/cmd/cmd_run.go
> +		WatchPaths string `name:"watchPaths" short:"w"  brief:"{cRunWatchPathsBrief}"`
已增加一个简单的示例: `gf run main.go -w "manifest/config/*.yaml"`.

2023-10-12 13:07 UTC, gqcn approved these changes

2023-10-12 13:07 UTC, merged