Feature/go workspace
gogf/gf pull request #3040
Opened 2023-10-12 02:30 UTC by hailaz

2023-10-12 13:54 UTC, gqcn requested changes

2023-10-12 13:54 UTC, gqcn commented on .set_version.sh
> +        mv go.work.version.bak go.work
其他都挺好，就是在这个`shell`中的这几堆`go mod edit`指令不是很好维护，得再研究一下。

2023-10-13 02:14 UTC, hailaz commented on .set_version.sh
> +        mv go.work.version.bak go.work
可以先上了，再优化。不然很久都用不了这个功能。

2023-10-16 12:43 UTC, gqcn commented on .set_version.sh
> +        mv go.work.version.bak go.work
我想了想，可以用`shell`指令来字符串操作`go.mod`自动执行`go mod`的这些指令，避免手动维护容易给后面维护埋坑

2023-10-17 02:03 UTC, hailaz commented on .set_version.sh
> +        mv go.work.version.bak go.work
感觉操作go.mod还是用go指令，统一些

2023-10-17 13:19 UTC, gqcn commented on .set_version.sh
> +        mv go.work.version.bak go.work
ok

2023-10-17 13:19 UTC, gqcn approved these changes

2023-10-18 12:01 UTC, merged