improve TemplateGenCtrlController is comments and formats
gogf/gf pull request #3065
Opened 2023-10-19 06:15 UTC by oldme-git

#3061

2023-10-19 12:03 UTC, gqcn commented
@oldme-git Besides the comments, it should check the generating logic for go file of `NewXxx`. It should not overwrite the go file of `NewXxx`.
<img width="1536" alt="image" src="https://github.com/gogf/gf/assets/26347176/2c78cb16-a395-4d55-bb8f-96f5e85a0d04">

2023-10-19 13:25 UTC, oldme-git commented
@gqcn if _new.go existed, `if !gfile.Exists(moduleFilePathNew)` is false

2023-10-23 11:27 UTC, gqcn requested changes

2023-10-23 11:27 UTC, gqcn commented on cmd/gf/internal/consts/consts_gen_ctrl_template.go
> +	// You can edit custom logic
unnecessary comment.

2023-10-31 12:20 UTC, gqcn approved these changes

2023-10-31 12:21 UTC, merged