improve gf gen ctrl gets structs info way
gogf/gf pull request #3066
Opened 2023-10-19 09:13 UTC by oldme-git

#3063
之前使用正则表达式获取结构体信息，现在改为使用 AST 获取结构体信息，这样更为合理和精确。

2023-10-19 09:47 UTC, whileW commented
AST 可以用 ast.Inspect 去遍历，是不是更好一点
像这样
```
ast.Inspect(node, func(n ast.Node) bool {
				if v, ok := n.(*ast.TypeSpec); ok {
					if !gstr.Contains(v.Name.Name, "Req") {
						return false
					}

					if _, ok := v.Type.(*ast.StructType); !ok {
						return false
					}

					if err := printer.Fprint(&buf, fileSet, v.Type); err != nil {
						return nil, err
					}

					structsInfo[v.Name.Name] = buf.String()
					return false
				}
				return true
			})
```

2023-10-19 12:13 UTC, gqcn approved these changes

2023-10-19 12:13 UTC, gqcn commented on cmd/gf/internal/cmd/genctrl/genctrl_calculate.go
> +				methodName = gstr.TrimRight(methodName, "Req")
`gstr.TrimRightStr`

2023-10-19 12:19 UTC, gqcn commented
@oldme-git It is awesome!

2023-10-19 12:23 UTC, gqcn commented
@oldme-git There's another important improvement: adding unit testing case for command `gen ctrl`. Without a unit testing case, it is hard to validate this pr working as expect or not. There's similar reference codes https://github.com/gogf/gf/blob/master/cmd/gf/internal/cmd/cmd_gen_dao_test.go

2023-10-19 12:32 UTC, gqcn requested changes
Please see the comments.

2023-10-19 13:00 UTC, oldme-git commented
@whileW 我觉得使用for循环比Inspect更加的清晰灵活，而且GetStructs()是封装的方法，不能把"Req"直接拿进来判断

2023-10-19 13:33 UTC, whileW commented
> @whileW 我觉得使用for循环比Inspect更加的清晰灵活，而且GetStructs()是封装的方法，不能把"Req"直接拿进来判断

好吧

2023-10-25 11:30 UTC, oldme-git commented
@gqcn 强哥，你看一下geo ctrl的单测

2023-10-25 13:52 UTC, gqcn requested changes

2023-10-25 13:52 UTC, gqcn commented on cmd/gf/internal/cmd/cmd__test.go
> +var ctx = context.Background()
不用单独增加这个文件，可以将这个变量写到`cmd_gen_ctrl_test.go`文件中。

2023-10-25 13:52 UTC, gqcn commented on cmd/gf/internal/cmd/testdata/genctrl/api/article/article.go
> +}
需要把这个文件还有控制器目录中，生成的文件都加入`.gitignore`里面，不要直接提交。

2023-10-25 13:54 UTC, oldme-git commented on cmd/gf/internal/cmd/cmd__test.go
> +var ctx = context.Background()
这个变量被cmd_gen_dao_test.go占用了

2023-10-25 14:02 UTC, oldme-git commented on cmd/gf/internal/cmd/testdata/genctrl/api/article/article.go
> +}
这里的文件用作expect

2023-10-31 07:43 UTC, closed without merging