fix api and ctrl not working well.
gogf/gf pull request #3076
Opened 2023-10-22 00:59 UTC by joy999

2023-10-23 12:07 UTC, gqcn requested changes

2023-10-23 12:07 UTC, gqcn commented on cmd/gf/internal/cmd/genpb/genpb.go
>  	}
是因为属性名称和`name`不一致导致参数无法接收吗？那可能是`gcmd`的问题，不是这里的问题。

2023-11-02 08:56 UTC, hailaz commented
现在只改了个单词错误？

2023-11-02 08:59 UTC, hailaz commented
那就顺便把这些改了 @joy999 
![image](https://github.com/gogf/gf/assets/29968474/d27521d1-8b3d-4d1b-94ba-bca10317fa15)
![image](https://github.com/gogf/gf/assets/29968474/85be09bd-7e6d-4637-8b23-90e238caede0)

2023-11-02 09:06 UTC, joy999 commented
这个PR还没完成哦~ 还要修改gcmd才算OK。

2023-11-02 09:15 UTC, hailaz commented
> 这个PR还没完成哦~ 还要修改gcmd才算OK。

name:"api" 是name这个tag失效？

2023-11-04 15:46 UTC, joy999 commented on cmd/gf/internal/cmd/genpb/genpb.go
>  	}
调整了gcmd中的逻辑处理了。

2023-11-04 15:47 UTC, joy999 commented
之前的逻辑只会判定field.Name()，所以不会判定 tag: name，现在给加了如果tag: name存在，则优先使用它进行判定。

2023-11-06 02:02 UTC, gqcn commented
> 之前的逻辑只会判定field.Name()，所以不会判定 tag: name，现在给加了如果tag: name存在，则优先使用它进行判定。

我看了，改得挺好的，就是缺少对应的单测，麻烦加上对应的单测呢❤️。

2023-11-08 13:26 UTC, gqcn approved these changes

2023-11-08 13:26 UTC, gqcn commented
@joy999 @hailaz You guys are awesome! ❤️

2023-11-08 13:26 UTC, merged