fix: CamelLower to LowerCamel
gogf/gf pull request #3098
Opened 2023-10-26 10:13 UTC by hailaz

2023-10-27 01:59 UTC, gqcn commented
@hailaz 请问这么修改是为了解决什么问题吗？

2023-10-27 02:32 UTC, hailaz commented
> @hailaz 请问这么修改是为了解决什么问题吗？

更正命名， LowerCamel 是大家都用的命名

2023-10-30 02:38 UTC, houseme approved these changes

2023-10-31 02:09 UTC, gqcn commented
@hailaz 不建议改这里了，既然之前是这么命名的大家也这么使用了就尽量不改了，否则会引起兼容问题的。并且这种非功能性也非修复性的名称变动，算是可有可无的修改，不建议在普通版本中进行，除非要搞非兼容发布，倒是可以考虑一下。

2023-10-31 12:07 UTC, gqcn requested changes

2023-10-31 12:07 UTC, gqcn commented on text/gstr/gstr_case.go
> +func CaseConvert(s string, caseName string, defaultCaseName ...string) string {
公共包方法不应当给默认参数，应当在`cmd`的逻辑中自行处理。

2023-10-31 12:07 UTC, gqcn commented on text/gstr/gstr_case.go
> +	Lower           string = "Lower"
建议使用枚举类型，例如:
```go
type CaseType string
const (
    Camel CaseType = "Camel"
    // ...
)
```

2023-11-01 11:52 UTC, gqcn approved these changes

2023-11-01 11:52 UTC, merged