fix issue #3099
gogf/gf pull request #3107
Opened 2023-10-27 07:26 UTC by joy999

Continue the PR#3102

2023-10-30 12:25 UTC, gqcn requested changes

2023-10-30 12:25 UTC, gqcn commented on util/gconv/gconv_struct.go
> +		}
是否将变量抽取出来，并且将逻辑复用更优雅一些，例如：
```go
var customConverterInput reflect.Value
if reflectValue, ok := value.(reflect.Value); ok {
	customConverterInput = reflectValue
} else {
	customConverterInput = reflect.ValueOf(value)
}
if ok, err := callCustomConverter(customConverterInput, structFieldValue); ok {
	return err
}
```

2023-10-31 01:07 UTC, joy999 commented on util/gconv/gconv_struct.go
> +		}
improved

2023-10-31 01:58 UTC, gqcn requested changes

2023-10-31 01:58 UTC, gqcn commented on util/gconv/gconv_struct.go
> +		}
没有`else`哦，这样会导致`customConverterInput`可能是`nil`。

2023-10-31 01:58 UTC, gqcn commented on util/gconv/gconv_struct.go
> +		if err, ok = bindVarToReflectValueWithInterfaceCheck(structFieldValue, value); ok || err != nil {
这里的 `|| err != nil`的逻辑不应该加，如果返回错误就表示转换失败，那么尝试后续转换逻辑即可，你觉得呢？

2023-10-31 06:00 UTC, joy999 commented on util/gconv/gconv_struct.go
> +		if err, ok = bindVarToReflectValueWithInterfaceCheck(structFieldValue, value); ok || err != nil {
那这里这个err配合ok会让人感觉很困扰。ok为真是才返回err，这个时候err会不会常为nil? 可能只有读下内部代码才清楚里面怎么写的。单从这里来看。ok为真时返回err，这个很让人费解。

2023-10-31 06:02 UTC, joy999 commented on util/gconv/gconv_struct.go
> +		}
if customConverterInput, ok = value.(reflect.Value); !ok {
	customConverterInput = reflect.ValueOf(value)
}
与
if reflectValue, ok := value.(reflect.Value); ok {
	customConverterInput = reflectValue
} else {
	customConverterInput = reflect.ValueOf(value)
}
应该是等价的。当value为nil时，ok应该是假。

2023-10-31 11:13 UTC, joy999 commented on util/gconv/gconv_struct.go
> +		if err, ok = bindVarToReflectValueWithInterfaceCheck(structFieldValue, value); ok || err != nil {
Reverted

2023-10-31 12:01 UTC, gqcn approved these changes

2023-10-31 12:02 UTC, merged