enhance #3063
gogf/gf pull request #3115
Opened 2023-10-31 07:59 UTC by oldme-git

Please review [geo ctrl test](https://github.com/gogf/gf/pull/3090) First, merge it. Then you can review this PR.

2023-10-31 12:07 UTC, gqcn approved these changes

2023-10-31 12:09 UTC, gqcn commented
@oldme-git Please add associated unit testing case for this pr.

2023-10-31 12:24 UTC, gqcn requested changes
Unit testing case required.

2023-10-31 12:41 UTC, oldme-git commented
@gqcn 等https://github.com/gogf/gf/pull/3090合并后，此PR就会有单测

2023-11-06 01:59 UTC, gqcn approved these changes

2023-11-06 01:59 UTC, merged