fix: 修正PKCS5UnPadding命名为PKCS7UnPadding，并兼容旧PKCS5UnPadding
gogf/gf pull request #3124
Opened 2023-11-03 02:56 UTC by hailaz

原始pr没更新，优化一下：https://github.com/gogf/gf/pull/3059

2023-11-05 00:40 UTC, fainc commented
thanks, busy last week ❤️

2023-11-06 01:55 UTC, gqcn requested changes

2023-11-06 01:55 UTC, gqcn commented on crypto/gaes/gaes.go
> +func PKCS5Padding(src []byte, blockSize ...int) []byte {
请在注释中描述方法的功能特性。

2023-11-06 01:55 UTC, gqcn commented on crypto/gaes/gaes.go
> +func PKCS5UnPadding(src []byte, blockSize ...int) ([]byte, error) {
请在注释中描述方法的功能特性。

2023-11-06 01:55 UTC, gqcn commented on crypto/gaes/gaes.go
> +func PKCS7UnPadding(src []byte, blockSize int) ([]byte, error) {
包公开方法缺少注释说明。

2023-11-06 01:55 UTC, gqcn commented on crypto/gaes/gaes.go
> +func PKCS7Padding(src []byte, blockSize int) []byte {
包公开方法缺少注释说明。

2023-11-06 11:19 UTC, gqcn approved these changes

2023-11-06 11:20 UTC, merged