improve gen service code
gogf/gf pull request #3140
Opened 2023-11-09 02:56 UTC by oldme-git

2023-11-09 08:14 UTC, gqcn requested changes

2023-11-09 08:14 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	in.WatchFile = gstr.TrimRight(in.WatchFile, `/`)
为什么要修改这里？

2023-11-09 08:43 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	in.WatchFile = gstr.TrimRight(in.WatchFile, `/`)
采用 Go 官方包`filepath.ToSlash`统一路径，要比文本替换好些吧，一个小改善

2023-11-13 13:36 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	in.WatchFile = gstr.TrimRight(in.WatchFile, `/`)
@oldme-git  其实你会发现代码都是统一用的`/`分隔符号，所以你这么改其实并没有改全。如果实在想要改，那么需要改全面，并且增加单测来验证，这块可能有些工作量。个人建议没有太大必要就不改。

2023-11-13 15:13 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	in.WatchFile = gstr.TrimRight(in.WatchFile, `/`)
@gqcn GF 现在是 filepath 和 replace 混用的，这个代码是将 `\` 转为 `/`，有单测验证，虽然没有太大改的必要，但是为了框架代码的优雅还是值得的

2023-11-14 12:52 UTC, gqcn approved these changes

2023-11-14 12:53 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	in.WatchFile = gstr.TrimRight(in.WatchFile, `/`)
@oldme-git 其实这里缺少了对打印内容是否已经正确替换为`/`的单例和断言。

2023-11-14 12:53 UTC, merged