Fix/#3147
gogf/gf pull request #3149
Opened 2023-11-13 03:55 UTC by hailaz

2023-11-13 14:03 UTC, gqcn requested changes

2023-11-13 14:52 UTC, hailaz commented on os/gcmd/gcmd_command_object.go
> +					}
因为现有情况下没有相应的办法让他任何时候都能赋值，gcmd的赋值只能多选一。
入参的名字有三种情况：结构体成员名、tag别名、tag短名字。
目前是尽可能少的代码改动实现了bug修复，减少bug影响时间。
原来的处理流程经过了多次解析和转换，完全梳理情况需要更多时间。

2023-11-14 12:54 UTC, gqcn commented on os/gcmd/gcmd_command_object.go
> +					}
我来看看呢

2023-11-14 13:03 UTC, gqcn commented on os/gcmd/gcmd_command_object.go
> +					}
@hailaz 这个影响还好，按照最优雅的方式来修改吧，我空了也一起看看。

2023-11-14 13:30 UTC, hailaz commented on os/gcmd/gcmd_command_object.go
> +					}
@gqcn 这个bug直接影响gf -v无法使用

2023-11-16 12:08 UTC, gqcn commented on os/gcmd/gcmd_command_object.go
> +					}
@hailaz 不会吧。

2023-11-16 13:39 UTC, gqcn commented
@hailaz https://github.com/gogf/gf/pull/3161

2023-11-16 13:39 UTC, closed without merging