Fix the bug that ScanAndCount and AllAndCount report errors in sqlserver
gogf/gf pull request #3155
Opened 2023-11-14 09:26 UTC by wlqe

AllAndCount and ScanAndCount throw errors in SQL Server environment when there is an orderby statement。

sql server 2022 statement：
      drop table if exists demo
      create table demo(recid int identity(1,1),txt varchar(100),primary key(recid))
      insert into demo(txt)values('txt1'),('txt2'),('txt3')
      select * from demo

example code：
      import (
	      "fmt"
	      _ "github.com/gogf/gf/contrib/drivers/mssql/v2"
	      "github.com/gogf/gf/v2/database/gdb"
      )
      
      func main() {
	      db, err := gdb.New(gdb.ConfigNode{
		      Link: `mssql:sa:123456@tcp(192.168.1.200:1433)/demo`,
	      })
	      if err != nil {
		      panic(err)
	      }
      
	      count, i, err := db.Model("demo").Order("recid").Limit(0, 10).AllAndCount(false)
	      if err != nil {
		      fmt.Println(err)
		      return
	      }
	      fmt.Println(count, i)
      }

Error message：
   SELECT COUNT(1) FROM demo ORDER BY recid: mssql: Column "demo.recid" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP By clause.

2023-11-14 09:31 UTC, hailaz commented on database/gdb/gdb_model_select.go
> +	if !isCountStatement { //The count statement of sqlserver cannot contain the order by statement
ci过不了，注释//后面要带空格。
// The...

2023-11-14 12:04 UTC, gqcn requested changes
@wlqe Please add associated unit testing case for this update in `crontrib/drivers/mssql`: https://github.com/gogf/gf/blob/master/contrib/drivers/mssql/mssql_z_model_test.go

2023-11-14 15:57 UTC, wlqe commented
contrib/drivers/mssql/mssql_z_model_test.go新加的单元测试代码如下：(不知道怎么把新变动的文件加到这个pr中来，只好直接贴在这了,哪位老大辛苦把代码加到mssql_z_model_test.go文件中吧)

func Test_Model_AllAndCount(t *testing.T) {
	table := createInitTable()
	defer dropTable(table)

	gtest.C(t, func(t *gtest.T) {
		result, total, err := db.Model(table).Order("id").Limit(0, 3).AllAndCount(false)
		t.Assert(err, nil)

		t.Assert(len(result), 3)
		t.Assert(total, TableSize)
	})
}

func Test_Model_ScanAndCount(t *testing.T) {
	table := createInitTable()
	defer dropTable(table)

	gtest.C(t, func(t *gtest.T) {
		type User struct {
			Id         int
			Passport   string
			Password   string
			NickName   string
			CreateTime gtime.Time
		}

		users := make([]User, 0)
		total := 0

		err := db.Model(table).Order("id").Limit(0, 3).ScanAndCount(&users, &total, false)
		t.Assert(err, nil)

		t.Assert(len(users), 3)
		t.Assert(total, TableSize)
	})
}

2023-11-15 01:24 UTC, zcyc commented
> contrib/drivers/mssql/mssql_z_model_test.go新加的单元测试代码如下：(不知道怎么把新变动的文件加到这个pr中来，只好直接贴在这了,哪位老大辛苦把代码加到mssql_z_model_test.go文件中吧)
> 
> func Test_Model_AllAndCount(t *testing.T) { table := createInitTable() defer dropTable(table)
> 
> ```
> gtest.C(t, func(t *gtest.T) {
> 	result, total, err := db.Model(table).Order("id").Limit(0, 3).AllAndCount(false)
> 	t.Assert(err, nil)
> 
> 	t.Assert(len(result), 3)
> 	t.Assert(total, TableSize)
> })
> ```
> 
> }
> 
> func Test_Model_ScanAndCount(t *testing.T) { table := createInitTable() defer dropTable(table)
> 
> ```
> gtest.C(t, func(t *gtest.T) {
> 	type User struct {
> 		Id         int
> 		Passport   string
> 		Password   string
> 		NickName   string
> 		CreateTime gtime.Time
> 	}
> 
> 	users := make([]User, 0)
> 	total := 0
> 
> 	err := db.Model(table).Order("id").Limit(0, 3).ScanAndCount(&users, &total, false)
> 	t.Assert(err, nil)
> 
> 	t.Assert(len(users), 3)
> 	t.Assert(total, TableSize)
> })
> ```
> 
> }

在你pr的分支继续commit就会自动加到pr中。

2023-11-15 02:30 UTC, wlqe commented
@zcyc thanks. Resubmitted.

2023-11-16 12:14 UTC, gqcn approved these changes

2023-11-16 12:15 UTC, merged