优化cmd gf在Windows下的效率，并改进开启debug后的日志信息显示更详尽
gogf/gf pull request #3174
Opened 2023-11-24 09:29 UTC by hailaz

2023-11-29 11:16 UTC, gqcn requested changes

2023-11-29 11:16 UTC, gqcn commented on cmd/gf/internal/utility/mlog/mlog.go
> +		logger.SetFlags(logger.GetFlags() | glog.F_FILE_LONG)
打印提示给使用端，有必要打印源文件路径吗？

2023-11-29 11:16 UTC, gqcn commented on cmd/gf/internal/utility/mlog/mlog.go
> +func Errorf(format string, v ...interface{}) {
`cli`中并没有使用，`mlog`在`cli`只是作为提示库使用，不建议增加。

2023-11-30 07:44 UTC, hailaz commented on cmd/gf/internal/utility/mlog/mlog.go
> +func Errorf(format string, v ...interface{}) {
好的，我去掉。

2023-11-30 10:59 UTC, gqcn approved these changes

2023-11-30 10:59 UTC, merged