fix: #2938
gogf/gf pull request #3178
Opened 2023-11-27 09:42 UTC by hailaz

fix #2938
如果需要body支持复读，可以在前置中间件中使用`r.MakeBodyRepeatableRead(true)`
```go
s.Group("/", func(group *ghttp.RouterGroup) {
		group.Middleware(func(r *ghttp.Request) {
			fmt.Println("middleware")
			r.MakeBodyRepeatableRead(true)
			r.Middleware.Next()
		})
		group.Middleware(ghttp.MiddlewareHandlerResponse)
		group.Bind(cUpload{})
	})
```

2023-11-30 11:08 UTC, gqcn requested changes

2023-11-30 11:08 UTC, gqcn commented on net/ghttp/ghttp_z_unit_feature_config_test.go
> +			),
为什么要改为`strings.Contains`判断呢？

2023-12-01 07:13 UTC, hailaz commented on example/httpserver/upload_file/main.go
> +	fmt.Println(req.Msg)
我删一下，忘了

2023-12-01 07:21 UTC, hailaz commented on net/ghttp/ghttp_z_unit_feature_config_test.go
> +			),
因为r.MakeBodyRepeatableRead(true)删掉后，错误的warp内容不一样了。但底层的http: request body too large是不变的

2023-12-20 12:25 UTC, merged