fix #2746
gogf/gf pull request #3309
Opened 2024-02-07 15:07 UTC by oldme-git

fixed #2746

2024-02-07 15:17 UTC, oldme-git commented
@gqcn First, please update `loads/mariadb:10.4`

2024-02-23 08:36 UTC, hailaz approved these changes

2024-02-27 11:41 UTC, gqcn requested changes

2024-02-27 11:41 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +	if dbType == "mariadb" {
- 建议将核心逻辑分开，例如使用`doTableFieldsMysql`和`doTableFiledsMariadb`方法来做区分。
- 通过`switch...case...`来分开判断调用不同的方法实现。
- 将公共逻辑抽象为公共方法。

2024-02-27 11:41 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +		// if filed exists in mariaJsonFiledName, replace its Type with "json"
`filed` -> `field`?

2024-02-27 11:41 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +		mariaJsonFiledName = gset.New(false)
`mariaJsonFiledName` -> `mariaJsonFieldNameSet`?

2024-02-29 02:31 UTC, houseme commented
> fixed #2746
> 
> **Dear reviewer:** 修复 mariaDb `gf gen dao` 的 `json` 字段识别为 `string` 问题
> 
> # 实现说明
> 在 `mysql driver` 中增加对 `mariaDb` 的识别，**如果是，则使用 mariaDb 特有的 `json` 字段类型的判断方式**，用以和 `mysql json` 做出区分

MariaDB 中json字段存的就是`longtext`类型，不是`json`

2024-02-29 03:04 UTC, oldme-git commented
> > fixed #2746
> > **Dear reviewer:** 修复 mariaDb `gf gen dao` 的 `json` 字段识别为 `string` 问题
> > # 实现说明
> > 在 `mysql driver` 中增加对 `mariaDb` 的识别，**如果是，则使用 mariaDb 特有的 `json` 字段类型的判断方式**，用以和 `mysql json` 做出区分
> 
> MariaDB 中json字段存的就是`longtext`类型，不是`json`

MariaDB 存 json 字段的确时 `longtext`，但是会在其上加上 `json` 约束：https://mariadb.com/resources/blog/using-json-in-mariadb/

2024-02-29 03:13 UTC, houseme commented
```sql
CREATE TABLE locations (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,  
    type CHAR(1) NOT NULL,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL,
    attr LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL 
    CHECK (JSON_VALID(`attr`)
     PRIMARY KEY (id)
);
```

请注意， attr 列的数据类型是 LONGTEXT 。除此之外，您会发现字符集和排序规则字段中添加了一些约束。然而，最重要的是 CHECK 约束，它指示当 attr 中的数据通过插入或更新进行修改时将执行的函数。
JSON_VALID() 函数是一个预定义函数，用于接收 JSON 数据（字符串形式）并验证其是否有效。有效含义正确形成的 JSON 数据。

2024-02-29 11:45 UTC, gqcn requested changes

2024-02-29 11:45 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +	return nil, gerror.New("The database type is not mysql or mariadb")
很多数据库支持`mysql`协议，并且当前`driver`包同时也支持`tidb`，我建议将`mysql`的`dbType`作为`default`处理，不报错误。

2024-02-29 11:45 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +		fmt.Sprintf(`SELECT CONSTRAINT_NAME as filedName, CHECK_CLAUSE as filedCheck FROM information_schema.CHECK_CONSTRAINTS WHERE TABLE_NAME = '%s'`, table),
`filed` -> `field`
建议全局代码中再搜索一下有无写错的地方。

2024-03-04 12:25 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +var (
缺少`sql`语句格式化处理，否则`sql`打印到日志中会有多行输出，请参考：https://github.com/gogf/gf/blob/8266a16b4e9a957bc910e443e448de88fd1b9e75/contrib/drivers/mssql/mssql_table_fields.go#L50

2024-03-04 12:26 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +		sql        string
建议调整下变量`sql`的名称，容易和标准库的`sql`包冲突，例如`tableFieldsSql`?

2024-03-04 12:29 UTC, gqcn commented on cmd/gf/internal/cmd/testdata/issue/2746/sql.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
单测`sql`语句缺少`json_valid`约束？

2024-03-04 12:31 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +	( CASE WHEN ch.CHECK_CLAUSE LIKE 'json_valid%%' THEN 'json' ELSE c.COLUMN_TYPE END ) AS 'Type',
这个获取表结构的`sql`有些复杂，能否通过`SHOW FULL COLUMNS FROM`语句获取表结构，如果查询表结构的结果带有`json_valid`约束语句，通过代码来判断`json_valid`约束？

2024-03-05 01:51 UTC, oldme-git commented on cmd/gf/internal/cmd/testdata/issue/2746/sql.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8;
@gqcn 创建表时，可以使用和 `mysql` 相同的 `sql` 语句。但如果字段的类型为 `json`，最终创建到 `mariadb` 中就是带有 `json_valid` 的 `longtext` 类型，这点区别与 `mysql`

2024-03-05 01:58 UTC, oldme-git commented on contrib/drivers/mysql/mysql_table_fields.go
> +	( CASE WHEN ch.CHECK_CLAUSE LIKE 'json_valid%%' THEN 'json' ELSE c.COLUMN_TYPE END ) AS 'Type',
@gqcn 通过 `SHOW FULL COLUMNS FROM` 语句拿不到 `json_valid` 约束，如果强行用，`json_valid` 约束需要多去查一次数据库
![20240305095831](https://github.com/gogf/gf/assets/45782393/1e75b6db-c53f-438a-881b-7134dfc3a0a3)

2024-03-05 12:55 UTC, gqcn commented on contrib/drivers/mysql/mysql_table_fields.go
> +		formatSqlTmp(tableFieldsSql),
可以考虑其他`driver`的用法，在`init`包初始化方法中处理一次即可，不用每次在`TableFields`方法调用时`format`一下。

2024-03-05 12:57 UTC, gqcn commented on contrib/drivers/mysql/mysql.go
> +func formatSqlTmp(sqlTmp string) string {
我发现好几个`driver`都定义有这个方法，代码看起来挺冗余的，要不提出来定义到`gdb`包方法`gdb_func.go`中复用吧，比如方法可以定义为`FormatMultiLineSqlToSingle`见名知意。

2024-03-06 11:07 UTC, gqcn approved these changes

2024-03-06 11:07 UTC, merged