enhance: gproc.signal enhance #3325
gogf/gf pull request #3326
Opened 2024-02-25 08:30 UTC by Agzer0

2024-02-27 13:26 UTC, gqcn commented
@Agzer0 Would you please give a brief description about your changes?

2024-02-28 02:52 UTC, Agzer0 commented
Implemented the following changes for gogf#3325:

1. Used sync.Once to restrict Listen() so that it is executed only once, avoiding multiple executions of Listen() that could lead to repetitive triggering of handlers.
2. Used waitChan to ensure that Listen() remains blocking.
3. In AddSigHandlerShutdown() and AddSigHandler(), invoked signal.Notify() everytime so that even if signals are added after Listen(), they can still be registered and listened to.

2024-02-29 11:36 UTC, gqcn requested changes

2024-02-29 11:36 UTC, gqcn commented on os/gproc/gproc_z_signal_test.go
> +package gproc
Please add copyright comments in the top of source file.

2024-03-04 12:09 UTC, gqcn approved these changes

2024-03-04 12:10 UTC, merged