fix #3330
gogf/gf pull request #3339
Opened 2024-02-29 08:12 UTC by oldme-git

fixed #3330

**Dear reviewer:**
PgSQL 查询字段信息时会错误识别主键，最终导致 `gdb.model.wherepri` 有bug

# 修复方案
编写正确的 SQL 语句正确的识别主键
` Select ... ( CASE WHEN d.contype = 'p' THEN 'pri' WHEN d.contype = 'u' THEN 'uni' ELSE'' END ) AS KEY from ...`

2024-03-04 12:43 UTC, gqcn approved these changes

2024-03-04 12:47 UTC, gqcn requested changes

2024-03-04 12:47 UTC, gqcn commented on contrib/drivers/pgsql/pgsql_z_unit_issue_test.go
> +	})
@oldme-git 感觉这个单测有些简单，由于表只有`1`条数据，即便`WherePri`不起作用，`One`方法查询也能查询出这条数据。建议插入`10`条数据，并在循环中使用`WherePri`查询每条查询是否符合预期。

2024-03-04 13:04 UTC, oldme-git commented on contrib/drivers/pgsql/pgsql_z_unit_issue_test.go
> +	})
@gqcn 不是的，强哥，wherePri + one，结果如不符合预期，查询出来的值便是空的，单测会失败，和数据的条数没有关系

2024-03-05 13:15 UTC, gqcn requested changes

2024-03-05 13:15 UTC, gqcn commented on contrib/drivers/pgsql/pgsql_z_unit_issue_test.go
> +	})
你这里除了`WherePri`方法就没其他条件方法了，总感觉这个方法失效后就变成了```SELECT * FROM xxx LIMIT 1```语句了。不确定的地方为了确保严谨性，就完善一下单测吧。

2024-03-06 11:19 UTC, gqcn approved these changes

2024-03-06 11:19 UTC, merged