fix http client trace gzip content
gogf/gf pull request #3342
Opened 2024-03-01 08:40 UTC by seth-shi

more screen string field contains invalid UTF-8 on gzip content
safeContent for httpRequestBody and httpResponseBody

2024-03-04 13:08 UTC, gqcn requested changes

2024-03-04 13:08 UTC, gqcn commented on net/gtrace/gtrace_content.go
> +// SafeContent safe trace content
```go
// SafeContent cuts and returns given content by `MaxContentLogSize`. 
// It appends string `...` to the tail of the result if the content size is greater than `MaxContentLogSize`.
```

2024-03-04 13:08 UTC, gqcn commented on net/gclient/gclient_tracing_tracer.go
> +		ct.span.SetStatus(codes.Error, fmt.Sprintf(`safe req content:%+v`, err))
It is not necessary outputting error stack content to span status.
`ct.span.SetStatus(codes.Error, fmt.Sprintf(`converting safe content failed: %s`, err.String()))`

2024-03-04 15:20 UTC, seth-shi commented
tomorrow fix

2024-03-05 01:39 UTC, houseme commented
建议测试一下内容比较的，防止卡住，以及文件上传的

2024-03-05 01:43 UTC, seth-shi commented
> 建议测试一下内容比较的，防止卡住，以及文件上传的

OK，我加个大 body 测试，现在的测试失败是什么原因导致的？

2024-03-05 02:36 UTC, houseme commented
> > 建议测试一下内容比较的，防止卡住，以及文件上传的
> 
> OK，我加个大 body 测试，现在的测试失败是什么原因导致的？

你可以搜索一下issues的记录，有同学反馈过，卡住的情况

2024-03-05 02:52 UTC, seth-shi commented
> > > 建议测试一下内容比较的，防止卡住，以及文件上传的
> > 
> > 
> > OK，我加个大 body 测试，现在的测试失败是什么原因导致的？
> 
> 你可以搜索一下issues的记录，有同学反馈过，卡住的情况

感觉如果判断是 HTTP 文件上传是不是直接不记录更好.

2024-03-05 02:58 UTC, houseme commented
> > > > 建议测试一下内容比较的，防止卡住，以及文件上传的
> > > 
> > > 
> > > OK，我加个大 body 测试，现在的测试失败是什么原因导致的？
> > 
> > 
> > 你可以搜索一下issues的记录，有同学反馈过，卡住的情况
> 
> 感觉如果判断是 HTTP 文件上传是不是直接不记录更好.

我自己是没有碰到过这种问题，只有trace上报服务器配置错误，导致启动不起来的问题。

2024-03-07 10:57 UTC, gqcn commented on net/gtrace/gtrace_content.go
> +func SafeContent(data []byte, header http.Header) (string, error) {
@seth-shi Do not forget the grpc part.

2024-03-12 14:12 UTC, seth-shi commented
> @seth-shi If this pr is ready again, please AT me.

it`s already ok, is there anything need to fix ?

2024-03-13 11:19 UTC, gqcn approved these changes

2024-03-13 11:21 UTC, merged