enhance: support save for Oracle
gogf/gf pull request #3364
Opened 2024-03-12 08:22 UTC by oldme-git

**Dear review:**
增加对 `Oracle` 的 `gdb.save` 支持

并且改善了一些其他地方：
- 统一 `Oracle` 单测函数名为大写下划线
- 增加 `Test_Model_Replace for Oralce` 单测
- 改善 `SQLite` 和 `PgSQL` 的 `return err`：增加 `gcode`
- 改善 `gbd.FormatMultiLineSqlToSingle` 函数入参的变量名称为 `sql`，这样有益 IDEA 的代码提示

2024-03-12 12:37 UTC, gqcn requested changes

2024-03-12 12:37 UTC, gqcn commented on database/gdb/gdb_func.go
> +	return sql
使用`sqlTmp`的变量名称是因为`sql`参数名称和标准库的`sql`包冲突。

2024-03-12 12:37 UTC, gqcn commented on contrib/drivers/sqlite/sqlite_format_upsert.go
> +			gcode.CodeInvalidRequest, `Please specify conflict columns`,
看起来应该是`gcode.CodeInvalidParameter`?

2024-03-12 12:37 UTC, gqcn commented on contrib/drivers/pgsql/pgsql_format_upsert.go
> +			gcode.CodeInvalidRequest, `Please specify conflict columns`,
看起来应该是`gcode.CodeInvalidParameter`?

2024-03-12 12:37 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_save.go
> +			gcode.CodeInvalidRequest, `Please specify conflict columns`,
- 看起来应该是`gcode.CodeInvalidParameter`?
- 错误信息是否没有对应修改？
- 必须要指定`OnConflict`参数？

2024-03-12 12:37 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_save.go
> +			gcode.CodeInvalidRequest, `Save operation list is empty by oracle driver`,
看起来应该是`gcode.CodeInvalidParameter`?

2024-03-12 12:37 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_save.go
> +func (d *Driver) doSave(ctx context.Context,
一个`go`文件实现一个`gdb.DB`的接口，因此这个`doSave`方法建议维护到`oracle_do_insert.go`源文件中。

2024-03-12 12:45 UTC, oldme-git commented on database/gdb/gdb_func.go
> +	return sql
我看其他的gdb函数也都使用的 `sql` 哦，这里的 `sql` 好像不冲突的

2024-03-12 12:51 UTC, oldme-git commented on contrib/drivers/oracle/oracle_do_save.go
> +			gcode.CodeInvalidRequest, `Please specify conflict columns`,
错误信息是正确的，新的全部改用了 `CodeMissingParameter`。之前的 `CodeInvalidRequest` 也是抄的其他包的🤣。看来 gf 的代码还有不小的进步空间。

所有的数据库，除 `mysql` 和 `clickhouse` 外，`save` 操作都需要指定 `OnConflict`

2024-03-12 14:05 UTC, gqcn requested changes

2024-03-12 14:05 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_save.go
> +package oracle
空文件要不就删掉？

2024-03-12 14:05 UTC, gqcn commented on database/gdb/gdb_func.go
> +	return sql
@oldme-git 这个函数我发现有个问题，由于是公开函数了，内部不应该`panic`，应当返回`error`，即便需要`panic`也应该在调用的地方执行`panic`。

2024-03-12 16:09 UTC, oldme-git commented on database/gdb/gdb_func.go
> +	return sql
@gqcn Please show #3368

2024-03-13 11:28 UTC, gqcn requested changes

2024-03-13 11:28 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_insert.go
> +		conflictKeySet = gset.New(true)
`conflictKeySet = gset.New()` 没有必要使用并发安全的锁。

2024-03-13 11:28 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_insert.go
> +		valueCharL, valueCharR = "'", "'"
统一在一个地方维护安全符号，这里建议使用统一的常量，或者使用`GetChars`方法获取。

2024-03-13 11:37 UTC, oldme-git commented on contrib/drivers/oracle/oracle_do_insert.go
> +		valueCharL, valueCharR = "'", "'"
charL 是 `'` 和 valueCharL 的 `"` 不同，valueCharL 不是安全符号，

2024-03-13 11:43 UTC, gqcn approved these changes

2024-03-13 12:11 UTC, merged