enhance: `Save` operation support for `mssql`
gogf/gf pull request #3365
Opened 2024-03-12 08:53 UTC by oldme-git

2024-03-20 12:03 UTC, gqcn requested changes

2024-03-20 12:03 UTC, gqcn commented on contrib/drivers/mssql/mssql_do_insert.go
> +			saveValue = t.Format(`2006-01-02 15:04:05`)
为什么要将时间对象转换为字符串呢，这样会丢失时间精度。底层`mssql driver`不支持时间对象输入吗？

2024-03-20 12:03 UTC, gqcn commented on contrib/drivers/mssql/mssql_do_insert.go
> +		return d.doSave(ctx, link, table, list, option)
请同时更新注释：https://github.com/gogf/gf/blob/040118b7c679328cb96fe1b8bfd7bf8bf8d7e3aa/contrib/drivers/mssql/mssql.go#L10

2024-03-21 02:34 UTC, oldme-git commented on contrib/drivers/mssql/mssql_do_insert.go
> +			saveValue = t.Format(`2006-01-02 15:04:05`)
转成字符串在代码中容易处理，现在格式化成 `ISO 8601` 格式了，这样就不会丢失精度了

2024-03-25 14:16 UTC, gqcn requested changes

2024-03-25 14:16 UTC, gqcn commented on contrib/drivers/mssql/mssql_do_insert.go
> +	}
严重：
- 为什么要将`sql+args`拼成`sql`语句来执行，而不是使用`sql+args`的预处理模式呢？这也是标准库sql支持的处理模式。
- 使用拼接字符串的模式不会出现`sql`注入风险吗？

2024-04-01 11:18 UTC, gqcn approved these changes

2024-04-01 11:18 UTC, merged