fix: To fix a small loophole, you need to set true for short tags
gogf/gf pull request #3393
Opened 2024-03-17 09:53 UTC by wln732

<p>
我在重新实现gconv.Struct的时候，测试发现gcmd下面的测试跑不过，发现了一个小bug<br>
当设置的字段是bool值并且是空值的时候，没有给短标签设置值
</p>

2024-03-18 14:08 UTC, wln732 commented
解析gcmd的参数时，需要添加name和short tag不然参数和字段名字对不上的时候，将无法正确解析

2024-03-19 11:35 UTC, gqcn commented
@wln732 The ci failed.

2024-03-19 12:11 UTC, wln732 commented
> @wln732 The ci failed.

@gqcn 测试没问题，那些报错的地方都是断言非空的err
![viewtest](https://github.com/gogf/gf/assets/49137144/3a656e93-9117-4057-9d2f-686faf2942de)

2024-03-20 11:56 UTC, gqcn requested changes

2024-03-20 11:56 UTC, gqcn commented on os/gcmd/gcmd_command_object.go
> +				err = gconv.StructTag(data, inputObject.Addr().Interface(), "name,short")
请补充对应修改的单测。

2024-03-21 02:49 UTC, closed without merging