fix: fsnotify watcher panics when closing
gogf/gf pull request #3399
Opened 2024-03-19 12:01 UTC by wlynxg

fix: https://github.com/gogf/gf/issues/3396

2024-03-20 11:51 UTC, gqcn requested changes

2024-03-20 11:51 UTC, gqcn commented on os/gfsnotify/gfsnotify_watcher.go
> +	w.events.Close()
为什么修改这里呢？我看你之前的`pr`只需要在`watcher`的`channel`那里判断下`ok`就行了呀？为什么要把之前的pr删掉呢？

2024-03-29 02:09 UTC, gqcn commented
@wlynxg Any updates?

2024-03-29 02:12 UTC, wlynxg commented
> @wlynxg Any updates?

关于调换两个 `channel` 的提议您的看法呢

2024-04-07 06:11 UTC, gqcn approved these changes

2024-04-07 06:12 UTC, merged