Improve the performance by reducing duplicated reflect usage on the s…
gogf/gf pull request #3413
Opened 2024-03-21 09:22 UTC by wln732

<p>
<ol>
<li>请求开始的时候，直接反射验证数据是否合法,并返回reflect.Value，后续所有操作可以不用重复反射对象</li>
<li>修正了测试 ghttp_z_unit_feature_request_struct_test.go：510 </li>
</ol>
</p>

2024-03-21 14:04 UTC, gqcn commented
@wln732 The ci fails.

2024-03-25 14:03 UTC, gqcn commented
涉及较核心逻辑代码调整，需要花点时间`review`。

2024-03-25 23:42 UTC, wln732 commented
> 涉及较核心逻辑代码调整，需要花点时间`review`。
========
其实设置default 和in tag 那里可以直接用反射赋值了，不需要再去判断data里有没有同名的，这样实现也很直观，如果data中设置了值，那后面再走gocnv.Struct这里赋值就好了

2024-04-10 03:43 UTC, oldme-git approved these changes

2024-04-24 13:13 UTC, gqcn requested changes

2024-04-24 13:14 UTC, gqcn commented
@wln32 这块代码看起来有点花时间，能否描述下你的改动思路？

2024-04-24 13:50 UTC, wln32 commented
> @wln32 这块代码看起来有点花时间，能否描述下你的改动思路？

先放放吧，后面在更新，
其实这块的代码，可以先做请求校验，然后在用gconv做赋值，还有defaut和header那里也可以再优化优化

2024-04-24 13:51 UTC, wln32 commented on net/ghttp/ghttp_request_param_request.go
> +		}
这里当时考虑的是，前端传的空值没啥意义，所以就把他删掉了

2024-05-30 13:33 UTC, gqcn commented
> > @wln32 这块代码看起来有点花时间，能否描述下你的改动思路？
> 
> @gqcn 先放放吧，后面在更新， 其实这块的代码，可以先做请求校验，然后在用gconv做赋值，还有defaut和header那里也可以再优化优化

好的，这个`pr`我过段时间就会来看看，不过由于需要持续`review`但经常被打断，那我优先去看看你对`http server`路由的优化吧。

2024-10-16 02:33 UTC, closed without merging