Feature: cmd init module
gogf/gf pull request #3425
Opened 2024-03-25 13:48 UTC by houseme

https://github.com/gogf/template-mono/pull/2 

建议同步更新 template-mono 的内容

2024-03-28 14:24 UTC, gqcn requested changes

2024-03-28 14:24 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_init.go
> +	Path   string `name:"path" short:"p" brief:"project creation directory"`
你这里是想要实现自定义设置`go module`名称？建议使用`Module`参数，缩写为`g`, 描述为`custom go module name`。
看了下这个源文件只需要实现`135`行的文本替换即可，其他地方可以不用修改。

2024-03-28 14:59 UTC, houseme commented on cmd/gf/internal/cmd/cmd_init.go
> +	Path   string `name:"path" short:"p" brief:"project creation directory"`
好的

2024-04-01 11:12 UTC, gqcn requested changes

2024-04-01 11:12 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_init.go
> +		in.Module = in.Name
使用`gfile.Basename(gfile.RealPath(in.Name)))`，其中`in.Name`可能为`.`

2024-04-01 13:30 UTC, houseme commented on cmd/gf/internal/cmd/cmd_init.go
> +		in.Module = in.Name
done

2024-04-02 06:05 UTC, gqcn approved these changes

2024-04-02 06:05 UTC, merged