imprpve: gbd.save of `Oracle` and `Dm` driver.
gogf/gf pull request #3426
Opened 2024-03-26 07:17 UTC by oldme-git

2024-03-28 14:17 UTC, gqcn requested changes

2024-03-28 14:17 UTC, gqcn commented on contrib/drivers/dm/dm_do_insert.go
> +		queryValues  = make([]interface{}, oneLen)
是否使用`saveHolders/saveValues`更贴切语意一些？

2024-03-28 14:17 UTC, gqcn commented on contrib/drivers/oracle/oracle_do_insert.go
> +		queryValues[index] = value
同上。

2024-03-28 14:56 UTC, oldme-git commented on contrib/drivers/dm/dm_do_insert.go
> +		queryValues  = make([]interface{}, oneLen)
这里的 queryHolders 和 queryValus 其实是在子句中的.

2024-03-29 02:57 UTC, oldme-git commented on contrib/drivers/dm/dm_do_insert.go
> +		queryValues  = make([]interface{}, oneLen)
Done

2024-04-01 11:08 UTC, gqcn approved these changes

2024-04-01 11:08 UTC, merged