feat(gvalid): add new rules for gvalid
gogf/gf pull request #3455
Opened 2024-04-04 16:35 UTC by cococolanosugar

added rules:
1. required-if-any-eq Required if any given field and its value are equal.
2. required-if-all-eq: Required if all given field and its value are equal.

2024-04-07 11:33 UTC, gqcn commented
@cococolanosugar 
Hello, thanks for your contribution for the project! 
The being added rule `required-if-any-eq` performs exactly as the existing rule `required-if`. It's better update the comments of the rule `required-if` instead of adding new rule.
The new rule `required-if-all-eq` is awsome, but it's better using name `required-if-all` which would be related to the onther rule `reuired-if` for the users.

2024-04-08 15:02 UTC, cococolanosugar commented
@gqcn 
Hi, thanks for your advice. I have updated the commits. If you have time, please review it.

2024-04-09 13:15 UTC, gqcn commented
@cococolanosugar Hello, I've made a pr for some improvement for your pr hah https://github.com/cococolanosugar/gf/pull/1

2024-04-10 12:27 UTC, gqcn requested changes

2024-04-10 12:27 UTC, gqcn commented on util/gvalid/internal/builtin/builtin_required_if_all.go
> +type RuleRequiredIfAllEq struct{}
`RuleRequiredIfAllEq` -> `RuleRequiredIfAll`

2024-04-10 12:27 UTC, gqcn commented on util/gvalid/gvalid_z_example_feature_rule_test.go
> +		MoreInfo string `v:"required-if-all:id,1,age:18" dc:"Your more info"`
`required-if-all:id,1,age,18`

2024-04-11 11:44 UTC, gqcn approved these changes

2024-04-11 11:45 UTC, merged