`gf gen ctrl` use AST to get original info
gogf/gf pull request #3470
Opened 2024-04-10 03:31 UTC by oldme-git

2024-04-10 12:10 UTC, gqcn requested changes

2024-04-10 12:10 UTC, gqcn commented on cmd/gf/internal/utility/ast/ast.go
> +func GetStructs(filePath string) (structsInfo map[string]string, err error) {
由于`map`是无序的，可能执行两次后生成代码顺序不一致，造成有差异，这里最好使用`slice`类型返回。

2024-04-10 12:10 UTC, gqcn commented on cmd/gf/internal/utility/ast/ast.go
> +func GetInterfaces(filePath string) (interfacesInfo map[string][]string, err error) {
同上。此外，如果该方法还没使用建议不增加，而是放到需要使用的`pr`中一起提交。

2024-04-10 12:37 UTC, oldme-git commented on cmd/gf/internal/utility/ast/ast.go
> +func GetStructs(filePath string) (structsInfo map[string]string, err error) {
无序的是 AST，AST对所有的节点遍历时无需的，如果必须排序，需要在遍历后进行排序

2024-04-11 11:15 UTC, gqcn approved these changes

2024-04-11 11:15 UTC, merged