fix: missing file closding when printing downloading percent of gf cli file for command `gf up`
gogf/gf pull request #3483
Opened 2024-04-12 09:33 UTC by testwill

2024-04-15 10:04 UTC, hailaz approved these changes

2024-04-15 12:06 UTC, gqcn requested changes

2024-04-15 12:06 UTC, gqcn commented on cmd/gf/internal/utility/utils/utils_http_download.go
> +			defer file.Close()
It'd better move this file `Open` logic out side of for loop.

2024-04-16 11:49 UTC, gqcn approved these changes

2024-04-16 11:49 UTC, merged