Improved: Optimized call flow when using gen ctrl -merge
gogf/gf pull request #3490
Opened 2024-04-16 03:36 UTC by wln32

改进：使用gen ctrl -merge参数时，可以一次将所有待生成的ctrl写入到文件，而不是分次写入。

2024-04-16 11:47 UTC, gqcn requested changes

2024-04-16 11:47 UTC, gqcn commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	if err = gfile.PutContentsAppend(methodFilePath, contents.String()); err != nil {
这里可能在多执行几次命令后，源码文件中存在重复生成内容，是否使用`gfile.PutContents`更合适一些？

2024-04-16 11:47 UTC, gqcn commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	for i := 0; i < len(items); i++ {
这里是否使用`for...range...`更优雅一些？

2024-04-16 11:47 UTC, gqcn commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +
无意义空行。

2024-04-16 12:28 UTC, wln32 commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +
> 无意义空行。

这里还好吧，我不喜欢下面的和函数声明粘到一起去

2024-04-16 12:31 UTC, wln32 commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	for i := 0; i < len(items); i++ {
> 这里是否使用`for...range...`更优雅一些？

这里确实可以用for range好点。
>这里用了索引是因为，最开始的时候，我在上面判断文件不存在的时候，用的之前的常量(会把package impor还有第一个ctrl都加进去)，然后这里索引是1开始

2024-04-16 13:01 UTC, wln32 commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	if err = gfile.PutContentsAppend(methodFilePath, contents.String()); err != nil {
> 这里可能在多执行几次命令后，源码文件中存在重复生成内容，是否使用`gfile.PutContents`更合适一些？

我在仔细看看

2024-04-17 04:05 UTC, wln32 commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	if err = gfile.PutContentsAppend(methodFilePath, contents.String()); err != nil {
> 这里可能在多执行几次命令后，源码文件中存在重复生成内容，是否使用`gfile.PutContents`更合适一些？

@gqcn 目前没有发现重复生成的问题，倒是发现了另外一个问题，就是使用merge参数后，比如
`/api/hello/v1` 目录下有两个文件 f1.go f2.go 每个文件分别都有``两对Req/Res结构体``
之前的逻辑没有判断文件名，生成的ctrl（一共有4个）会全部写入到一个文件中去，
所有我又重写了原来的逻辑，加上了文件名的判断，会分别生成 `hello_v1_f1.go`  `hello_v1_f2.go`
每个里面都有两个ctrl

---
关于重复生成的
文件路径： `cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go`
当代码走到 `(*controllerGenerator).Generate` 时，需要生成的ctrl都是不存在的，
只有当文件不存在时可以使用`gfile.PutContents`
我在本地测试了一下，使用gf gen ctrl -m命令和我的测试结果是一致的，测试代码如下
```go
// 可以随便找个项目测试下，
// 测试前用git保存下，然后创建两个分支
// 分支1： 使用gf gen ctrl -m 保存提交，切换到另一个分支
// 分支2： 拉取我这个分支的代码，运行下面的测试。保存提交
// 运行完比对下两次提交
func Test_Gen_Ctrl_UseMerge(t *testing.T) {
	gtest.C(t, func(t *gtest.T) {
		var (
   
			ctrlPath  = "本地路径\\internal\\controller"
			apiFolder = “本地路径\\api"
			in        = genctrl.CGenCtrlInput{
				SrcFolder: apiFolder,
				DstFolder: ctrlPath,
				Merge: true,
			}
		)

		err := gfile.Mkdir(ctrlPath)
		t.AssertNil(err)

		for i := 0; i < 100; i++ {
			_, err = genctrl.CGenCtrl{}.Ctrl(ctx, in)
			t.AssertNil(err)
		}

	})
}
```

2024-04-17 13:51 UTC, gqcn commented on cmd/gf/internal/cmd/genctrl/genctrl_generate_ctrl.go
> +	for _, item := range items {
@wln32 给个小建议呢，变量命名仅可能定义有具象的名称，不用在意长短，能见名知意最好。这样更利于长远维护时不同的贡献者对代码的快速理解，对于`reviewer`来讲也会更友好一些。

举个简单的例子，这里的`items`使用`apiItems`的名称会更优雅一些，不用上下文切换去理解变量名称。其实这个`apiItem`当时最好也定义为`apiDefinitionItem`会更好一些。

2024-04-17 13:52 UTC, gqcn approved these changes

2024-04-18 12:12 UTC, merged