gf gen dao support type mapping for specific field of table
gogf/gf pull request #3498
Opened 2024-04-19 08:55 UTC by CyJaySong

gf gen dao support type mapping for specific field of table

2024-04-22 12:20 UTC, gqcn commented
Interesting feature! 
@hailaz @houseme @DGuang21 @oldme-git @wln32 Hi guys, would you please take a look together?

2024-04-22 12:30 UTC, hailaz commented
支持，我之前有想过，之前单纯指定类型并不够灵活，应该表名加字段加类型这样更好。现在有人实现了(¯▽¯)👍

2024-04-22 12:55 UTC, wln32 approved these changes

2024-04-23 03:23 UTC, oldme-git approved these changes

2024-04-23 14:39 UTC, hailaz commented
你们说有没有可能和原来的TypeMapping结合到一起，不过这样的使用难度会提高不少。

2024-04-23 14:40 UTC, hailaz approved these changes

2024-04-24 00:45 UTC, CyJaySong commented
> 你们说有没有可能和原来的TypeMapping结合到一起，不过这样的使用难度会提高不少。

@hailaz  TypeMapping 适用于按照数据库字段类型批量映射，FieldMapping适用于表字段特定指定类型。比如，json 类型，我们为了开发方便会建一个结构体进行映射

2024-04-24 02:31 UTC, houseme commented
TypeMapping 碰到必须优先引入这个依赖才可以生成dao成功，如果在表创建时在引入会出现失败的情况，建议不上这一块的test

2024-04-24 03:12 UTC, CyJaySong commented
> TypeMapping 碰到必须优先引入这个依赖才可以生成dao成功，如果在表创建时在引入会出现失败的情况，建议不上这一块的test

执行cli中执行shell 的问题，PR中修复了的

2024-04-24 11:30 UTC, gqcn requested changes

2024-04-24 11:30 UTC, gqcn commented on cmd/gf/internal/cmd/gendao/gendao.go
> +			  type:   map[string]string
这里的示例不是很好理解，建议修改为：
```yaml
fieldMapping:
    table_name.field_name:
        type:   decimal.Decimal
        import: github.com/shopspring/decimal
```

2024-04-25 11:18 UTC, gqcn approved these changes

2024-04-25 11:19 UTC, merged