cmd/gf: add gf init app/mono-app -ma
gogf/gf pull request #3550
Opened 2024-04-27 13:35 UTC by oldme-git

**Dear reviewer:**
新增微服务大仓模式下初始化应用的命令：
`gf init app/mono-app -ma`

如果合并 PR 后，需要在社区仓库中创建 `template-mono-app`。然后把模板代码推上去: https://github.com/oldme-git/template-mono-app

2024-04-27 23:51 UTC, houseme commented
原来不是有一个多模块的创建吗？

2024-04-28 01:21 UTC, oldme-git commented
> 原来不是有一个多模块的创建吗？

是说 `gf init xxx -m` 吗，这个命令是为大仓模式创建一个子服务

2024-04-29 11:09 UTC, gqcn commented
@oldme-git 你这个模板内容从哪里来的呢？感觉可以从单仓模板的`res`中来，然后在`cli`中删除一些文件。另外，这个命令参数有点长，可以改为`-a`即可。

2024-04-29 11:37 UTC, gqcn requested changes

2024-04-29 11:37 UTC, gqcn commented on cmd/gf/internal/packed/template-mono-app.go
> +package packed
@oldme-git 感觉这个模板可以从单仓模板自动生成而来，这样好维护一些（不然模板太多分散不好管理），然后在`cli`中删除一些模板文件（例如`go.mod, go.sum,  .gitattributes, .gitignore`）就是这个`mono-app`的模板了。可以修改`Makefile`来自动生成这个`mono-app`模板：https://github.com/gogf/gf/blob/master/cmd/gf/Makefile

另外，这个命令参数有点长，可以改为`-a`即可。

2024-05-01 05:52 UTC, oldme-git commented on cmd/gf/internal/packed/template-mono-app.go
> +package packed
done

2024-05-07 14:08 UTC, gqcn requested changes

2024-05-07 14:08 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_init.go
> +	MonoApp bool   `name:"mono-app" short:"a" brief:"initialize a mono-repo-app instead a single-repo" orphan:"true"`
`name:"monoApp"`

2024-05-07 14:08 UTC, gqcn commented on cmd/gf/Makefile
> +	@rm -fr temp/template-mono-app/resource/*
`api`, `internal/controller`, `resource`这三个目录似乎不需要删除吧？

2024-05-08 01:25 UTC, oldme-git commented on cmd/gf/Makefile
> +	@rm -fr temp/template-mono-app/resource/*
对于微服务的小仓来说，需要 `api` 和 `ctrl` 里面的内容吗，一般不是会通过 `proto` 生成吗。`resource` 在微服务的小仓下，什么业务会用到呢

2024-05-08 01:28 UTC, oldme-git commented on cmd/gf/internal/cmd/cmd_init.go
> +	MonoApp bool   `name:"mono-app" short:"a" brief:"initialize a mono-repo-app instead a single-repo" orphan:"true"`
done

2024-05-14 13:38 UTC, gqcn commented on cmd/gf/Makefile
> +	@rm -fr temp/template-mono-app/resource/*
> 对于微服务的小仓来说，需要 `api` 和 `ctrl` 里面的内容吗，一般不是会通过 `proto` 生成吗。`resource` 在微服务的小仓下，什么业务会用到呢

大仓中的`app`下面也是需要`api`和`controller`的，你说的`proto`也是可能有的，我们只生成模板，至于用户保留什么删什么可以自行决定。

2024-05-15 12:25 UTC, gqcn approved these changes

2024-05-15 12:25 UTC, merged