fix:迭代器内操作死锁
gogf/gf pull request #3572
Opened 2024-05-10 10:46 UTC by LonelySally

glist与gtree的迭代器内有下标操作,如果去除锁在并发操作的情况下可能造成数组越界导致panic,因此不做变更,但需要在文档处标注说明.

2024-05-11 03:41 UTC, gqcn requested changes

2024-05-11 03:41 UTC, gqcn commented on container/garray/garray_normal_any.go
>  	}
缺少单测，给个参考：
```go
func main() {
	array := garray.NewIntArrayFrom([]int{0, 1, 2, 3, 4, 5}, true)
	array.IteratorAsc(func(k int, v int) bool {
		fmt.Println(k, v)
		if v%2 == 0 {
			array.Remove(k)
		}
		return true
	})
	fmt.Println(array)
}
```

2024-05-11 05:13 UTC, LonelySally commented on container/garray/garray_normal_any.go
>  	}
> 缺少单测，给个参考：
> 
> ```go
> func main() {
> 	array := garray.NewIntArrayFrom([]int{0, 1, 2, 3, 4, 5}, true)
> 	array.IteratorAsc(func(k int, v int) bool {
> 		fmt.Println(k, v)
> 		if v%2 == 0 {
> 			array.Remove(k)
> 		}
> 		return true
> 	})
> 	fmt.Println(array)
> }
> ```

测试时发现garray的remove后数量正确,但值不正确.原因是Remove操作是直接截断源数组后重新拼接成一个新的,前面执行Remove后会导致数组下标前推造成异常.因此回滚变更保持原样,需要在框架文档处声明死锁问题.

2024-05-21 14:07 UTC, gqcn approved these changes

2024-05-21 14:07 UTC, merged