net/ghttp：Improve the process of parameter parsing
gogf/gf pull request #3578
Opened 2024-05-13 07:50 UTC by wln32

如果是严格路由的情况下，缓存带有default，in，valid，这三个tag的字段，避免做不必要的解析

2024-05-21 13:58 UTC, gqcn commented
@wln32 这个改进思路非常不错！但是有些小瑕疵，我和你一起协作改进一下，需要花一点点时间。

2024-05-22 01:30 UTC, wln32 commented
> @wln32 这个改进思路非常不错！但是有些小瑕疵，我和你一起协作改进一下，需要花一点点时间。

哪些问题呢？

2024-06-18 12:29 UTC, gqcn commented on net/ghttp/ghttp.go
> +		validTagFields int
- `validatingTagFieldsCount`
- 注释没有描述清楚
- 注释请放字段后面便于结构体字段整体编码对齐

2024-06-18 12:36 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +func getValidTagField(field reflect.Type) (count int) {
`getValidatingTagFieldCount`

2024-06-18 12:40 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +		}
既然将这个字段`validTagFields`定义为`int`类型，那么需要保证这个字段计算的准确性。
```go
validTag := field.TagValid()
if validTag != "" {
    funcInfo.validTagFields += 1
}
funcInfo.validTagFields += getValidTagField(field.Field.Type)
```

2024-06-18 12:43 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +		field = field.Elem()
这样获取`field`的原始类型并不准确，可以给`Field`结构体增加`OriginalType`方法，参考现有的`OriginalKind`实现：https://github.com/gogf/gf/blob/4abb32e11b5c368585f365a01468f6800faf98f7/os/gstructs/gstructs_field.go#L86

2024-06-18 12:44 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +	if field.Kind() == reflect.Struct {
推荐判断逻辑使用尽早退出逻辑，减少代码层级，例如这里可以调整为;
```go
if field.Kind() != reflect.Struct {
    return 
}
```

2024-06-18 12:45 UTC, gqcn commented on net/ghttp/ghttp_server_service_handler.go
> +				return
既然要计算标签数量，那么应当计算准确，这里应当使用`continue`

2024-06-18 12:46 UTC, gqcn commented
> > @wln32 这个改进思路非常不错！但是有些小瑕疵，我和你一起协作改进一下，需要花一点点时间。
> 
> 哪些问题呢？

我已经在代码中评论你了。

2024-06-18 12:49 UTC, gqcn requested changes

2024-06-18 12:49 UTC, gqcn commented on net/ghttp/ghttp_request_param.go
>  				return err
这3个`case`对应的方法其实存在瑕疵：
- `mergeInTagStructValue`仅在`doGetRequestStruct`中有处理，其他两个`case`没有处理。
- 这3个方法都重复调用了`mergeDefaultStructValue`方法，其实可以抽象出来统一处理。

2024-06-18 13:07 UTC, wln32 commented on net/ghttp/ghttp.go
> +		validTagFields int
> * `validatingTagFieldsCount`
> * 注释没有描述清楚
> * 注释请放字段后面便于结构体字段整体编码对齐

这里暂时用int类型代替，是用来统计字段有无需要验证的，本来是想把验证的规则用map存起来，然后不需要重复解析

2024-06-18 13:09 UTC, wln32 commented on net/ghttp/ghttp_server_service_handler.go
> +		}
> 既然将这个字段`validTagFields`定义为`int`类型，那么需要保证这个字段计算的准确性。
> 
> ```go
> validTag := field.TagValid()
> if validTag != "" {
>     funcInfo.validTagFields += 1
> }
> funcInfo.validTagFields += getValidTagField(field.Field.Type)
> ```

不需要准确到有几个字段需要验证，其实用bool类型可能好点，这样做只是想判断有没有需要验证的字段

2024-06-24 12:08 UTC, gqcn commented
@wln32 Hello handsome, any updates?

2024-07-02 12:55 UTC, wln32 commented
> @wln32 Hello handsome, any updates?

应该没了，再更新就是valid那块的缓存起来，gvalid的代码看起来有点麻烦

2024-07-04 13:33 UTC, gqcn commented
这个pr很好，后续需要我来看看进一步改进。

2024-10-19 03:47 UTC, Buffjfcfnmfx approved these changes

2025-03-11 05:01 UTC, closed without merging