net/ghttp: 修复路由重复注册的错误内容不够清晰
gogf/gf pull request #3603
Opened 2024-05-24 03:49 UTC by hailaz

before
```cmd
2024-05-24 11:43:42.348 [FATA] {38c941d7dd4fd21776ffce2184665142} duplicated route registry "/hello1@default" at C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:22 , already registered at C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:22
Stack:
1.  github.com/gogf/template-single/internal/cmd.glob..func1
    C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:26
2.  main.main
    C:/hailaz/gomod/gf-master/template-single/main.go:12

exit status 1
```

after
```cmd
2024-05-24 11:39:37.170 [FATA] {7c1d12c6a44fd217d1f3d408af3bcf35} The duplicated route registry [%GET:/hello@default] what is meaning [{hook}%{method}:{path}@{domain}] at
C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:22=>github.com/gogf/template-single/internal/controller/hello.(*ControllerV1).Hello1 , which has already been registered at 
C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:22=>github.com/gogf/template-single/internal/controller/hello.(*ControllerV1).Hello
You can disable duplicate route detection by modifying the server.routeOverWrite configuration, but this will cause some routes to be overwritten
Stack:
1.  github.com/gogf/template-single/internal/cmd.glob..func1
    C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:26
2.  main.main
    C:/hailaz/gomod/gf-master/template-single/main.go:12

exit status 1
```

before
```cmd
2024-05-24 11:45:44.877 [FATA] duplicated route registry "/content/list" at C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:28 , already registered at C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:25 
Stack:
1.  github.com/gogf/template-single/internal/cmd.glob..func1
    C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:28
2.  main.main
    C:/hailaz/gomod/gf-master/template-single/main.go:12

exit status 1
```
after
```cmd
2024-05-24 11:46:14.850 [FATA] The duplicated route registry [%ALL:/content/list@default] what is meaning [{hook}%{method}:{path}@{domain}] at 
C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:28=>github.com/gogf/template-single/internal/cmd.HelloHandler , which has already been registered at
C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:25=>github.com/gogf/template-single/internal/cmd.glob..func1.1
You can disable duplicate route detection by modifying the server.routeOverWrite configuration, but this will cause some routes to be overwritten
Stack:
1.  github.com/gogf/template-single/internal/cmd.glob..func1
    C:/hailaz/gomod/gf-master/template-single/internal/cmd/cmd.go:28
2.  main.main
    C:/hailaz/gomod/gf-master/template-single/main.go:12

exit status 1
```

2024-05-27 12:52 UTC, gqcn requested changes

2024-05-27 12:52 UTC, gqcn commented on net/ghttp/ghttp_server_router.go
> +						"The duplicated route registry [%s] what is meaning [{hook}%%{method}:{path}@{domain}] at \n%s=>%s , which has already been registered at \n%s=>%s"+
- `which is meaning [{hook}%%{method}:{path}@{domain}] at \n%s -> %s `
- 缺少对应的单测。

2024-05-31 08:39 UTC, hailaz commented on net/ghttp/ghttp_server_router.go
> +						"The duplicated route registry [%s] what is meaning [{hook}%%{method}:{path}@{domain}] at \n%s=>%s , which has already been registered at \n%s=>%s"+
Fatalf 是os.Exit(1)，要怎么单测？
https://github.com/gogf/gf/blob/e22e1d0e4ae477b8859690eaa4952a757018a203/os/glog/glog_logger_api.go#L36

2024-06-13 13:14 UTC, gqcn commented on net/ghttp/ghttp_server_router.go
> +						"The duplicated route registry [%s] what is meaning [{hook}%%{method}:{path}@{domain}] at \n%s=>%s , which has already been registered at \n%s=>%s"+
> Fatalf 是os.Exit(1)，要怎么单测？
> 
> https://github.com/gogf/gf/blob/e22e1d0e4ae477b8859690eaa4952a757018a203/os/glog/glog_logger_api.go#L36

原来如此，那就改了错误提示就好了。

2024-06-13 13:15 UTC, gqcn approved these changes

2024-06-13 13:16 UTC, merged