cmd/gf: improve gf gen ctrl
gogf/gf pull request #3616
Opened 2024-05-29 05:56 UTC by oldme-git

**Dear review:**
把另外一处正则替换成 `AST`，现在 `ctrl` 还有两处正则，但是正则的内容来源于模板，比较简单，可以不使用 `AST`。另外，调整了一下单测，把一些基本的测试纳入到基础测试里

2024-05-30 11:59 UTC, gqcn requested changes

2024-05-30 11:59 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_z_unit_gen_ctrl_test.go
> -func Test_Gen_Ctrl_Comments_Issue3569(t *testing.T) {
为什么要删除 3569 的单测呢？

2024-05-30 12:28 UTC, oldme-git commented on cmd/gf/internal/cmd/cmd_z_unit_gen_ctrl_test.go
> -func Test_Gen_Ctrl_Comments_Issue3569(t *testing.T) {
@gqcn 合到基础单测里去了，这个测试不用另外开一个issue测试

2024-06-04 13:01 UTC, gqcn requested changes

2024-06-04 13:01 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_z_unit_gen_ctrl_test.go
> -func Test_Gen_Ctrl_Comments_Issue3569(t *testing.T) {
> @gqcn 合到基础单测里去了，这个测试不用另外开一个issue测试

我找了现在`master`分支对应的`gen ctrl`单测，没有找到注释接口后不生成接口`api`的单测呢？

2024-06-04 13:12 UTC, gqcn approved these changes

2024-06-04 13:13 UTC, merged