cmd/gf: delete binary file when gf run end process
gogf/gf pull request #3628
Opened 2024-06-04 08:46 UTC by oldme-git

**Dear reviewer:**
在 `gf run` 结束时删除临时使用的二进制文件，另外，统一了不同系统的分隔符

2024-06-04 12:08 UTC, gqcn requested changes

2024-06-04 12:08 UTC, gqcn commented on cmd/gf/internal/cmd/cmd_run.go
> +	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
监听的信号不完整，建议使用`gproc.AddSigHandlerShutdown`来统一监听退出信号。

2024-06-05 05:56 UTC, oldme-git commented on cmd/gf/internal/cmd/cmd_run.go
> +	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
Done

2024-06-12 13:32 UTC, gqcn approved these changes

2024-06-12 13:32 UTC, merged