gerror: compatibility standard library error , IIs interface not implemented
gogf/gf pull request #3635
Opened 2024-06-07 08:47 UTC by junler

Fixes #3633

2024-06-11 14:03 UTC, gqcn requested changes

2024-06-11 14:03 UTC, gqcn commented on errors/gerror/gerror_api_stack.go
> +	return e.Is(target)
是否这样改动更合适一些：
```go
e, ok := err.(IIs)
if ok {
    return e.Is(target)
}
return err == target
```

2024-06-11 15:51 UTC, junler commented on errors/gerror/gerror_api_stack.go
> +	return e.Is(target)
如果改成这样，这个测试用例就过不了：t.Assert(gerror.Is(errors.New("1"), gerror.New("1")), true)

2024-06-12 13:18 UTC, gqcn commented on errors/gerror/gerror_api_stack.go
> +	return e.Is(target)
> 如果改成这样，这个测试用例就过不了：t.Assert(gerror.Is(errors.New("1"), gerror.New("1")), true)

看了下，这个`t.Assert(gerror.Is(errors.New("1"), gerror.New("1")), true)`本来就不应该过。我新建了分支合并了你的提交新建了pr到这里 https://github.com/gogf/gf/pull/3640

2024-06-12 13:19 UTC, gqcn commented
https://github.com/gogf/gf/pull/3640

2024-06-12 13:19 UTC, closed without merging