container/gtree: refactor code with gods package for avltree
gogf/gf pull request #3647
Opened 2024-06-18 08:58 UTC by oldme-git

`Dear reviewer:`
使用 `goda` 重构 `avltree`，并且新增 `gtree interface`，用做规范

2024-06-24 11:50 UTC, gqcn requested changes

2024-06-24 11:50 UTC, gqcn commented on container/gtree/gtree.go
> +type gtree interface {
- 你这个新接口没有看到使用的地方呢？
- 部分接口方法缺少注释。
- 如果创建接口对象，那么该接口应当定义为公开接口，例如`Tree`。

2024-06-24 12:35 UTC, oldme-git commented on container/gtree/gtree.go
> +type gtree interface {
三个不同的树都使用了这个接口，注释已经补上

2024-06-25 13:36 UTC, gqcn requested changes

2024-06-25 13:36 UTC, gqcn commented on container/gtree/gtree.go
> +type Gtree interface {
- 名称不使用报名，使用`Tree`更清楚一些。
- 我又找了你的`3`个pr，该接口没有找到明确使用的地方啊？

2024-06-25 14:34 UTC, oldme-git commented on container/gtree/gtree.go
> +type Gtree interface {
这个接口是个约束，没有直接出现，三个树本身就已经实现了这个接口

2024-07-01 12:36 UTC, gqcn approved these changes

2024-07-01 12:37 UTC, merged