database/gdb: add exist feature
gogf/gf pull request #3657
Opened 2024-06-21 08:31 UTC by CyJaySong

database/gdb: add exist feature

2024-06-24 12:47 UTC, gqcn requested changes

2024-06-24 12:47 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	return false, nil
直接用`Count`就可以实现`Exist`，为什么需要单独加一个方法呢？

2024-06-25 00:44 UTC, CyJaySong commented on database/gdb/gdb_model_select.go
> +	return false, nil
目前的Count()会查询符合条件的数据数量，即便是使用了limit(1)限制，
单独实现的`Exist` 限制limit 1, 查询效率自然要高一点，而且直接返回bool结果，对开发也友好一点

2024-06-25 01:08 UTC, CyJaySong commented on database/gdb/gdb_model_select.go
> +	return false, nil
纯粹只是为了开发时方便

2024-06-25 01:24 UTC, CyJaySong commented on database/gdb/gdb_model_select.go
> +	return false, nil
不过我感觉直接使用COUNT，效率不够高，待我优化一下

2024-06-25 02:07 UTC, CyJaySong commented on database/gdb/gdb_model_select.go
> +	return false, nil
查询时生成的sql 为`SELECT 1 FROM `user_1719281175072039000` WHERE `id` >= 1 LIMIT 1`

2024-06-25 13:28 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	return false, nil
@CyJaySong 感谢参与贡献，不过这个`Exist`确实与`Count`有一些冗余，所以无法合并进入主分支。

2024-06-25 13:29 UTC, closed without merging

2024-10-14 06:56 UTC, cyjaysong commented
@gqcn 这个合了吧，业务开发场景挺常用的，虽然Count 能够实现，但是效率肯定没这个方式高啊

2024-10-14 07:23 UTC, cyjaysong commented
使用Count 查询时，生成条件SQL  isCountStatement 传递了 true 以至于使用 Limit(1) 和 Count() 组合时，limit 不生效
<img width="1316" alt="image" src="https://github.com/user-attachments/assets/0899d255-dac6-4632-a467-e4d9ac6105db">
<img width="976" alt="image" src="https://github.com/user-attachments/assets/809f1073-29ce-49e7-be3c-149d8b87d1a7">

2024-10-14 13:56 UTC, gqcn commented
@cyjaysong 请重新提交一下pr，我们再重新走一下review流程，该pr已经无法打开了。