docs: 修改pr提交的标题要求说明
gogf/gf pull request #3666
Opened 2024-06-27 03:17 UTC by hailaz

2024-06-27 06:38 UTC, oldme-git requested changes

2024-06-27 06:38 UTC, oldme-git commented on .github/PULL_REQUEST_TEMPLATE.MD
>    + Title not Markdown
这一个规则不要了

2024-06-27 12:56 UTC, gqcn requested changes

2024-06-27 12:56 UTC, gqcn commented on .github/PULL_REQUEST_TEMPLATE.MD
> ++ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fixed time zone issues`
`fix(os/gtime): time zone issues`

2024-06-27 12:56 UTC, gqcn commented on .github/PULL_REQUEST_TEMPLATE.MD
> ++ PR 标题格式如下：`<类型>[可选 范围]: <描述>` 例如 `fix(os/gtime): fixed time zone issues`
同上。

2024-06-28 02:09 UTC, hailaz commented on .github/PULL_REQUEST_TEMPLATE.MD
> ++ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fixed time zone issues`
描述虽然看起来重复了，但是描述是完整的。

2024-06-28 05:37 UTC, oldme-git approved these changes

2024-07-01 12:33 UTC, gqcn commented on .github/PULL_REQUEST_TEMPLATE.MD
> ++ The PR title is formatted as follows: `<type>[optional scope]: <description>` For example, `fix(os/gtime): fixed time zone issues`
那就改下语法吧 `fix(os/gtime): fix time zone issue`

2024-07-02 12:56 UTC, gqcn approved these changes

2024-07-02 12:56 UTC, merged