util/gconv:  Add gconv.Struct cache logic
gogf/gf pull request #3673
Opened 2024-07-01 08:43 UTC by wln32

1. 对`gconv.Scan`, `gconv.Struct`之类的函数(只要是转换到struct类型的)增加了缓存逻辑，不需要重复解析
2. 对于常见类型的字段使用`gconv.Int`, `gconv.String`之类的，无需多次判断
3. 缓存特性由`UseConvCacheExperiment`函数来控制，默认开启，如果开启后有什么bug，关闭即可，平稳过渡
4. 对于上次的改进来说，性能方面大幅度提升，运行速度差不多有一倍，内存方面大幅度减少

以下是本次的性能，会有一些浮动，
```
Benchmark_doStruct_Fields8_Basic_MapToStruct
Benchmark_doStruct_Fields8_Basic_MapToStruct-8            976039              6240 ns/op            1310 B/op         10 allocs/op

2024-07-01 10:50 UTC, houseme approved these changes

2024-07-17 13:25 UTC, gqcn commented
@wln32 很棒的性能优化思路 👍 我刚粗略看了下，整体实现逻辑上没什么问题的，我需要仔细看看学习一下细节，需要花一点时间哈。

2024-07-18 13:31 UTC, gqcn requested changes

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +func UseConvCacheExperiment(b bool) {
不建议把开关作为选项给使用者来控制，去掉该方法。

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +}
这个`convertFieldInfoBase`结构的每一项属性描述请使用中文详细描述下作用。我来转为英文。

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +}
这个`convertFieldInfo`结构的每一项属性描述请使用中文详细描述下作用。我来转为英文。

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +func (structInfo *convertStructInfo) NoFields() bool {
`HasNoFields`

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +	return v
`return structInfo.fieldAndTagsMap[fieldName]`

2024-07-18 13:31 UTC, gqcn commented on util/gconv/gconv_struct_cache.go
> +	otherFieldIndex [][]int
为什么要定义多维数组？

2024-07-18 13:37 UTC, wln32 commented on util/gconv/gconv_struct.go
> +		usedParamsKeyOrTagNameMap = poolGetUsedParamsKeyOrTagNameMap()
可以的，每次用完都会把map清空的，我在那个注释那里有写

2024-07-18 13:38 UTC, wln32 commented on util/gconv/gconv_struct.go
> +		usedParamsKeyOrTagNameMap = poolGetUsedParamsKeyOrTagNameMap()
> 这个`usedParamsKeyOrTagNameMap`恐怕不能使用`pool`来全局复用吧，每个`struct`转换的时候这个`map`都应当是不一样的，复用的话恐怕会有问题哦？！

@gqcn 可以的，没问题，每次用完吧map清空就行了，我注释那里有写的

2024-07-18 13:38 UTC, wln32 commented on util/gconv/gconv_struct_cache.go
> +}
> 这个`convertFieldInfo`结构的每一项属性描述请使用中文详细描述下作用。我来转为英文。

ok

2024-07-18 13:42 UTC, wln32 commented on util/gconv/gconv_struct_cache.go
> +	otherFieldIndex [][]int
> 为什么要定义多维数组？

正常是[]int，可以兼顾到嵌套的字段，使用[][]int的原因是嵌套的结构体字段可能会和外层结构体或者其他嵌套结构体的字段重名
例如以下
```go
type Name struct{
   LastName string
   FirstName string
}


type User struct{
  Name 
  LastName string
  FirstName string
}
```
这种情况只会存储两个字段`LastName`, `FirstName`,使用不同的索引来代表不同的字段

2024-07-18 13:46 UTC, wln32 commented on util/gconv/gconv_struct_cache.go
> +func UseConvCacheExperiment(b bool) {
> 不建议把开关作为选项给使用者来控制，去掉该方法。

ok

2024-08-08 11:53 UTC, gqcn requested changes

2024-08-08 12:37 UTC, gqcn commented
I'm still reviewing this. ❤️

2024-08-14 14:11 UTC, houseme approved these changes

2024-09-09 07:19 UTC, gqcn requested changes

2024-09-09 07:19 UTC, gqcn commented on util/gconv/internal/structcache/structcache_cached_field_info.go
> +type cachedFieldInfoBase struct {
内部包的数据结构可以定义为公开，这里改为`CachedFieldInfoBase`

2024-09-09 07:23 UTC, wln32 commented on util/gconv/internal/structcache/structcache_cached_field_info.go
> +type cachedFieldInfoBase struct {
> 内部包的数据结构可以定义为公开，这里改为`CachedFieldInfoBase`

ok

2024-09-09 07:28 UTC, gqcn approved these changes

2024-09-09 08:17 UTC, merged