fix(contrib/drivers/pgsql): fix insert error when data struct field has nil in PgSQL
gogf/gf pull request #3679
Opened 2024-07-09 09:56 UTC by oldme-git

Fixes #3668

2024-07-11 11:54 UTC, gqcn approved these changes

2024-07-11 11:56 UTC, gqcn requested changes

2024-07-11 11:56 UTC, gqcn commented on contrib/drivers/pgsql/pgsql_convert.go
> +	if fieldValue == nil {
是否这里使用`empty.IsNil`来判断更合适一些呢？

2024-07-12 03:47 UTC, oldme-git commented on contrib/drivers/pgsql/pgsql_convert.go
> +	if fieldValue == nil {
用不了，empty 是内部包

2024-07-17 12:47 UTC, gqcn requested changes

2024-07-17 12:47 UTC, gqcn commented on contrib/drivers/pgsql/pgsql_convert.go
> +	if fieldValue == nil {
在`golang`里面的`interface{}`判断为`== nil`会有坑，因为它在内部需要判断类型和值，类型不相同时判断会失效，所以这里需要使用框架封装的`IsNil`方法来判断避免踩坑。这里可以使用`g.IsNil`来判断。

2024-07-18 02:15 UTC, oldme-git commented on contrib/drivers/pgsql/pgsql_convert.go
> +	if fieldValue == nil {
Done

2024-09-09 07:21 UTC, gqcn approved these changes

2024-09-09 08:16 UTC, merged