database/gdb: Convert Time based on fieldType
gogf/gf pull request #3712
Opened 2024-07-26 06:47 UTC by cyjaysong

Convert Time based on fieldType

2024-07-29 12:54 UTC, gqcn requested changes

2024-07-29 12:54 UTC, gqcn commented on os/gtime/gtime_sql.go
> +func (t *Time) ValueForFieldType(fieldType string) (driver.Value, error) {
It is suggested adding `ValueForFieldType`  interface implement for `gtime.Time`, which adds unnecessary magic features for time object, could be complicated for usage.

2024-07-29 12:54 UTC, gqcn commented on database/gdb/gdb_types.go
> +}
It is suggested make it as simple as possible for usage, not more unnecessary, hidden interfaces.

2024-07-30 01:54 UTC, cyjaysong commented
@gqcn 移除`gtime`的`driver.Valuer` 接口实现，使用ConvertValueForField中的类型匹配规则进行序列化

2024-08-01 12:13 UTC, gqcn requested changes

2024-08-01 14:31 UTC, cyjaysong commented on os/gtime/gtime_format.go
> +
魔法糖方法 已经Revert

2024-08-02 02:17 UTC, wln32 commented
> @gqcn 移除的 接口实现，使用中的类型匹配规则进行序列化`gtime``driver.Valuer``ConvertValueForField`

我觉得没啥必要加这个接口，用Scan和Value和标准库一样，就可以

2024-08-02 02:33 UTC, cyjaysong commented
> > @gqcn 移除的 接口实现，使用中的类型匹配规则进行序列化`` gtime``driver.Valuer``ConvertValueForField ``
> 
> 我觉得没啥必要加这个接口，用Scan和Value和标准库一样，就可以

没加接口了啊，新加的接口移除掉了

2024-08-03 13:27 UTC, niluan304 commented
我觉得不应该移除 `gtime.Time` 的 `driver.Valuer` 接口实现，
如果项目使用的是其他 orm，如 gorm，而字段类型又是 `gtime.Time`，可能会导致无法序列化为数据库中对应的类型。

2024-08-14 12:58 UTC, gqcn requested changes

2024-08-14 12:58 UTC, gqcn commented on os/gtime/gtime_sql.go
> +func (t *Time) ValueForFieldType(fieldType string) (driver.Value, error) {
@cyjaysong

2024-08-14 12:58 UTC, gqcn requested changes

2024-08-14 12:58 UTC, gqcn commented on os/gtime/gtime_sql.go
> +func (t *Time) ValueForFieldType(fieldType string) (driver.Value, error) {
> It is not suggested adding `ValueForFieldType` interface implement for `gtime.Time`, which adds unnecessary magic features for time object, could be complicated for usage.

@cyjaysong

2024-08-15 05:54 UTC, cyjaysong commented
@gqcn 这个ci失败看着不像我这边的问题，我没改gview

2024-08-15 06:02 UTC, niluan304 commented
> @gqcn 这个ci失败看着不像我这边的问题，我没改gview

可能是github服务故障导致的：

https://www.githubstatus.com/incidents/kz4khcgdsfdv


试试重新运行一下 action

2024-08-15 09:31 UTC, cyjaysong commented
@niluan304 怎么重新Action

2024-08-27 00:24 UTC, cyjaysong commented
@gqcn 不看看了吗

2024-09-10 09:51 UTC, gqcn approved these changes

2024-09-10 09:51 UTC, merged