fix(database/gdb): fix#3649 when constructing query param, `gdb.Row` value not directly write to Buffer
gogf/gf pull request #3718
Opened 2024-07-31 01:40 UTC by cyjaysong

fix#3649 when constructing query param, `gdb.Row` value not directly write to Buffer

2024-07-31 01:43 UTC, cyjaysong commented
@gqcn @hailaz

2024-07-31 10:47 UTC, hailaz commented
这个问题是解决，但不确定有没其他情况需要用到原来的那个逻辑分支。 @gqcn 看看

2024-08-01 11:36 UTC, gqcn requested changes

2024-08-01 11:36 UTC, gqcn commented on contrib/drivers/mysql/mysql_z_unit_issue_test.go
> +		//t.Assert(n, 1)
这个单测只校验了SQL语法不报错，但没有逻辑校验，建议参考issue https://github.com/gogf/gf/issues/3649 对期望结果进行校验。

2024-08-01 14:44 UTC, cyjaysong commented on contrib/drivers/mysql/mysql_z_unit_issue_test.go
> +		//t.Assert(n, 1)
已修改

2024-08-14 13:16 UTC, gqcn approved these changes

2024-08-14 13:16 UTC, merged