feat(os/gsession): add session reset function.    fix(i18n/gi18n_manager): TranslateFormat bug fixed
gogf/gf pull request #3726
Opened 2024-08-14 10:26 UTC by lxy1151

session模块：增加了session重置方法。

多语言翻译中TranslateFormat方法增加了动态参数与位置无关的处理（部分翻译在不同语言动态参数位置会变化）。

2024-08-15 07:53 UTC, hailaz commented
> session模块：增加了session重置方法。
> 
> 多语言翻译中TranslateFormat方法增加了动态参数与位置无关的处理（部分翻译在不同语言动态参数位置会变化）。

如果包含两个功能的修改，可以拆分为两个pr提交，这样不会相互影响，也能提高代码审批的效率。

2024-08-18 02:50 UTC, lxy1151 commented
> > session模块：增加了session重置方法。
> > 多语言翻译中TranslateFormat方法增加了动态参数与位置无关的处理（部分翻译在不同语言动态参数位置会变化）。
> 
> 如果包含两个功能的修改，可以拆分为两个pr提交，这样不会相互影响，也能提高代码审批的效率。
好的，下次尽量单一功能提交

2024-09-23 08:38 UTC, gqcn commented
@lxy1151 Any updates?

2024-09-25 09:48 UTC, lxy1151 commented on i18n/gi18n/gi18n_manager.go
> +	return fmt.Sprintf(result, values...)
需要拆分是吗？

2024-09-25 09:48 UTC, lxy1151 commented on i18n/gi18n/gi18n_manager.go
> +	return fmt.Sprintf(result, values...)
好的，我先处理下

2024-09-26 06:18 UTC, lxy1151 commented
> @lxy1151 Any updates?

I have processed it, please recheck!

2024-09-28 13:51 UTC, gqcn requested changes

2024-09-28 13:51 UTC, gqcn commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
请描述增加此方法的必要性，例如需要解决什么样的业务场景痛点？

2024-09-29 01:30 UTC, lxy1151 commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
没有这个方法，sessionId始终不能过期。
每次登录时要求上次的sessionId过期，无法实现，特此加了该方法

2024-10-23 03:11 UTC, lxy1151 commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
这个怎么说，还需修改什么吗？

2024-11-11 13:50 UTC, gqcn requested changes

2024-11-11 13:50 UTC, gqcn commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
直接使用`RemoveAll`不就行了呢。

2024-12-05 02:59 UTC, lxy1151 commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
但是sessionId生成不了新的，还是会是老的
其他成熟的框架session都是有这个方法的，我们项目用了下，很难用直接放弃了，希望能改进下

2024-12-05 13:04 UTC, gqcn requested changes

2024-12-05 13:04 UTC, gqcn commented on os/gsession/gsession_session.go
> +func (s *Session) RegenSession(delOld ...bool) (newSid string, err error) {
@lxy1151 为什么一定要重新生成新的`sessionid`呢？你们现在使用的是哪个`session`组件呢？

2024-12-05 14:39 UTC, gqcn commented
@lxy1151 你好，我添加了`RegenerateId/MustRegenerateId`方法，欢迎一起进行 code review https://github.com/gogf/gf/pull/4012

2024-12-05 14:39 UTC, closed without merging