build: add go version 1.23
gogf/gf pull request #3733
Opened 2024-08-15 12:02 UTC by houseme

build: add go version 1.23

2024-08-22 03:52 UTC, hailaz approved these changes

2024-09-09 06:33 UTC, gqcn requested changes

2024-09-09 06:33 UTC, gqcn commented on database/gredis/gredis_redis.go
> +const errorNilAdapter = `redis adapter is not set, missing configuration or adapter register? possible reference: https://github.com/gogf/gf/tree/master/contrib/nosql/redis`
请在本次pr中还原该修改。

2024-09-09 07:09 UTC, houseme commented on database/gredis/gredis_redis.go
> +const errorNilAdapter = `redis adapter is not set, missing configuration or adapter register? possible reference: https://github.com/gogf/gf/tree/master/contrib/nosql/redis`
改回去，这里失败了
![image](https://github.com/user-attachments/assets/e58c420c-9928-4548-bee8-bc1f855f7a8d)

2024-09-09 07:46 UTC, houseme commented on database/gredis/gredis_redis.go
> +const errorNilAdapter = `redis adapter is not set, missing configuration or adapter register? possible reference: https://github.com/gogf/gf/tree/master/contrib/nosql/redis`
修改为常量和最终的效果是一样的，目前代码里的还需要函数处理一下。改回的原因是方便阅读还是有其他考虑呢？

2024-09-12 10:01 UTC, gqcn commented on database/gredis/gredis_redis.go
> +const errorNilAdapter = `redis adapter is not set, missing configuration or adapter register? possible reference: https://github.com/gogf/gf/tree/master/contrib/nosql/redis`
> 修改为常量和最终的效果是一样的，目前代码里的还需要函数处理一下。改回的原因是方便阅读还是有其他考虑呢？@gqcn

之前你这个常量是带了换行，在错误提示中是不行的，如果改为了一行，那就没什么问题了。我之前用变量的原因是方便阅读。

2024-09-12 10:07 UTC, houseme commented on database/gredis/gredis_redis.go
> +const errorNilAdapter = `redis adapter is not set, missing configuration or adapter register? possible reference: https://github.com/gogf/gf/tree/master/contrib/nosql/redis`
> > 修改为常量和最终的效果是一样的，目前代码里的还需要函数处理一下。改回的原因是方便阅读还是有其他考虑呢？@gqcn
> 
> 之前你这个常量是带了换行，在错误提示中是不行的，如果改为了一行，那就没什么问题了。我之前用变量的原因是方便阅读。

那就是还是改为常量咯，显示的结果都是一样，ide 需要换行显示，设置自动换行就可以

2024-09-19 02:37 UTC, gqcn approved these changes

2024-09-19 02:38 UTC, merged