fix(encoding/gxml): XML special character encoding error
gogf/gf pull request #3740
Opened 2024-08-22 06:04 UTC by oldme-git

Dear review:
fixed #3716

2024-09-09 06:46 UTC, gqcn requested changes

2024-09-09 06:46 UTC, gqcn commented on encoding/gxml/gxml.go
> +	defer mxj.XMLEscapeChars(false)
- `mxj.XMLEscapeChars`是设置全局配置的，该方法不支持并发安全。因此如果需要调用该方法，建议参考`mxj`新增个全局配置方法来实现。
- 之前不是说要用标准库替换`mxj`这个库么，目前看标准库不支持只能继续使用`mxj`?

2024-09-09 06:53 UTC, oldme-git commented on encoding/gxml/gxml.go
> +	defer mxj.XMLEscapeChars(false)
`mxj` 没找到全局配置方法，要支持并发安全需要加锁了估计。
标准库编码问题不大，解码要考虑的问题很多，难度很高。`mxj` 其实就是基于标准库编码，解码单独写的。

2024-09-10 03:21 UTC, oldme-git commented on encoding/gxml/gxml.go
> +	defer mxj.XMLEscapeChars(false)
Done

2024-09-12 09:53 UTC, gqcn requested changes

2024-09-12 09:53 UTC, gqcn commented on encoding/gxml/gxml_z_unit_test.go
> +		gxml.XMLEscapeChars(true)
这里是不是加个`defer`还原一下默认值？

2024-09-13 01:57 UTC, oldme-git commented on encoding/gxml/gxml_z_unit_test.go
> +		gxml.XMLEscapeChars(true)
Done

2024-09-13 02:37 UTC, gqcn approved these changes

2024-09-13 02:37 UTC, merged