fix: skip custom body for streaming content types
gogf/gf pull request #3762
Opened 2024-09-09 07:03 UTC by wwwfeng

It optimizes the middleware by skipping custom response body handling for streaming content types, preventing unnecessary processing.

2024-09-10 06:05 UTC, gqcn requested changes

2024-09-10 06:05 UTC, gqcn commented on net/ghttp/ghttp_middleware_handler_response.go
> +		if gstr.Equal(mediaType, ct) {
是否直接使用`mediaType == ct`即可？

2024-09-10 06:05 UTC, gqcn commented on net/ghttp/ghttp_middleware_handler_response.go
> +		"multipart/x-mixed-replace",
将内部临时变量提出为内部包变量是否更好一些？

2024-09-10 06:05 UTC, gqcn commented on net/ghttp/ghttp_middleware_handler_response.go
> +
请提交对应的单测用例，覆盖该修改。

2024-09-10 06:05 UTC, gqcn commented on net/ghttp/ghttp_middleware_handler_response.go
> +	// The response will not return any additional custom content or body
```go
// It does not output common response content if it is stream response.
```

2024-09-10 10:51 UTC, wwwfeng commented on net/ghttp/ghttp_middleware_handler_response.go
> +		if gstr.Equal(mediaType, ct) {
了解

2024-09-10 10:52 UTC, wwwfeng commented on net/ghttp/ghttp_middleware_handler_response.go
> +		"multipart/x-mixed-replace",
是的

2024-09-10 10:53 UTC, wwwfeng commented on net/ghttp/ghttp_middleware_handler_response.go
> +
> 请提交对应的单测用例，覆盖该修改。

已经新增测试用例

2024-09-10 10:55 UTC, wwwfeng commented on net/ghttp/ghttp_middleware_handler_response.go
> +		"multipart/x-mixed-replace",
> 将内部临时变量提出为内部包变量是否更好一些？

是的

2024-09-10 10:55 UTC, wwwfeng commented on net/ghttp/ghttp_middleware_handler_response.go
> +		if gstr.Equal(mediaType, ct) {
> 是否直接使用`mediaType == ct`即可？

了解

2024-09-12 09:29 UTC, gqcn approved these changes

2024-09-12 09:50 UTC, merged