fix(net/gclient): using the wrong header to update file
gogf/gf pull request #3775
Opened 2024-09-13 08:33 UTC by oldme-git

fixed #3748

2024-09-13 09:46 UTC, houseme approved these changes

2024-09-19 03:56 UTC, gqcn requested changes

2024-09-19 03:56 UTC, gqcn commented on net/gclient/gclient_request.go
> +}
等等，我看了下这个issue https://github.com/gogf/gf/issues/3748 只是提了会报`panic`，应该是参数处理不严谨。而你这个pr做了一些枚举来允许文件上传，好像是两码事了诶？！

2024-09-19 07:47 UTC, oldme-git commented on net/gclient/gclient_request.go
> +}
之前这块的上传逻辑不严谨，如果 `header content-type` 头是 `json` 或者 `xml` 这种不允许上传文件的头，应该将其做为一个普通的字符串上传

2024-09-23 08:22 UTC, gqcn requested changes

2024-09-23 08:22 UTC, gqcn commented on net/gclient/gclient_request.go
> +}
@oldme-git  如果是通过`json`这种`header`头来上传文件，服务端也接受不了的，上传不了文件，我们不需要做额外处理。只需要解决`issue`中提出来的参数处理不严谨导致`panic`的问题就好，任何情况下框架其实不太应该`panic`，而是通过返回`error`的形式让上层处理。

2024-09-23 08:46 UTC, oldme-git commented on net/gclient/gclient_request.go
> +}
@gqcn 
这个是框架内部占用了 `@file:` 这个字符。例如这样一个请求：

```
POST: http://goframe.org
header, content-type: application/json
body: 
{
  "fileType": "mail@file:123"
}
```
在框架是中是不被允许的，会将 `mail@file:123` 这个字符串识别成文件，但是在 `postman` 这类工具中，它是可以正常请求的，并且后端会受到这个 json 字符串。

2024-09-24 08:11 UTC, gqcn commented on net/gclient/gclient_request.go
> +}
@oldme-git 确实会有这个问题，看样子还有两个细节，我来看看怎么修复这个问题呢。

2024-09-25 02:37 UTC, merged