fix(utils/utils_str): fix recognize '+' as a valid numeric sign
gogf/gf pull request #3778
Opened 2024-09-13 11:50 UTC by wwwfeng

我觉得`+`号也应该作为数字类型识别，我看标准库的atoi 也有类似对于带`+`符号的数字处理
比如
```
func ParseInt(s string, base int, bitSize int) (i int64, err error) {
	 //...
	// Pick off leading sign.
	s0 := s
	neg := false
	if s[0] == '+' {
		s = s[1:]
	} else if s[0] == '-' {
		neg = true
		s = s[1:]
	}
      //...
  return
}

```

2024-09-19 06:13 UTC, gqcn requested changes

2024-09-19 06:13 UTC, gqcn commented on internal/utils/utils_str.go
> +		if (s[i] == '-' || s[i] == '+') && i == 0 {
需要注意边界判断，比如`-`或者`+`是不能被认为是`numeric`的，建议同时加上这两个单测case。

2024-09-19 06:14 UTC, gqcn commented
fixed #3776

2024-09-19 07:15 UTC, wwwfeng commented on internal/utils/utils_str.go
> +		if (s[i] == '-' || s[i] == '+') && i == 0 {
大概这样吗？
```
	        t.Assert(utils.IsNumeric("-a23"), false)
		t.Assert(utils.IsNumeric("+a23"), false)
		t.Assert(utils.IsNumeric("1+23"), false)
		t.Assert(utils.IsNumeric("1-23"), false)
```

2024-09-19 10:27 UTC, wwwfeng commented
咦，CI的问题吗

2024-09-20 23:00 UTC, wln32 commented
@wwwfeng @gqcn 按照如下更改是否会更好一些？
```go
func IsNumeric(s string) bool {
	var (
		dotCount = 0
		length   = len(s)
		start    = 0
	)
	if length == 0 {
		return false
	}
	// -123 => 123
	// +123 => 123
	if s[0] == '-' || s[0] == '+' {
		// + false
		// - false
		if length == 1 {
			return false
		}
		start = 1
	}
	// .123 false
	// 123. false
	// .    false
	if s[0] == '.' || s[length-1] == '.' {
		return false
	}
	for i := start; i < length; i++ {
		if s[i] == '.' {
			dotCount++
			if dotCount > 1 {
				return false
			}
			continue
		}
		if s[i] < '0' || s[i] > '9' {
			return false
		}
	}
	return true
}
```
另再添加如下测试用例
```go
t.Assert(utils.IsNumeric("123."), false)
		t.Assert(utils.IsNumeric(".123"), false)
		t.Assert(utils.IsNumeric("123.a"), false)
		t.Assert(utils.IsNumeric("a.123"), false)
		t.Assert(utils.IsNumeric("+"), false)
		t.Assert(utils.IsNumeric("-"), false)
		t.Assert(utils.IsNumeric("."), false)
                t.Assert(utils.IsNumeric("-."), false)
		t.Assert(utils.IsNumeric("+."), false)
```

2024-09-21 01:11 UTC, wwwfeng commented
> @wwwfeng @gqcn 按照如下更改是否会更好一些？
> 
> ```go
> func IsNumeric(s string) bool {
> 	var (
> 		dotCount = 0
> 		length   = len(s)
> 		start    = 0
> 	)
> 	if length == 0 {
> 		return false
> 	}
> 	// -123 => 123
> 	// +123 => 123
> 	if s[0] == '-' || s[0] == '+' {
> 		// + false
> 		// - false
> 		if length == 1 {
> 			return false
> 		}
> 		start = 1
> 	}
> 	// .123 false
> 	// 123. false
> 	// .    false
> 	if s[0] == '.' || s[length-1] == '.' {
> 		return false
> 	}
> 	for i := start; i < length; i++ {
> 		if s[i] == '.' {
> 			dotCount++
> 			if dotCount > 1 {
> 				return false
> 			}
> 			continue
> 		}
> 		if s[i] < '0' || s[i] > '9' {
> 			return false
> 		}
> 	}
> 	return true
> }
> ```
> 
> 另再添加如下测试用例
> 
> ```go
> t.Assert(utils.IsNumeric("123."), false)
> 		t.Assert(utils.IsNumeric(".123"), false)
> 		t.Assert(utils.IsNumeric("123.a"), false)
> 		t.Assert(utils.IsNumeric("a.123"), false)
> 		t.Assert(utils.IsNumeric("+"), false)
> 		t.Assert(utils.IsNumeric("-"), false)
> 		t.Assert(utils.IsNumeric("."), false)
>                 t.Assert(utils.IsNumeric("-."), false)
> 		t.Assert(utils.IsNumeric("+."), false)
> ```

确实遗漏了一些case，似乎满足这些用例下面的变更就可以实现
```
if (s[i] == '-' || s[i] == '+') && i == 0 {
			if length == 1 {
				return false
			}
			continue
		}
```

// .123 false
// 123. false
这两个case原本处理逻辑似乎是包含了的

2024-09-23 08:17 UTC, gqcn approved these changes

2024-09-23 08:45 UTC, merged