Feature/gf service embed
gogf/gf pull request #3802
Opened 2024-09-24 06:10 UTC by joy999

实现logic中内嵌其它logic时，生成service可以合并内嵌logic的接口生成。
比如 type sAdmin struct {
sMember
}
生成的service.IAdmin将存在sMember的接口合并，并不会只有sAdmin的接口。

2024-09-24 08:42 UTC, gqcn requested changes

2024-09-24 08:42 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +					if len(field.Names) == 0 { // 匿名字段
源码中请使用英文注释。

2024-09-24 08:42 UTC, gqcn commented on cmd/gf/internal/cmd/genservice/genservice.go
> +type fileInfo struct {
请提交对应的单测，覆盖提交的修改。

2024-09-26 03:29 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +					if len(field.Names) == 0 { // 匿名字段
updated

2024-09-26 03:30 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice.go
> +type fileInfo struct {
added

2024-10-09 12:55 UTC, gqcn commented
这个PR @hailaz 和 @oldme-git 一起帮忙review下呢？

2024-10-09 13:10 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +				}
外层的会覆盖内层的。

2024-10-09 13:17 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_calculate.go
> +			//获取对应的structName的methods列表
done

2024-10-10 01:34 UTC, oldme-git requested changes

2024-10-10 01:34 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice.go
> +	var allStructItems = make(map[string][]string)
这里可以用一个 var 吧

2024-10-10 01:34 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +
这个函数可以优化一下写法，先判断 `eles if hasPrefix`，提前返回 false，从而省去 `else if` 子句

2024-10-10 01:34 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +				}
这里能否减少一些缩进，比如先判断 `field.Names != 0 - contiune`

2024-10-10 01:35 UTC, oldme-git commented
@gqcn 这个功能是否需要，如果存在多层嵌套该怎么处理

2024-10-10 01:42 UTC, joy999 commented
> @gqcn @joy999 这个功能是否需要，如果存在多层嵌套该怎么处理

多层嵌套有处理过。内层的同名函数会被外层的同名函数定义覆盖。有些场景是需要这样处理的。比如先有一个sMember，然后要再定义一个sAdmin继承自sMember，sAdmin只重载一些特定方法，其它的沿用sMember的。

2024-10-10 12:47 UTC, gqcn commented
> @gqcn @joy999 这个功能是否需要，如果存在多层嵌套该怎么处理

@joy999 嗯，这里能否做个开关控制一下，通常用不着，可以让用户自己打开。另外，麻烦在关键逻辑多加点注释，方便长期维护。

2024-10-11 22:44 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +
这块代码现在直接去掉了。不再使用s开头来判定是否是内嵌。所以这里可以忽略掉了。

2024-10-11 22:44 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +				}
代码已经作了调整

2024-10-11 22:47 UTC, joy999 commented
> > @gqcn @joy999 这个功能是否需要，如果存在多层嵌套该怎么处理
> 
> @joy999 这里能否做个开关控制一下，通常用不着，可以让用户自己打开。另外，麻烦在关键逻辑多加点注释，方便长期维护。

现在已经去除了通过结构体s开头来判定是否要内嵌识别的处理逻辑。而是改用在内嵌结构体名后加tag的方式，这样不管是s开头或者是其它的结构体都可以嵌入，同时，现在也可以跨包内嵌了。tag现在定义了 gen:"extend" 则会内嵌识别。

2024-10-12 06:01 UTC, gqcn commented
> > > @gqcn @joy999 这个功能是否需要，如果存在多层嵌套该怎么处理
> > 
> > 
> > @joy999 这里能否做个开关控制一下，通常用不着，可以让用户自己打开。另外，麻烦在关键逻辑多加点注释，方便长期维护。
> 
> 现在已经去除了通过结构体s开头来判定是否要内嵌识别的处理逻辑。而是改用在内嵌结构体名后加tag的方式，这样不管是s开头或者是其它的结构体都可以嵌入，同时，现在也可以跨包内嵌了。tag现在定义了 gen:"extend" 则会内嵌识别。

识别`s`开头是因为`logic`下面会有很多`struct`，需要区分那些struct是需要生成service的。你去掉了`s*`名称判断后，怎么来识别呢？我看你加的`gen`标签只是为了识别结构体中的属性是否识别扩展方法。

2024-10-12 08:07 UTC, joy999 commented
> > > > @gqcn @joy999 这个功能是否需要，如果存在多层嵌套该怎么处理
> > > 
> > > 
> > > @joy999 这里能否做个开关控制一下，通常用不着，可以让用户自己打开。另外，麻烦在关键逻辑多加点注释，方便长期维护。
> > 
> > 
> > 现在已经去除了通过结构体s开头来判定是否要内嵌识别的处理逻辑。而是改用在内嵌结构体名后加tag的方式，这样不管是s开头或者是其它的结构体都可以嵌入，同时，现在也可以跨包内嵌了。tag现在定义了 gen:"extend" 则会内嵌识别。
> 
> 识别`s`开头是因为`logic`下面会有很多`struct`，需要区分那些struct是需要生成service的。你去掉了`s*`名称判断后，怎么来识别呢？我看你加的`gen`标签只是为了识别结构体中的属性是否识别扩展方法。

并没有改动原来的sXXX的生成判定。我去掉的是我用来判定内嵌识别的那部分我自己添加的代码，之前是以sXXX为嵌入结构体，其它的命名的结构体不会被识别为嵌入方法继承，所以只能在本目录下引入。现在这个调整为了通过tag来识别，所以，理论上任意位置的结构体现在都可以嵌入了。

2024-10-14 13:18 UTC, gqcn approved these changes

2024-10-15 06:02 UTC, oldme-git requested changes

2024-10-15 06:02 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +			case *ast.SelectorExpr: // define selector
这里的注释也是

2024-10-15 06:02 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +			case *ast.Ident: // define ident
这里的注释也是

2024-10-15 06:02 UTC, oldme-git commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +				structItems[structName] = []string{typeName}
structItems 为什么不可以使用 map[string]string呢

2024-10-15 06:23 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +	pkgAliasMap := make(map[string]string)
没必要啊。不同的风格而已。我们又不是禁用了:=的

2024-10-15 06:24 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +			}
ast并不能识别出真正的srcPkg，没必要放parseImportPackages里。这里只是在当前的场景下可以在90%的情况下工作。也只是为了防止那出现的10%的可能性。

2024-10-15 06:25 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +		case *ast.TypeSpec: // type define
这个不是在解释下面的代码块。只是在补充说明这个常量的意思，不应该放到下面去。

2024-10-15 06:25 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +			case *ast.Ident: // define ident
同前

2024-10-15 06:25 UTC, joy999 commented on cmd/gf/internal/cmd/genservice/genservice_ast_parse.go
> +				structItems[structName] = []string{typeName}
看下前面的代码吧。structItems 并不是这里专用的。这里只是偷懒沿用了前面用过的structItems

2024-11-11 13:01 UTC, oldme-git approved these changes

2024-12-05 06:44 UTC, merged