test(drivers/mssql): add transation unit testing
gogf/gf pull request #3818
Opened 2024-09-27 05:35 UTC by oldme-git

2024-09-28 03:25 UTC, gqcn requested changes

2024-09-28 03:25 UTC, gqcn commented on contrib/drivers/mssql/mssql_z_unit_transaction_test.go
> +}
你这里的单测应该是从`contrib/drivers/mysql`那边拷贝过来的，那块代码有些老旧了，主要是再单测这里，在`Case`内部应该使用断言例如`t.AssertNil/t.Assert`，之前都是用的`if`判断。这里有一些工作量，方便统一修改一下吗？😅

2024-09-28 16:03 UTC, oldme-git commented on contrib/drivers/mssql/mssql_z_unit_transaction_test.go
> +}
好，后面我把mysql也一起改一下

2024-09-29 02:17 UTC, gqcn commented on contrib/drivers/mssql/mssql_z_unit_transaction_test.go
> +}
@oldme-git 辛苦了，你是最棒的🫡

2024-11-20 12:22 UTC, gqcn approved these changes

2024-12-05 06:44 UTC, merged