fix(util/gconv/internal/structcache): fix same tag field overwrite bug
gogf/gf pull request #3822
Opened 2024-09-27 09:15 UTC by helloteemo

Fixes #3821

现状：CachedStructInfo 结构体限定了tag、FieldName只能出现一次，同名FieldName、tag放在OtherSameNameField字段中作为补充

问题：AddField函数仅检查同名FieldName，未检查同名tag

解决方案：当存在同名tag时添加到已存在tag的OtherSameNameField中。

2024-09-28 03:11 UTC, gqcn requested changes

2024-09-28 03:11 UTC, gqcn commented on util/gconv/internal/structcache/structcache_cached_test.go
> +func Test_parseStructToCachedStructInfo(t *testing.T) {
- 你好，这个单测case请放到外层单测文件中，对应文件为 https://github.com/gogf/gf/blob/master/util/gconv/gconv_z_unit_issue_test.go
- 此外，你这个单测可能就不应该按照内部逻辑进行编写和断言了，应该按照issue使用方式按照使用者的角度来编写和断言。具体可以参考该文件已有的单测。

2024-09-29 06:29 UTC, helloteemo commented on util/gconv/internal/structcache/structcache_cached_test.go
> +func Test_parseStructToCachedStructInfo(t *testing.T) {
已处理，按照建议，已将单测用例放在对应文件中，同时增加按照使用者角度编写的单侧与断言。

还是保留了内部逻辑的校验，如果觉得无必要可删减对应代码

2024-09-29 06:30 UTC, helloteemo commented on util/gconv/internal/structcache/structcache_cached_test.go
> +	// can't use gtest.C, because it's import cycle
收到，已处理

2024-09-29 06:31 UTC, helloteemo commented on util/gconv/internal/structcache/structcache_cached_struct_info.go
> +			}
感谢您的建议，对我非常有帮助，在书写单测时注意到及时有同名的Field也需要添加对应的Tag，因此重新修改了对应的代码。期待您的再次review

2024-09-29 09:04 UTC, gqcn commented
@helloteemo 你好，我对注释和变量命名做了一些修改便于更好理解和长期维护 https://github.com/helloteemo/gf/pull/1

2024-09-29 10:37 UTC, helloteemo commented
> @helloteemo 你好，我对注释和变量命名做了一些修改便于更好理解和长期维护 [helloteemo#1](https://github.com/helloteemo/gf/pull/1)

2024-09-29 12:56 UTC, gqcn requested changes

2024-09-29 12:56 UTC, gqcn commented on util/gconv/gconv_z_unit_issue_test.go
> +		_ = structInfo
这两段代码看起来没有什么意义，是否应该删掉？

2024-09-29 12:57 UTC, gqcn commented
@wln32 我初步看了没看出什么问题，你在double check一下呢？

2024-09-29 23:11 UTC, wln32 commented on util/gconv/gconv_z_unit_issue_test.go
> +		var record = map[string]interface{}{
只保留这个测试即可，上面的测试属于内部实现，不保证稳定，没必要

2024-09-29 23:11 UTC, wln32 commented on util/gconv/internal/structcache/structcache_cached_struct_info.go
> +		newFieldInfo := csi.makeOrCopyCachedInfo(
没必要这样子改吧，这样子反而看不太明白了，比如44行的变量ok和53行的判断就没有必要隔这么远，
@gqcn 我觉得没有必要为了封装而封装

2024-09-30 02:13 UTC, helloteemo commented on util/gconv/gconv_z_unit_issue_test.go
> +		var record = map[string]interface{}{
好的，会删除掉内部测试代码

2024-09-30 02:13 UTC, helloteemo commented on util/gconv/gconv_z_unit_issue_test.go
> +		_ = structInfo
好的，会删除掉这段测试代码

2024-09-30 02:37 UTC, helloteemo commented on util/gconv/internal/structcache/structcache_cached_struct_info.go
> +		newFieldInfo := csi.makeOrCopyCachedInfo(
非常感谢您的建议，

1. `makeOrCopyCachedInfo` 是能够根据当前的Field统一创建FieldInfo行为，可封装也可不封装，封装的话函数cached可以放在内部逻辑中，这样会更为清晰，也比较符合您的第二点意见，见代码2改动
2. ok变量间隔较远确实比较影响代码的可读性，可以这样修改，见代码1改动


代码1: 

```go
func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
	tagOrFieldNameArray := csi.genPriorityTagAndFieldName(field, priorityTags)
	for _, tagOrFieldName := range tagOrFieldNameArray {
		var newFieldInfo *CachedFieldInfo
		cachedFieldInfo := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
		if cachedFieldInfo == nil || cachedFieldInfo.StructField.Type != field.Type {
			newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
		} else {
			newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
		}
		newFieldInfo.IsField = tagOrFieldName == field.Name

		if newFieldInfo.IsField {
			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
		}
		cachedFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
		if ok && cachedFieldInfo != nil {
			cachedFieldInfo.OtherSameNameField = append(cachedFieldInfo.OtherSameNameField, newFieldInfo)
			continue
		}
		csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
	}
}
```

代码2: 

```go
func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
	tagOrFieldNameArray := csi.genPriorityTagAndFieldName(field, priorityTags)
	for _, tagOrFieldName := range tagOrFieldNameArray {
		newFieldInfo := csi.makeOrCopyCachedInfo(
			field, fieldIndexes, priorityTags, tagOrFieldName,
		)
		if newFieldInfo.IsField {
			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
		}
		cachedFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
		if ok {
			cachedFieldInfo.OtherSameNameField = append(cachedFieldInfo.OtherSameNameField, newFieldInfo)
			continue
		}
		csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
	}
}

func (csi *CachedStructInfo) makeOrCopyCachedInfo(
	field reflect.StructField,
	fieldIndexes []int,
	priorityTags []string,
	currTagOrFieldName string,
) (newFieldInfo *CachedFieldInfo) {
	cachedFieldInfo := csi.tagOrFiledNameToFieldInfoMap[currTagOrFieldName]
	if cachedFieldInfo == nil || cachedFieldInfo.StructField.Type != field.Type {
		// If the types are different, some information needs to be reset.
		newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
	} else {
		// If the field types are the same.
		newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
	}
	newFieldInfo.IsField = currTagOrFieldName == field.Name
	return
}
```

2024-09-30 11:05 UTC, wln32 commented on util/gconv/internal/structcache/structcache_cached_struct_info.go
> +		newFieldInfo := csi.makeOrCopyCachedInfo(
> 非常感谢您的建议，
> 
> 1. `makeOrCopyCachedInfo` 是能够根据当前的Field统一创建FieldInfo行为，可封装也可不封装，封装的话函数cached可以放在内部逻辑中，这样会更为清晰，也比较符合您的第二点意见，见代码2改动
> 2. ok变量间隔较远确实比较影响代码的可读性，可以这样修改，见代码1改动
> 
> 代码1:
> 
> ```go
> func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
> 	tagOrFieldNameArray := csi.genPriorityTagAndFieldName(field, priorityTags)
> 	for _, tagOrFieldName := range tagOrFieldNameArray {
> 		var newFieldInfo *CachedFieldInfo
> 		cachedFieldInfo := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
> 		if cachedFieldInfo == nil || cachedFieldInfo.StructField.Type != field.Type {
> 			newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> 		} else {
> 			newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
> 		}
> 		newFieldInfo.IsField = tagOrFieldName == field.Name
> 
> 		if newFieldInfo.IsField {
> 			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
> 		}
> 		cachedFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
> 		if ok && cachedFieldInfo != nil {
> 			cachedFieldInfo.OtherSameNameField = append(cachedFieldInfo.OtherSameNameField, newFieldInfo)
> 			continue
> 		}
> 		csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
> 	}
> }
> ```
> 
> 代码2:
> 
> ```go
> func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
> 	tagOrFieldNameArray := csi.genPriorityTagAndFieldName(field, priorityTags)
> 	for _, tagOrFieldName := range tagOrFieldNameArray {
> 		newFieldInfo := csi.makeOrCopyCachedInfo(
> 			field, fieldIndexes, priorityTags, tagOrFieldName,
> 		)
> 		if newFieldInfo.IsField {
> 			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
> 		}
> 		cachedFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
> 		if ok {
> 			cachedFieldInfo.OtherSameNameField = append(cachedFieldInfo.OtherSameNameField, newFieldInfo)
> 			continue
> 		}
> 		csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
> 	}
> }
> 
> func (csi *CachedStructInfo) makeOrCopyCachedInfo(
> 	field reflect.StructField,
> 	fieldIndexes []int,
> 	priorityTags []string,
> 	currTagOrFieldName string,
> ) (newFieldInfo *CachedFieldInfo) {
> 	cachedFieldInfo := csi.tagOrFiledNameToFieldInfoMap[currTagOrFieldName]
> 	if cachedFieldInfo == nil || cachedFieldInfo.StructField.Type != field.Type {
> 		// If the types are different, some information needs to be reset.
> 		newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> 	} else {
> 		// If the field types are the same.
> 		newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
> 	}
> 	newFieldInfo.IsField = currTagOrFieldName == field.Name
> 	return
> }
> ```

我认为还是没有原来的可读性高，原来的流程很清晰，根据tag或者fieldName判断是否存在，做对应的处理，然后在判断类型是否相同，再处理，能封装的地方可能就是判断类型是否相同哪里。
代码1 csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] 查找了两次，没必要
代码2 if cachedFieldInfo == nil || cachedFieldInfo.StructField.Type != field.Type 这里的判断有歧义，判断等于nil和类型不同属于不同的逻辑， == nil  是不存在的时候，!= field.Type是类型不同，两者本身没有关联

2024-10-01 00:07 UTC, wln32 commented
> @wln32 我初步看了没看出什么问题，你再double check一下呢？

```go
func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
        cachedFieldInfo := csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
	for _, tagOrFieldName := range cachedFieldInfo.PriorityTagAndFieldName {
		newFieldInfo := cachedFieldInfo.CopyByTagOrFieldName(tagOrFieldName)
		if newFieldInfo.IsField {
			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
		}
		alreadyExistFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
		if !ok {
			csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
		} else {
			if alreadyExistFieldInfo.StructField.Type == field.Type {
				// If the field name and type are the same
				newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
			} else {
				// If the types are different, some information needs to be reset
				newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
			}
			alreadyExistFieldInfo.OtherSameNameField = append(
				alreadyExistFieldInfo.OtherSameNameField,
				newFieldInfo,
			)
		}
	}

}

func(cfi *CachedFieldInfo)CopyByTagOrFieldName(tagOrFieldName string)*CachedFieldInfo {
	return &CachedFieldInfo{
		CachedFieldInfoBase: cfi.CachedFieldInfoBase,
		IsField:             cfi.FieldName() == tagOrFieldName,
	}
}


```

@gqcn @helloteemo 这样子觉得怎么样？

2024-10-01 12:35 UTC, helloteemo commented
> > @wln32 我初步看了没看出什么问题，你再double check一下呢？
> 
> ```go
> func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
>         cachedFieldInfo := csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> 	for _, tagOrFieldName := range cachedFieldInfo.PriorityTagAndFieldName {
> 		newFieldInfo := cachedFieldInfo.CopyByTagOrFieldName(tagOrFieldName)
> 		if newFieldInfo.IsField {
> 			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
> 		}
> 		alreadyExistFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
> 		if !ok {
> 			csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
> 		} else {
> 			if alreadyExistFieldInfo.StructField.Type == field.Type {
> 				// If the field name and type are the same
> 				newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
> 			} else {
> 				// If the types are different, some information needs to be reset
> 				newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> 			}
> 			alreadyExistFieldInfo.OtherSameNameField = append(
> 				alreadyExistFieldInfo.OtherSameNameField,
> 				newFieldInfo,
> 			)
> 		}
> 	}
> 
> }
> 
> func(cfi *CachedFieldInfo)CopyByTagOrFieldName(tagOrFieldName string)*CachedFieldInfo {
> 	return &CachedFieldInfo{
> 		CachedFieldInfoBase: cfi.CachedFieldInfoBase,
> 		IsField:             cfi.FieldName() == tagOrFieldName,
> 	}
> }
> ```
> 
> @gqcn @helloteemo 这样子觉得怎么样？

不太建议 `CopyByTagOrFieldName` 复用cfi本身的内存，容易出现一些奇奇怪怪的问题

2024-10-01 12:45 UTC, helloteemo commented on util/gconv/internal/structcache/structcache_cached_struct_info.go
> +		newFieldInfo := csi.makeOrCopyCachedInfo(
@wln32 

现有的流程也比较清晰：
1. 根据tag或fieldName创建好FieldInfo，属于预处理过程
2. 做对应处理：发现有同名tag或FieldName就需要加入到SameInfo中，否则就加入到map上


确实认为代码1不太好理解

代码2 if 逻辑是用来区分我们是需要计算FieldInfo还根据现有的FieldCache修改一下条件就可以得到FieldInfo，而不能根据现有FieldCache的条件为：本身就不存在cache，cache的类型不一致，就需要重新计算了。逻辑上个人理解是通顺的。

`makeOrCopyCachedInfo` 有一次查找是正常的现象，不会有很高性能损耗的

2024-10-02 00:19 UTC, wln32 commented
> > > @wln32 我初步看了没看出什么问题，你再double check一下呢？
> > 
> > 
> > ```go
> > func (csi *CachedStructInfo) AddField(field reflect.StructField, fieldIndexes []int, priorityTags []string) {
> >         cachedFieldInfo := csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> > 	for _, tagOrFieldName := range cachedFieldInfo.PriorityTagAndFieldName {
> > 		newFieldInfo := cachedFieldInfo.CopyByTagOrFieldName(tagOrFieldName)
> > 		if newFieldInfo.IsField {
> > 			csi.FieldConvertInfos = append(csi.FieldConvertInfos, newFieldInfo)
> > 		}
> > 		alreadyExistFieldInfo, ok := csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName]
> > 		if !ok {
> > 			csi.tagOrFiledNameToFieldInfoMap[tagOrFieldName] = newFieldInfo
> > 		} else {
> > 			if alreadyExistFieldInfo.StructField.Type == field.Type {
> > 				// If the field name and type are the same
> > 				newFieldInfo = csi.copyCachedInfoWithFieldIndexes(cachedFieldInfo, fieldIndexes)
> > 			} else {
> > 				// If the types are different, some information needs to be reset
> > 				newFieldInfo = csi.makeCachedFieldInfo(field, fieldIndexes, priorityTags)
> > 			}
> > 			alreadyExistFieldInfo.OtherSameNameField = append(
> > 				alreadyExistFieldInfo.OtherSameNameField,
> > 				newFieldInfo,
> > 			)
> > 		}
> > 	}
> > 
> > }
> > 
> > func(cfi *CachedFieldInfo)CopyByTagOrFieldName(tagOrFieldName string)*CachedFieldInfo {
> > 	return &CachedFieldInfo{
> > 		CachedFieldInfoBase: cfi.CachedFieldInfoBase,
> > 		IsField:             cfi.FieldName() == tagOrFieldName,
> > 	}
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @gqcn @helloteemo 这样子觉得怎么样？
> 
> 不太建议 `CopyByTagOrFieldName` 复用cfi本身的内存，容易出现一些奇奇怪怪的问题

什么问题呢？可以举例说下吗，一般来说，每个结构体字段会保存两个同样信息的key进map，tag和fieldName，这两个的信息本身是一个的，除了那个IsField不是共享的，其他都是共享的，比如类型，字段索引，转换函数之类的，没有什么区别

2024-10-08 02:25 UTC, helloteemo commented
@wln32 好的，我会晚一些处理，感谢review，对我提升很大

2024-10-12 02:58 UTC, helloteemo commented
@wln32 不好意思，久等了，按照CR意见已修改变量名，同时将makeOrCopy函数的if条件拆开。test代码已删减

2024-10-12 10:28 UTC, wln32 approved these changes

2024-10-14 13:34 UTC, gqcn approved these changes

2024-10-14 13:34 UTC, merged