fix(net/goai): cannot customize OpenAPIv3 type for request parameters
gogf/gf pull request #3845
Opened 2024-10-07 07:41 UTC by gqcn

fixed #3135

2024-10-08 01:42 UTC, oldme-git requested changes

2024-10-08 01:42 UTC, oldme-git commented on net/goai/goai_z_unit_issue_test.go
> +	"github.com/gogf/gf/v2/util/guid"
格式化一下

2024-10-08 01:42 UTC, oldme-git commented on net/goai/goai_z_unit_test.go
>  		fmt.Println(oai)
这个打印有必要吗

2024-10-08 05:51 UTC, gqcn commented on net/goai/goai_z_unit_issue_test.go
> +	"github.com/gogf/gf/v2/util/guid"
done

2024-10-08 05:51 UTC, gqcn commented on net/goai/goai_z_unit_test.go
>  		fmt.Println(oai)
done

2024-10-08 13:35 UTC, gqcn commented
@gqcn It's a test.

2024-10-09 01:32 UTC, oldme-git approved these changes

2024-10-09 05:15 UTC, merged