feat(trace): add trace for Custom trace client and provider
gogf/gf pull request #3847
Opened 2024-10-08 11:07 UTC by houseme

feat(trace): add trace for Custom trace client and provider 

#3171 #3201 #3834

2024-10-08 13:57 UTC, gqcn requested changes

2024-10-08 13:57 UTC, gqcn commented on contrib/trace/provider/provider.go
> +		resource.WithAttributes(
这种带有`With*`设置的方法灵活性比较高，这里的`NewResource`直接封装死了了几个参数`serviceName, serverIP string`是不是不太合适？

2024-10-08 13:57 UTC, gqcn commented on contrib/trace/provider/provider.go
> +	return trace.NewBatchSpanProcessor(exporter)
我没太明白这样封装得意义是什么？

2024-10-08 13:57 UTC, gqcn commented on contrib/trace/provider/provider.go
> +func NewTracerProviderOptions(sampler trace.Sampler, resource *resource.Resource, spanProcessor trace.SpanProcessor) []trace.TracerProviderOption {
这块的参数也封装得比较死，是不是直接暴露第三方的`options`让用户来自定义更合适一些？

2024-10-08 14:27 UTC, houseme commented on contrib/trace/provider/provider.go
> +func NewTracerProviderOptions(sampler trace.Sampler, resource *resource.Resource, spanProcessor trace.SpanProcessor) []trace.TracerProviderOption {
这里只是一个默认的，也可以直接使用`InitTracer` 方法，按照 `opts ...trace.TracerProviderOption` 传参。

2024-10-08 14:28 UTC, houseme commented on contrib/trace/provider/provider.go
> +		resource.WithAttributes(
修改了名称，为默认方法，以及再提供方法，传入`opts ...resource.Option` 参数。

2024-10-08 14:30 UTC, houseme commented on contrib/trace/provider/provider.go
> +	return trace.NewBatchSpanProcessor(exporter)
`trace.SpanProcessor`接口有2种实现，这是其中一种，也可直接使用`trace.NewBatchSpanProcessor(exporter)` 或 `trace.NewSimpleSpanProcessor(exporter)`

2024-10-09 05:41 UTC, gqcn commented
@houseme 我总感觉没有封装初始化`TraceProvider`的需要，因为封装后灵活性肯定缺失了。可以保留之前的`otlpgrpc/otlphttp`组件，提供的是默认的`TraceProvider`初始化实现，如果用户想要更灵活的`Trace`设置，就自己初始化`Provider`，咱们在提供的组件源码中注释说明一下就好了。这样对于咱们未来维护成本也低。

2024-10-09 05:42 UTC, gqcn requested changes

2024-10-09 05:42 UTC, gqcn commented on contrib/trace/provider/provider.go
> +	return trace.NewBatchSpanProcessor(exporter)
这里让用户直接使用`trace.NewBatchSpanProcessor(exporter)`不行么？

2024-10-09 09:16 UTC, houseme commented on contrib/trace/provider/provider.go
> +	return trace.NewBatchSpanProcessor(exporter)
可以，`NewBatchSpanProcessor` 和 `NewBatchSpanProcessor` 可以删除，直接使用 `trace.NewBatchSpanProcessor(exporter)` 或 `trace.NewSimpleSpanProcessor(exporter)`

2024-10-09 12:42 UTC, gqcn commented
> > @houseme 我总感觉没有封装初始化`TraceProvider`的需要，因为封装后灵活性肯定缺失了。可以保留之前的`otlpgrpc/otlphttp`组件，提供的是默认的`TraceProvider`初始化实现，如果用户想要更灵活的`Trace`设置，就自己初始化`Provider`，咱们在提供的组件源码中注释说明一下就好了。这样对于咱们未来维护成本也低。
> 
> 或许把这一块的代码移到`example/trace/provider` 目录，提供一个示例，需要自定义的按照示例写。

嗯，我觉得这样好。另外咱们现有组件完善下注释，说明下如果自定义的初始化参考哪里。

2024-10-10 05:00 UTC, houseme commented
> > > @houseme 我总感觉没有封装初始化`TraceProvider`的需要，因为封装后灵活性肯定缺失了。可以保留之前的`otlpgrpc/otlphttp`组件，提供的是默认的`TraceProvider`初始化实现，如果用户想要更灵活的`Trace`设置，就自己初始化`Provider`，咱们在提供的组件源码中注释说明一下就好了。这样对于咱们未来维护成本也低。
> > 
> > 
> > 或许把这一块的代码移到`example/trace/provider` 目录，提供一个示例，需要自定义的按照示例写。
> 
> 嗯，我觉得这样好。另外咱们现有组件完善下注释，说明下如果自定义的初始化参考哪里。

改完了，看看需要改进一下注释不

2024-10-10 14:04 UTC, gqcn commented
> https://github.com/gogf/gf/pull/3847#issuecomment-2404026348

个人感觉这样挺好的，可以在`otlpgrpc`和`otlphttp`包的注释中完善一下，说一下如果想要更灵活第配置`Tracing`参数，那么参数example的哪个文件，放个链接过去即可。

2024-10-11 03:39 UTC, houseme commented
> > [#3847 (comment)](https://github.com/gogf/gf/pull/3847#issuecomment-2404026348)
> 
> 个人感觉这样挺好的，可以在`otlpgrpc`和`otlphttp`包的注释中完善一下，说一下如果想要更灵活第配置`Tracing`参数，那么参数example的哪个文件，放个链接过去即可。

改了，也加上注释说明

2024-10-12 10:25 UTC, wln32 approved these changes

2024-10-14 13:28 UTC, gqcn approved these changes

2024-10-14 13:30 UTC, merged