database/gdb: add exist feature #3657 reopen
gogf/gf pull request #3854
Opened 2024-10-14 17:08 UTC by cyjaysong

database/gdb: add exist feature  #3657 reopen

2024-10-15 13:13 UTC, gqcn commented
@cyjaysong 你好，我仔细看了一下，这个`Exist`能力可以通过`Count`来实现，内部并不需要执行`Limit`操作，因为`Count`操作通常都是只有`1`条记录，也只会取第一条记录的数据值。并且在最新版本中，如果`Count`查询的字段大于`1`，会有报错。因此这个`Exist`功能并不是很需要。

2024-10-16 05:24 UTC, cyjaysong commented
@gqcn

2024-10-16 14:21 UTC, gqcn requested changes

2024-10-16 14:21 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	var (
是否直接使用`return m.Fields(1).One()`就可以了？

2024-10-16 14:21 UTC, gqcn commented on contrib/drivers/clickhouse/clickhouse_z_unit_model_test.go
> +		exist, err := db.Model(table).Exist()
请在`Exist`查询加上条件语句。以下同。

2024-10-16 15:40 UTC, cyjaysong commented on database/gdb/gdb_model_select.go
> +	var (
间接能实现，但直接得到bool的结果不是更好么，开发也更方便不是

2024-10-16 15:43 UTC, cyjaysong commented on contrib/drivers/clickhouse/clickhouse_z_unit_model_test.go
> +		exist, err := db.Model(table).Exist()
已添加

2024-10-17 02:03 UTC, cyjaysong commented on database/gdb/gdb_model_select.go
> +	var (
试了一下Fields(1)未生效

2024-10-18 01:30 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	var (
> 间接能实现，但直接得到bool的结果不是更好么，开发也更方便不是

我的意思，你这里的实现逻辑复杂了一点，可以简化为`return m.Fields(1).One()`，稍等我试试。

2024-10-19 03:18 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	var (
@cyjaysong 确实不支持，稍等，我来看看先能不能改进下这里的`Fields`方法。

2024-10-19 04:20 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +	var (
@cyjaysong 我已经对`Fields`做了改进 https://github.com/gogf/gf/pull/3873 ，等那个PR合并后，你可以合并一下主库的主分支，随后你的这里可以使用`return m.Fields(Raw(1)).One()`便简化很多。我会持续关注该PR。

2024-10-19 04:23 UTC, gqcn requested changes

2024-10-19 04:23 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +			sqlWithHolder = fmt.Sprintf("SELECT COUNT(1) FROM (%s) AS T", m.rawSql)
为什么这里不使用`SELECT 1`呢？

2024-10-19 08:06 UTC, cyjaysong commented on database/gdb/gdb_model_select.go
> +			sqlWithHolder = fmt.Sprintf("SELECT COUNT(1) FROM (%s) AS T", m.rawSql)
我也想啊，这个地方使用`SELECT 1` 的话，这里得到的SQL是`SELECT 1 FROM (SELECT * FROM user_1729128487) AS T LIMIT 1` ，但是啊，Oracle 数据库那边文件路径`contrib/drivers/oracle/oracle_do_filter.go`，有个逻辑把实际执行的SQL 转换成了  `SELECT * FROM ( SELECT GFORM.*, ROWNUM ROW_NUMBER__ FROM (SELECT  1 FROM (SELECT * FROM user_1729128487) AS T ) GFORM WHERE ROWNUM <= 1 ) WHERE ROW_NUMBER__ > 0` 测试报`ORA-00907: missing right parenthesis` 。 后来我发现如果代码走这里了，即便是现在这个逻辑，Oracle还是有问题 `SELECT COUNT(1) FROM (SELECT * FROM user_1729131134) AS T: ORA-00933: SQL command not properly ended` 。可头疼死我了

2024-10-21 01:23 UTC, gqcn commented on database/gdb/gdb_model_select.go
> +			sqlWithHolder = fmt.Sprintf("SELECT COUNT(1) FROM (%s) AS T", m.rawSql)
@cyjaysong  明白了，咱们一起看看呢。可能需要花点时间哈。

2024-10-24 07:28 UTC, gqcn approved these changes

2024-10-24 07:29 UTC, merged