add cache
gogf/gf pull request #3857
Opened 2024-10-15 06:29 UTC by wwwfeng

不知道理解的对不对
before：
![before](https://github.com/user-attachments/assets/5d8dddce-3530-4bd6-912d-365caca2f5f6)
after:
![after](https://github.com/user-attachments/assets/f2e3f5d7-4883-43fb-94cd-5c1e491d5c87)

2024-10-15 13:38 UTC, gqcn commented
related issue https://github.com/gogf/gf/issues/3852

2024-10-16 00:00 UTC, gqcn requested changes

2024-10-16 00:00 UTC, gqcn commented on util/gmeta/gmeta.go
> +	if cachedData, ok := cachedMetadata.Load(reflectType.String()); ok {
看起来CI失败问题是由`reflectType.String()`引起的，因为在同一个包中可能存在局部定义的数据结构，他们的`reflectType.String()`都是相同的，但是`reflectType`不同，因此建议将缓存的键名修改为`reflectType`。

2024-10-16 02:04 UTC, wwwfeng commented on util/gmeta/gmeta.go
> +	if cachedData, ok := cachedMetadata.Load(reflectType.String()); ok {
👍🏻 确实如此，没考虑到这点

2024-10-16 05:16 UTC, gqcn requested changes

2024-10-16 05:16 UTC, gqcn commented on util/gmeta/gmeta.go
>  	reflectType, err := gstructs.StructType(object)
如果把这里的`gstructs.StructType`改为`reflect.TypeOf`应该能更进一步提高性能。

2024-10-16 07:28 UTC, wwwfeng commented on util/gmeta/gmeta.go
>  	reflectType, err := gstructs.StructType(object)
强哥，似乎不太行。`reflectType := reflect.TypeOf(object)` 没有办法解析下面的case，为了兼容下面这些case会在Data里面再实现一次gstructs.StructType
```
type A struct {
	gmeta.Meta `tag:"123" orm:"456"`
	Id         int
	Name       string
}

        a := &[]A{
		{Id: 200,
			Name: "alice"},
	}

	b := []*A{
		{Id: 300,
			Name: "bob"},
	}
```

2024-10-16 14:25 UTC, gqcn commented on util/gmeta/gmeta.go
>  	reflectType, err := gstructs.StructType(object)
好的，看样子之前我写的`gstructs.StructType`实在是太棒了。

2024-10-16 14:32 UTC, gqcn commented
@wwwfeng 奇怪，我这基准测试性能还比加缓存前差了很多，而且还没发运行完
![QQ_1729089095915](https://github.com/user-attachments/assets/a30d327e-23cb-44c1-82de-ffafa5a7a852)

2024-10-16 15:39 UTC, wwwfeng commented
> @wwwfeng 奇怪，我这基准测试性能还比加缓存前差了很多，而且还没发运行完 ![QQ_1729089095915](https://private-user-images.githubusercontent.com/26347176/377099657-a30d327e-23cb-44c1-82de-ffafa5a7a852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTE0ODYsIm5iZiI6MTcyOTA5MTE4NiwicGF0aCI6Ii8yNjM0NzE3Ni8zNzcwOTk2NTctYTMwZDMyN2UtMjNjYi00NGMxLTgyZGUtZmZhZmE1YTdhODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE1MDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YTRkNzZhZTExYmYzMmFiZTRkNzQ3MGY4YTNmNDkxN2FkMWZjZGU2YzcwMTlkZWI3ZDZlM2JlYjY1M2I3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xUgrhD93o_jPNDCs7wnHI9QWfotVep9FuBqmwz4IU3U)

奇怪，我这边测试无法复现
<img width="1768" alt="image" src="https://github.com/user-attachments/assets/34a9da40-571e-4ec3-a11e-2a2aba0a6b6c">

无法完成基准测试倒是像这个场景🙈
`cachedMetadata.Load(reflectType)`

2024-10-18 01:21 UTC, gqcn commented
> @wwwfeng 奇怪，我这基准测试性能还比加缓存前差了很多，而且还没发运行完 ![QQ_1729089095915](https://private-user-images.githubusercontent.com/26347176/377099657-a30d327e-23cb-44c1-82de-ffafa5a7a852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTQ2ODAsIm5iZiI6MTcyOTIxNDM4MCwicGF0aCI6Ii8yNjM0NzE3Ni8zNzcwOTk2NTctYTMwZDMyN2UtMjNjYi00NGMxLTgyZGUtZmZhZmE1YTdhODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDAxMTk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDc0MjM2ODE5YWFjYjA3NjczMTc4MzhiNzg0M2E0ZTZkMmUwZDkxMWNiMjBjZDkxZjBhNWZiMDAyNmUwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FKOpFIlRIEm23yqOqPUAyHCQYjwr33-ANqQcWB5M7OM)

@hailaz @houseme @oldme-git @wln32 大伙一起试试呢，不晓得是不是我环境问题。

2026-08-06 08:47 UTC, lingcoder commented
年久失修，非功能性修复

2026-08-06 08:47 UTC, closed without merging