feat(contrib/nacos): Allows custom actions after a remote profile update
gogf/gf pull request #3858
Opened 2024-10-16 03:10 UTC by LanceAdd

Allows custom actions after a remote profile update

2024-10-16 05:18 UTC, gqcn requested changes

2024-10-16 05:18 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +func New(ctx context.Context, config Config, actions ...func()) (adapter gcfg.Adapter, err error) {
建议将`OnChange`回调函数配置到`Config`中。

2024-10-16 05:20 UTC, gqcn requested changes

2024-10-16 05:20 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +		wg.Wait()
为什么这样要用`sync.WaitGroup`呢，如果有一个`OnChange`回调函数阻塞了，基础的配置管理能力也会失效。

2024-10-16 05:49 UTC, LanceAdd commented on contrib/config/nacos/nacos.go
> +		wg.Wait()
利用context.WithTimeout来防止超时可以吗

2024-10-16 05:51 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +		wg.Wait()
@LanceAdd 让`OnChange`的回调函数编写者自己去保证吧，咱们不加`WaitGroup`就好，直接`go Xxx()`就行了。

2024-10-24 07:09 UTC, gqcn requested changes

2024-10-24 07:09 UTC, gqcn commented on contrib/config/nacos/nacos.go
> +	OnConfigChange func()                  // Configure change callback function
为什么不按照`c.config.ConfigParam.OnChange`那样的回调函数定义方式呢？

2024-10-24 07:26 UTC, LanceAdd commented on contrib/config/nacos/nacos.go
> +	OnConfigChange func()                  // Configure change callback function
`func(namespace, group, dataId, data string) `我当时的想法是这些原始信息对开发者来说应该没什么意义，一般都是在回调中使用gctx和gcfg获取更新后的配置内容进行自定义操作，我想不到有什么场景需要在更新配置后的回调中使用原始配置字符串和nacos的配置信息，可能我的开发经验涉及的场景还是有点太少了
```
func (c *Client) addWatcher() error {
	if !c.config.Watch {
		return nil
	}
	c.config.ConfigParam.OnChange = func(namespace, group, dataId, data string) {
		c.doUpdate(data)
		if c.config.OnConfigChange != nil {
			go c.config.OnConfigChange()
		}
	}

	if err := c.client.ListenConfig(c.config.ConfigParam); err != nil {
		return gerror.Wrap(err, `watch config from namespace failed`)
	}

	return nil
}
```

2024-11-11 13:03 UTC, gqcn approved these changes

2024-12-01 11:57 UTC, houseme commented on contrib/config/nacos/nacos_test.go
> +	"net/url"
这个引入还原一下

2024-12-01 11:57 UTC, houseme commented on contrib/config/nacos/nacos.go
> -
这个引入还原一下

2024-12-07 06:23 UTC, gqcn commented
@LanceAdd 请处理一下文件冲突。

2024-12-07 06:55 UTC, houseme commented
如何处理 import 可以看下 #4010

2024-12-10 02:43 UTC, LanceAdd commented on contrib/config/nacos/nacos_test.go
> +	"net/url"
好的

2024-12-10 02:48 UTC, LanceAdd commented
> 如何处理 import 可以看下 #4010

好的，我学习下

2024-12-11 10:54 UTC, houseme commented
@LanceAdd 需要您在自己分支提交一次commit，会自动格式化 `contrib/config/nacos/nacos.go` 和 `contrib/config/nacos/nacos_test.go` ,谢谢

2024-12-12 04:52 UTC, LanceAdd commented
因为使用master分支的原因导致gci无法正常使用，使用新的分支处理该PR

2024-12-12 04:54 UTC, closed without merging