feat(net/goai): enhance openapi doc with responses and examples
gogf/gf pull request #3859
Opened 2024-10-16 08:50 UTC by UncleChair

Fixes #3747 
- Added tags for response status and exampls
- Added interface EnhancedResponse for other error response generation
- Added coresponding test case
  - github.com/gogf/gf/v2/net/goai  0.631s  coverage: 80.5% of statements

2024-10-17 01:47 UTC, oldme-git requested changes

2024-10-17 01:47 UTC, oldme-git commented on net/goai/goai_example.go
> +	if e == nil {
这里可以使用 g.IsNil 吗，e == nil 有坑

2024-10-17 01:47 UTC, oldme-git commented on net/goai/goai_example.go
> +	return nil
可以使用 
```
if json == ""  {
    return
}
var data interface{}
err := gjson.Unmarshal([]byte(json), &data)
....
```
控制反转，提前返回，使代码减少缩进，增加可读性

2024-10-17 01:47 UTC, oldme-git commented on net/goai/goai_response_ref.go
> +	if _, ok := (*r)[status]; !ok {
这里也可以先判断 ok 为 true 提前返回，将主体代码逻辑提到主函数里来

2024-10-17 05:34 UTC, UncleChair commented on net/goai/goai_example.go
> +	if e == nil {
感谢指正，已更改

2024-10-17 05:35 UTC, UncleChair commented on net/goai/goai_example.go
> +	return nil
已更改

2024-10-17 05:35 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +	if _, ok := (*r)[status]; !ok {
已更改

2024-10-17 05:56 UTC, oldme-git commented on net/goai/goai_response_ref.go
> +func (r *Responses) AddStatus(oai *OpenApiV3, status string, object interface{}, businessStructName string, isDefault bool) error {
定义新的公共方法，可以写一下这个函数作用的详细注释吗

2024-10-17 08:19 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +func (r *Responses) AddStatus(oai *OpenApiV3, status string, object interface{}, businessStructName string, isDefault bool) error {
想了一下还是改成了私有方法，oai在没有Path的时候用户自己调用函数添加status可能会有奇怪的问题，添加起来也不是很优雅，不知道这样行不行

2024-10-17 14:33 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +func (r *Responses) AddStatus(oai *OpenApiV3, status string, object interface{}, businessStructName string, isDefault bool) error {
重构了一下这块的方法，现在应该用起来比较符合直觉了

2024-10-19 03:00 UTC, gqcn requested changes

2024-10-19 03:00 UTC, gqcn commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
名称是否使用`SesponseStatusDef`更合适一些？

2024-10-19 03:06 UTC, gqcn requested changes

2024-10-19 03:06 UTC, gqcn commented on net/goai/goai_response_ref.go
> +func (oai *OpenApiV3) getResponseFromObject(object interface{}, isDefault ...bool) (*Response, error) {
如果没特别必要性，不不建议使用多参数的方式来当做非必须参数来使用。这里是内部方法，建议将`isDefault`参数定义为必传参数，内部根据调用场景传递`true/false`即可。

2024-10-19 04:54 UTC, UncleChair commented on net/goai/goai_response.go
> +type StatusCode = int
已添加

2024-10-19 04:54 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +	for _, v := range contentTypes {
已修改

2024-10-19 04:56 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +		}
已修改，原来的写法也会在contentType循环内部去处理schemaRef，这块我也一起拿出来了

2024-10-19 04:57 UTC, UncleChair commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
应该是 `ResponseStatusDef` ? 已修改

2024-10-19 04:57 UTC, UncleChair commented on net/goai/goai_response_ref.go
> +func (oai *OpenApiV3) getResponseFromObject(object interface{}, isDefault ...bool) (*Response, error) {
已修改

2024-10-19 05:09 UTC, wln32 approved these changes

2024-10-21 01:19 UTC, gqcn commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
@UncleChair 我指的是`interface`名称，不是方法名称。

2024-10-21 01:31 UTC, UncleChair commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
接口名称的话 `XXXResponse` 或者是 `XXXResponseDef` 这样可能会好一些？我的理解是具体的响应需要实现该接口才能有更多的状态信息，那么这个接口应该是 `Response` 的一种类型而不是 `Status` 的一种类型，所以命名为了 `EnhancedResponse` ，不知道这样理解有没有问题

2024-10-21 05:57 UTC, gqcn commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
如果是`EnhancedResponse`那么表示是对`Response`的扩展，比较宽泛。但是咱们这里只是对`Response Status`扩展，只对其中的状态码类型做扩展，所以这里使用`ResponseStatusDef`比较合适一些。
如果后续有对`Response`的其他类型做扩展，那么都是单独定义具体的接口。

2024-10-21 06:06 UTC, UncleChair commented on net/goai/goai_response.go
> +type EnhancedResponse interface {
@gqcn 感谢说明，已修改

2024-10-21 12:28 UTC, gqcn approved these changes

2024-10-21 12:49 UTC, oldme-git approved these changes

2024-10-21 13:16 UTC, merged