style(gtest/test): improve code
gogf/gf pull request #3891
Opened 2024-10-25 02:09 UTC by oldme-git

2024-11-11 13:25 UTC, gqcn requested changes

2024-11-11 13:25 UTC, gqcn commented on test/gtest/gtest_util.go
> +	ksExpect := rvExpect.MapKeys()
我发现这几行代码用`var`来包裹一下，缩进会更漂亮。

2024-11-12 01:16 UTC, oldme-git commented on test/gtest/gtest_util.go
> +	ksExpect := rvExpect.MapKeys()
Done

2024-11-12 12:20 UTC, gqcn approved these changes

2024-11-12 12:20 UTC, merged