feat(i18n/gi18n): support `fs.FS`
gogf/gf pull request #3942
Opened 2024-11-20 08:25 UTC by ynwcel

* 支持添加 fs.FS 路径
   * SetPathFS
 * `go test`
 
![gf-gi18n-add-std-fs](https://github.com/user-attachments/assets/1bd360f5-740a-441f-a29f-039c348ce8d7)

2024-11-22 11:33 UTC, hailaz approved these changes

2024-11-23 05:51 UTC, gqcn requested changes

2024-11-23 05:51 UTC, gqcn commented on i18n/gi18n/gi18n_manager.go
> +			pathType = opts.checkPathType(opts.Path)
能否不定义`SetPathFS`方法，直接在`checkPathType`中判断`opts.Path`路径是否存在于`fs.Fs`中，如果是得话则用`fs.Fs`，否则走原来默认逻辑。这样可以降低使用复杂度。

2024-12-09 15:13 UTC, gqcn commented
@ynwcel 我将会在近期，尝试在`gres`中支持`fs.FS`

2024-12-10 02:44 UTC, ynwcel commented
> @ynwcel 我将会在近期，尝试在`gres`中支持`fs.FS`
大佬牛的。。之前我想处理来着。但 github CI 报错了

2025-10-16 08:32 UTC, closed without merging