fix(database/gdb): gdb.Counter not work in OnDuplicate
gogf/gf pull request #4073
Opened 2024-12-24 03:55 UTC by cyjaysong

fix gdb.Counter not work in OnDuplicate

2024-12-24 07:34 UTC, houseme commented on contrib/drivers/pgsql/pgsql_format_upsert.go
> -
这一行别删除了，删除就会触发Action 目前的那个错误

2024-12-24 07:56 UTC, cyjaysong commented on contrib/drivers/pgsql/pgsql_format_upsert.go
> -
这也太奇葩了吧

2024-12-24 08:11 UTC, cyjaysong commented
@houseme 合吧

2024-12-24 08:33 UTC, cyjaysong commented
@houseme 老郭在搬砖呢

2024-12-24 10:35 UTC, houseme approved these changes

2024-12-24 14:22 UTC, gqcn requested changes

2024-12-24 14:22 UTC, gqcn commented on contrib/drivers/sqlite/sqlite_format_upsert.go
> +				)
- 大兄弟，你这重复代码有点多，你参考下原有代码的实现 https://github.com/gogf/gf/blob/f79aef666917b6f78fc6a89ebc68c4a188bf48d2/database/gdb/gdb_core.go#L624
- 同时，你可以把内部方法 https://github.com/gogf/gf/blob/f79aef666917b6f78fc6a89ebc68c4a188bf48d2/database/gdb/gdb_core.go#L588 提出来作为`Core`的内部私有方法，供内部访问复用。

2024-12-25 07:57 UTC, gqcn requested changes

2024-12-25 07:57 UTC, gqcn commented on database/gdb/gdb_core.go
> +// getCounterAlter The polished counter alter
如果描述不清楚就删除这个私有方法注释吧。

2024-12-25 07:57 UTC, gqcn commented on contrib/drivers/sqlite/sqlite_format_upsert.go
> +			case gdb.Counter, *gdb.Counter:
`contrib/drivers/sqlitecgo`也需要相应修改一下哈，那个组件是针对`32bit`系统的。

2024-12-26 10:18 UTC, gqcn approved these changes

2024-12-26 10:18 UTC, merged