fix(ci/golangci): fix golangcl-lint git push and apply format code on Push
gogf/gf pull request #4077
Opened 2024-12-24 10:20 UTC by houseme

2024-12-24 14:26 UTC, gqcn requested changes

2024-12-24 14:26 UTC, gqcn commented on .github/workflows/apply-format-code-on-push.yml
> +        run: |
这里是不是应该加上`GITHUB_TOKEN`的环境变量，便于`git`提交的权限设置。
```yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

2024-12-24 14:26 UTC, gqcn commented on .github/workflows/apply-format-code-on-push.yml
> +name: Apply format code on Push
名称是不是使用`Format code on Push`更合适一些？

2024-12-25 06:32 UTC, gqcn requested changes

2024-12-25 06:32 UTC, gqcn commented on .github/workflows/before_script.sh
> +# 安装 gci
在源码中统一使用英文注释。以下同理。可以使用AI编辑器来转换一下。

2024-12-25 06:32 UTC, gqcn commented on .github/workflows/format-code-on-push.yml
> +name: Format code on Push
是不是英文的首字母大写更统一一些？

2024-12-25 07:41 UTC, houseme commented on .github/workflows/before_script.sh
> +# 安装 gci
done

2024-12-25 07:41 UTC, houseme commented on .github/workflows/format-code-on-push.yml
> +name: Format code on Push
改了

2024-12-25 13:24 UTC, gqcn approved these changes

2024-12-26 02:19 UTC, merged